### ISSUE TITLE
<M-f> opens search

### ISSUE THREAD

**Issue by felberj** [hackmdio/hackmd-io-issues#10]
In emacs mode, `<M-f>` (alt + f) opens search.
I think that (at least in emacs mode) the cursor should jump one word forward.

Tested on osx with safari and chrome.

See: https://github.com/hackmdio/hackmd/issues/759

**Comment by felberj** [comment]
### Expected
Also described in the lined issue:
In this hackmd: https://hackmd-ce.herokuapp.com/vecwMfsTRTq2st9U2WdKBA?both

if I have the cursor here:
```
Writing some stuff
--------^
```

And press alt-f, it jumps here:

```
Writing some stuff
-----------^
```

This is the expected (emacs) behaviour.
Note that I mapped alt-f to "moveWordForward:" in my operating system.

### got

in https://hackmd.io/PU6MJcXbTFyc8AFr1JxWyA it opens the search bar.

### want

at least in emacs mode, do not rebind alt-f or allow me to disable it, as it is intended to jump words

**Comment by mavenlin** [comment]
@jackycute In emacs, `alt-f`/`meta-f` is bound to moving the cursor forward, not search. Consider bind `ctrl-s` to search, or at least give the configuration option to user.

**Comment by mavenlin** [comment]
Is there a plan for this issue?
It is solved for codimd. https://github.com/hackmdio/codimd/issues/759

**Comment by haochenx** [comment]
is there a plan to fix for this issue? it's a deal breaker for many emacs users (as for me) I guess.

it is a worse user experience even compared to completely disabling all keyboard shortcuts, since then we could use system / browser shortcuts that we are familiar with (e.g. on macOS most emacs style cursor movement keybindings works almost anywhere).

**Comment by jackycute** [comment]
Hi everyone,
Sorry this took a long while.
We have deployed a fix few days ago, please try and let us know if this works as you expected, thanks!

**Comment by mavenlin** [comment]
> Hi everyone, Sorry this took a long while. We have deployed a fix few days ago, please try and let us know if this works as you expected, thanks!

Just confirmed it works, thanks for fixing it.
