### ISSUE TITLE
Add the mode dropdown / slides mode to anonymous users?

### ISSUE THREAD

**Issue by t829702** [hackmdio/hackmd-io-issues#105]
**Is your feature request related to a problem? Please describe.**
Anonymous users are allowed to create md files and share but there's no mode dropdown
https://hackmd.io/s/BybnsNINr

When I was reading this tutorial, I didn't see anywhere say it requires logged in
https://hackmd.io/c/tutorials/%2Fs%2Fhow-to-create-slide-deck

**Describe the solution you'd like**
open the mode dropdown to Anonymous users

under some privacy context, it would be very nice to be able share slides with Anonymous (private browsing with Tor)

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/49542456/63219531-53c85000-c128-11e9-8f41-8f1f20a25a11.png)

**Comment by GitOnion** [comment]
Thanks for raising this use case to our attention. We currently have to focus our energy on mainstream use cases and will come back to this issue later when we have more resources!
