### ISSUE TITLE
Documentation on templates unclear

### ISSUE THREAD

**Issue by reagle** [hackmdio/hackmd-io-issues#107]
Your [documentation says](https://hackmd.io/c/tutorials/%2Fs%2Fhow-to-use-template) "Editing template is pretty much the same as editing regular notes - all your edits will be automatically saved, except you will see a green banner telling you that you’re editing a template." It doesn't say if such edits are then propagated to every page using that template.

**Comment by jackycute** [comment]
Hi @reagle,
No, it won't propagate to the page that created from the template.

**Comment by jackycute** [comment]
If you're seeking a way to reference a note that can be updated, you can try to embed a note: https://hackmd.io/c/tutorials/%2Fs%2Fhow-to-embed-note
