### ISSUE TITLE
spoiler block is o

### ISSUE THREAD

**Issue by reagle** [hackmdio/hackmd-io-issues#109]
Following #101, spoiler is offered in the autocomplete but has no special rendering

```
:::spoiler
spoiler
:::
```
<img width="757" alt="Screen Shot 2019-08-21 at 3 25 00 PM" src="https://user-images.githubusercontent.com/596814/63462033-faae3400-c427-11e9-84d8-5d3bbfc06d4c.png">

**Comment by jackycute** [comment]
Hi @reagle 
In current implementation, you have put text after `:::spoiler`, like this:
```
:::spoiler click me
content
:::
```

Then it will be able to render.

**Comment by reagle** [comment]
Ah, that's confusing because none of the others work that way and the spoiler autocomplete still places the cursor at content. Perhaps the autocomplete should include the "click me."

**Comment by jackycute** [comment]
> Ah, that's confusing because none of the others work that way and the spoiler autocomplete still places the cursor at content. Perhaps the autocomplete should include the "click me."

I agree with you.

**Comment by Yukaii** [comment]
Let's open a separate issue for tracking this

**Comment by reagle** [comment]
@Yukaii did you open one, what number?

**Comment by Yukaii** [comment]
@reagle Thanks for the reminder, open an issue in CodiMD: https://github.com/hackmdio/codimd/issues/1265
