### ISSUE TITLE
HackMD.io help modal points to wrong issue tracker

### ISSUE THREAD

**Issue by SISheogorath** [hackmdio/hackmd-io-issues#11]
Currently the "report an issue" link points to https://github.com/hackmdio/hackmd/issues instead of https://github.com/hackmdio/hackmd-io-issues/issues

This probably misleads people where to open an bug report.

Would be nice when it gets fixed :)

**Comment by jackycute** [comment]
Thanks @SISheogorath 
Fixed now.
