### ISSUE TITLE
Does clicking on a link always require a new tab?

### ISSUE THREAD

**Issue by reagle** [hackmdio/hackmd-io-issues#110]
Is there a way to configure whether you want clicked links to open in a new tab or not?

**Comment by jackycute** [comment]
Hi @reagle,
The default link behavior will always open in new tab.
If you like change this, you can use HTML:

```
<a href="https://google.com" target="_self">Go to Google</a>
```

**Comment by reagle** [comment]
I don't think that should be the standard behavior, but I suspect your users are already used to it and isn't likely to change...

**Comment by jackycute** [comment]
So the first intention was: you won't likely to click out when you're editing a note.
