### ISSUE TITLE
Syntax highlighting breaking

### ISSUE THREAD

**Issue by ddejohn** [hackmdio/hackmd-io-issues#111]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem

Syntax highlighting breaks after using a LaTeX math block.

#### Current behaviour

Here is syntax highlighting working: https://i.imgur.com/mWrGcbO.png

Converting the inline math to a math block breaks the highlighting for the rest of the document: https://i.imgur.com/6FipNlv.png

**See line 47 in the screenshots.**

#### Steps to reproduce

1. Put some markdown in your document. 
2. Put a math block (LaTeX between **double** dollar signs) before the markdown.
3. Markdown syntax highlighting is broken.

I use HackMD on:

**Desktop**
- OS: W10
- Browser: Chrome
- Browser Version: 76.0.3809.100

It's not the end of the world, but when managing a large document, it is frustrating not having the visual aid for being able to find certain parts to edit.

**Comment by jackycute** [comment]
Hi @ddejohn,
For inline math, the syntax is using **single** dollar sign to surround math.
like:
```
$a = b + c$
```

For block math, the syntax is using **double** dollar sign and newlines to surround math.
like:
```
$$
a = b + c
$$
```

So that the syntax highlighting will be rendered properly.

**Comment by ddejohn** [comment]
Weeelp I feel like an idiot.
