### ISSUE TITLE
Can't push to github file with space in name

### ISSUE THREAD

**Issue by nbrachet** [hackmdio/hackmd-io-issues#113]
### Is this a hackmd.io issue?

- [X] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem

Can't push a note to GitHub with space in the name.

#### Current behaviour

Provide steps to reproduce:

1. Create a note
2. Push the version to GitHub
3. In the "Select File" field enter: "Something with a space"
4. See how the "Create a new file" option disappears.

#### Expected behaviour

I should be able to name a note with a space.

#### Environment

I use HackMD on:

**Desktop**
- OS: macOS
- Browser: chrome
- Browser Version: 76

**Comment by jackycute** [comment]
Hi, @nbrachet 
We've tried to fix this issue, could you help us to double check?

**Comment by jackycute** [comment]
Feel free to reopen if you can reproduce :)

**Comment by nbrachet** [comment]
Sorry for the late response. Works like a charm!
