### ISSUE TITLE
Invite link looks like a phishing attempt

### ISSUE THREAD

**Issue by murbard** [hackmdio/hackmd-io-issues#115]
### Is this a hackmd.io issue?

- [X] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### Read our Official tutorial

It's on https://hackmd.io/c/tutorials/

或是中文版 https://hackmd.io/c/tutorials-tw/

### What's the problem

When inviting people to collaborate, instead of receiving a link to hackmd.io, they receive a link to https://wmlc2cvj.r.us-east-1.awstrack.me/L0/https:%2F%2Fhackmd.io%..... with the <a> text looking like it's a link  to hackmd.io.

This makes it look like a bad phishing attempt.

#### Current behaviour

> Screenshot (optional)

Provide steps to reproduce:

1. Create a document on hackmd.io
2. Add collaborators by entering their email
3. They get an email with a link that looks like it's to hackmd.dio
4. But it's too some aws tracker instead 
5. Collaborator follows good security practices and reports spam
6. Sadness

If possible, create a note with reproducible content and share the link with us.

e.g. note link: https://hackmd.io/features

#### Expected behaviour

Users get a real link to hackmd.io which does whatever tracking it thinks it needs to do on its own domain

#### Environment

I use HackMD on:

**Desktop**
- Chrome

#### Fix

Turn off simple email tracking in AWS.

**Comment by jackycute** [comment]
Hi @murbard, thanks for reaching us @murbard.
However, we need this email tracking to understand if user's email is reachable.
We will research better resolution for this.

**Comment by didiksupriadi41** [comment]
Yeh, when I received the "Please confirm your email address" email, this is occured to me.

![](https://i.imgur.com/khjuv3f.png)
