### ISSUE TITLE
How to add more than 3 team members?

### ISSUE THREAD

**Issue by cbenz** [hackmdio/hackmd-io-issues#116]
I created a team, added 2 other members, then when clicking on "add" in https://hackmd.io/team/{myteam}/manage I have the error: 

> Team member quota has reached

![image](https://user-images.githubusercontent.com/12686/64277506-ccae1100-cf4a-11e9-9891-bbf38d54bb94.png)

I don't find any "pricing" page or indication about how to bypass this limit.

**Comment by jackycute** [comment]
Hi @cbenz, you can now check the pricing page at: https://hackmd.io/pricing
