### ISSUE TITLE
Enable  Julia Lang code highlighting  

### ISSUE THREAD

**Issue by lrsantos11** [hackmdio/hackmd-io-issues#117]
I love hackmd. I really want to use it to teach Julia Lang (www.julialang.org). However the code highlighting for it is not enable.

I notice that you use highlightjs (https://highlightjs.org/). So it is very easy to enable this feature. Just download the api, now with julia lang highlight. 

I noted that CodiMD already has this feature enabled, so I hope you could provide this very soon. 

 Thanks again Guys.

**Comment by lrsantos11** [comment]
Seems like CodiMD fix this  here https://github.com/hackmdio/codimd/pull/1004. So it is very easy indeed

**Comment by jackycute** [comment]
Julia syntax highlighting is now supported.
