### ISSUE TITLE
Scrolling issue on phone

### ISSUE THREAD

**Issue by afaa97** [hackmdio/hackmd-io-issues#119]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io

### What's the problem

When I visit my notes in book mode on my phone, the scrolling keeps jittering in a weird way. I tried to replicate it without book mode and it doesn't happen.

#### Current behavior

![GIF](https://user-images.githubusercontent.com/31856635/64925714-e245f500-d7ec-11e9-9393-7df6227ed2ec.gif)

#### Steps to reproduce:

**1.** Go to hackmd and create a book with some pages;
**2.** Generate a link to the book;
**3.** Visit that link **on your phone** and scroll down;
**4.** The jittering appears.

#### Expected behaviour

It's expected to work normally without that jittering.

### Environment

I use HackMD on:

**Mobile**

- Device: Huawei P9 Lite
- OS: Android 6.0
- Browser: Chrome
- Version: Latest (77.0.3865.73)

#### Additional context

- My google chrome was outdated, I updated it but I still got the same bug.
- I didn't use other browsers to test this.
- Everything else works fine on my computer and phone.
- I haven't updated my phone in a while, maybe it's because of that?

**Comment by jackycute** [comment]
Do you still experiencing this @RedWavez ?

**Comment by jackycute** [comment]
Please reopen if you still have this issue @RedWavez, thanks!
