### ISSUE TITLE
Task list and <label> tag option

### ISSUE THREAD

**Issue by Tatsh** [hackmdio/hackmd-io-issues#12]
`- [ ] text` should have a `<label>` tag wrapped around the text:

```html
<label><input type="checkbox">text</label>
```

Right now an empty `<label>` tag appears.

```html
<li class="task-list-item" data-startline="5" data-endline="5">
  <input type="checkbox" class="task-list-item-checkbox" checked="">
  <label></label>
  text
</li>
```

Am I supposed to do a checklist differently to get the label to render correctly? I know this isn't standard and even GitHub does not do it, but this is normal behaviour on virtually any other UI (macOS, Windows, KDE). It is far easier to click on this than to focus on the checkbox.

[CodePen example](https://codepen.io/anon/pen/OvrEVr)

Sometimes the cursor is left as text selection (`cursor: text`) so users don't think the text is not select-able. `<label>` uses `cursor: default` by default in all major browsers.

**Comment by jackycute** [comment]
Hi @Tatsh 
Thanks for giving us suggestion!
So the this is by design to avoid using label here letting user select list item text without check the box accidentally.

**Comment by Tatsh** [comment]
Option in the YAML or new tag in the future? Something like `* [ ]`?
