### ISSUE TITLE
floating table of content

### ISSUE THREAD

**Issue by artagmaz** [hackmdio/hackmd-io-issues#120]
Hello! Is there any possibility to save the floating table of content in GitHub?

**Comment by jackycute** [comment]
Hi @artagmaz,
Could you give us some example? I'm not completely sure what you want.
GitHub's markdown rendering doesn't support CSS style tag, so maybe this won't be much possible.

**Comment by jackycute** [comment]
Feel free to reopen this if you can provide more clear context of the issue @artagmaz!
