### ISSUE TITLE
spoiler should allow in-line formatting like code, bold, italic

### ISSUE THREAD

**Issue by ssbarnea** [hackmdio/hackmd-io-issues#123]
Ar this moment you can only write plain text for spoiler and this prevents adding expansable section for shell commands because
```
:::spoler `rm -rf /`
oops.... you did it
:::
```
For example the example above goes unformatted but it should be formatted.

**Comment by jackycute** [comment]
We've supported this feature, thanks for suggestion @ssbarnea!
