### ISSUE TITLE
Only view with link

### ISSUE THREAD

**Issue by richardvanthof** [hackmdio/hackmd-io-issues#124]
**Is your feature request related to a problem? Please describe.**
I often want to share my posts with people that don't use hackmd.io. But I do not always want my notes to be findable via a search engine or my profile page without having to log in.

**Describe the solution you'd like**
An option to only share with people who have the link. (A feature similar to what's availible in Google Drive)

**Comment by jackycute** [comment]
Hi @RichART-Official, thanks for reaching us.
I think we already have this feature, please read more here: https://hackmd.io/c/tutorials/%2Fs%2Finvite
