### ISSUE TITLE
Support multiple tags categories in "My Notes" page

### ISSUE THREAD

**Issue by Sean1127** [hackmdio/hackmd-io-issues#125]
Currently the first tag of each note is used as its category.
How can I use ALL tags as its categories?
Or is there an option where I can choose "I want to use the first N tags as categories"?

**Comment by jackycute** [comment]
Hi @Sean1127,
We've added the tags filter just now:

<img width="672" alt="螢幕快照 2019-11-13 下午3 10 54" src="https://user-images.githubusercontent.com/2639151/68741132-d24d6480-0627-11ea-8521-37a0d8b4a148.png">
