### ISSUE TITLE
Broken drop down menu in "Overview" page

### ISSUE THREAD

**Issue by Sean1127** [hackmdio/hackmd-io-issues#126]
Windows 10 professional 1903
Chrome 77.0.3865.120

My account->Settings or Profile, there is a "HackMD" logo as a drop down on the top-left of the screen.
On click, it show a little while bar.

I do not know what to expected, as this is probably an unfinished feature?

This is not a beta issue, the original page has the same problem.

![tempsnip](https://user-images.githubusercontent.com/11289467/67922796-d10f4700-fbe6-11e9-869a-a4abed204620.png)

**Comment by jackycute** [comment]
Hi @Sean1127,
We reserved that dropdown for create a team button, now should be available.
Thanks for reporting!
