### ISSUE TITLE
GraphQL syntax highligting

### ISSUE THREAD

**Issue by emil-nasso** [hackmdio/hackmd-io-issues#130]
**Is your feature request related to a problem? Please describe.**
Wouldn't really call it a problem.

**Describe the solution you'd like**
When you type \`\`\` in hackmd you are presented in with many choices of different languages and types of "code" to get proper syntax highlighting. I would like GraphQL to be added. We often use graphql-schemas as a type of documentation. We often use hackmd for initial refinement of new features and work to be done. We use it as a collaborate platform to work towards a solution that we want to implement. Part of that is writing the final graphql schema that we will implement.

Being able to properly syntax highlight graphql-schemas would be great! 

**Describe alternatives you've considered**
You can use something like the json-highlighting but its not perfect... Or other tools.... but we love hackmd and don't want to use other tools! :) 

**Additional context**
Don't think it's needed.

**Comment by pedenys** [comment]
It would be nice indeed, as GraphQL allows kind of self-documenting API as far as I know.

**Comment by jackycute** [comment]
GraphQL syntax highlighting is now supported.
