### ISSUE TITLE
Username field is incorrectly populated in Settings -> General

### ISSUE THREAD

**Issue by benjaminion** [hackmdio/hackmd-io-issues#132]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io

### What's the problem

When visiting the Settings->General page, the Username field is pre-filled with my email address instead of my username.

This means that
1. I can't see my username (it appears very briefly before being overwritten by the email address), and
1. When I try to Save the page I get a "Please match the requested format." error on the Username field as a result of this.

#### Current behaviour

Provide steps to reproduce:

1. Go to [Settings -> General](https://hackmd.io/settings#general)
1. See error

#### Expected behaviour

I expect the Username field to be populated with my username 😄 

#### Environment

**Desktop**
- OS: Windows
- Browser (same problem on all of the following):
   - FireFox 70.0.1 (64-bit)
   - Brave Version 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit)
   - Chrome Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by jackycute** [comment]
Hi @benjaminion,
Thanks for reporting to us.
I don't see this issue on my side.
Could this be auto filled by your browser? Could you try other browser if this might reproduce?

**Comment by benjaminion** [comment]
Ah, you are right. It seems to be some bad interaction with my password manager. I've worked around this and will close the issue. Thanks for looking into it!
