### ISSUE TITLE
Not work export to google drive

### ISSUE THREAD

**Issue by rmuhamedgaliev** [hackmdio/hackmd-io-issues#137]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

#### Current behaviour

![alt](https://i.imgur.com/mymKWsq.jpg)

Provide steps to reproduce:

1. Go to edit post
2. Click on export to Google Drive
3. See error

If possible, create a note with reproducible content and share the link with us.

e.g. note link: https://hackmd.io/features

#### Expected behaviour

Dockumend should be exported to Google Drive

#### Environment

I use HackMD on:

**Desktop**
- OS: macOS
- Browser: chrome
- Browser Version: 71

**Comment by jackycute** [comment]
Do you still experiencing this @rmuhamedgaliev?

**Comment by rmuhamedgaliev** [comment]
@rmuhamedgaliev no, just close. I'm forget this issue

**Comment by jackycute** [comment]
OK, feel free to reopen if you encounter this in the future.
