### ISSUE TITLE
The new book mode design causes nodes not accessible in a long list

### ISSUE THREAD

**Issue by brlin-tw** [hackmdio/hackmd-io-issues#139]
### Workaround
Filter out the desired node via the search bar.

### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

#### Current behaviour
Refer the following screenshot:

![Screenshot_20191225_101050](https://user-images.githubusercontent.com/13408130/71428922-dc6e8280-26fe-11ea-88c9-b4ad78a69fde.png)

The nodes under "Monitoring modules" are not accessible when the navigation(left) pane is already scrolled to the very end.

Provide steps to reproduce:

0. Login to an account
1. Go to <https://hackmd.io/@brlin/orncb-ansible-module-index/https%3A%2F%2Fhackmd.io%2F%40brlin%2Forncb-ansible-module-index%2Fedit%3Fedit>
2. Hover pointer to the left pane
3. Scroll down to the very end
4. Verify whether the last node in the list is accessible

#### Expected behaviour

Every node in the book is accessible in the left pane

#### Environment

I use HackMD on:

**Desktop**
- OS: Ubuntu 18.04
- Browser: Mozilla Firefox
- Browser Version: 71.0

**Comment by jackycute** [comment]
Thanks for reporting, we've fixed this.
