### ISSUE TITLE
HackMD-it homepage 404's

### ISSUE THREAD

**Issue by gene1wood** [hackmdio/hackmd-io-issues#14]
The homepage configured for the [HackMD-it](https://addons.mozilla.org/en-US/firefox/addon/hackmd-it/) firefox add-on is https://github.com/hackmdio/hackmd-it-issues which 404's. I'm guessing it should be https://github.com/hackmdio/hackmd-io-issues

Or you should setup that repo, `hackmd-it-issues`.

**Comment by jackycute** [comment]
Thanks @gene1wood 
It's now opening: https://github.com/hackmdio/hackmd-it-issues
