### ISSUE TITLE
The book mode update breaks headings with linebreaks and links

### ISSUE THREAD

**Issue by brlin-tw** [hackmdio/hackmd-io-issues#140]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

#### Current behaviour
Refer the following screenshot:

![Screenshot_20191225_102115](https://user-images.githubusercontent.com/13408130/71429327-ff019b00-2700-11ea-9826-5a09362945f6.png)

Provide steps to reproduce:

1. Go to <https://hackmd.io/@brlin/once-read-never-come-back/https%3A%2F%2Fhackmd.io%2F%40brlin%2Fonce-read-never-come-back%2Fedit%3Fedit>
2. Refer the navigation(left) pane

#### Expected behaviour

`<br>` in the heading markup properly breaks the heading in the navigation pane

#### Environment

I use HackMD on:

**Desktop**
- OS: Ubuntu 18.04
- Browser: Mozilla Firefox
- Browser Version: 71.0

**Comment by Yukaii** [comment]
![Screen Shot 2019-12-25 at 1 55 34 PM](https://user-images.githubusercontent.com/4230968/71434281-ad680900-271e-11ea-8c25-97207172779e.png)

@Lin-Buo-Ren 調整了 styling 這樣 OK 嗎？

**Comment by brlin-tw** [comment]
可以，感謝協助

**Comment by jackycute** [comment]
Thanks for reporting, we've fixed this.
