### ISSUE TITLE
手機版頁面 選單不正常出現

### ISSUE THREAD

**Issue by CA-Lee** [hackmdio/hackmd-io-issues#142]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### Read our Official tutorial

It's on https://hackmd.io/c/tutorials/

或是中文版 https://hackmd.io/c/tutorials-tw/

#### Current behaviour

> Screenshot (optional)
![Screenshot_20191231-154503](https://user-images.githubusercontent.com/31626425/71614276-abea8500-2be5-11ea-9c2b-7e133ac6e585.png)

Provide steps to reproduce:

1.使用手機開啟hackmd.io
2.新增筆記
3.點選≡ > 共享
4.返回編輯畫面
5.點擊編輯區任意位置，顯示游標
6.向左滑

If possible, create a note with reproducible content and share the link with us.

e.g. note link: https://hackmd.io/features

#### Expected behaviour

(description of expected behaviour)
無法向左滑，或是選單直接覆蓋編輯區呈現，或完整顯示選單，不會出現如截圖的畫面。

#### Environment

I use HackMD on:

**Desktop**
- OS: 
- Browser: 
- Browser Version: 

**Mobile**

- Device: SONY G3426
- OS: Android 8.0.0
- Browser: Chrome/加至主畫面
- Version: [e.g. 23]

#### Additional context

不知道是不是Feature，剛才約略看了一下沒有看到類似的bug reports。

**Comment by jackycute** [comment]
請問目前此問題還有發生嗎？ @CA-Lee

**Comment by CA-Lee** [comment]
剛剛測試了 已經不會發生此狀況了 謝謝

**Comment by jackycute** [comment]
@CA-Lee 謝謝協助回報與測試！
