### ISSUE TITLE
hackmd.io down

### ISSUE THREAD

**Issue by bencardoen** [hackmdio/hackmd-io-issues#143]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### Read our Official tutorial

It's on https://hackmd.io/c/tutorials/

或是中文版 https://hackmd.io/c/tutorials-tw/

### What's the problem
Site unreachable

#### Current behaviour

> Screenshot (optional)

Provide steps to reproduce:

hackmd.io

If possible, create a note with reproducible content and share the link with us.

e.g. note link: https://hackmd.io/features

#### Expected behaviour
Response of the site

(description of expected behaviour)

#### Environment

I use HackMD on:

**Desktop**
- OS: [eg. macOS]
- Browser: [e.g. chrome, safari, firefox, opera]
Chrome, Opera, Firefox
- Browser Version: [71]

**Mobile**

- Device: [e.g. iPhone XS]
- OS: [e.g. iOS 12.1]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 23]

**Comment by jackycute** [comment]
Service now is recovered, thanks for reporting.
