### ISSUE TITLE
Filtering by tag on the profile page

### ISSUE THREAD

**Issue by benjaminion** [hackmdio/hackmd-io-issues#147]
**Is your feature request related to a problem? Please describe.**
My [profile page](https://hackmd.io/@benjaminion) is of limited use because it shows all my published content mixed up.

**Describe the solution you'd like**
Allow filtering of published articles by tag embedded in the URL query.

For example:

    https://hackmd.io/@username?tag=tagname

Or

    https://hackmd.io/@username?tags=tagname1,tagname2

**Describe alternatives you've considered**
This can be simulated by with the currently available search functionality:

    https://hackmd.io/@username?q=tagname

But this is unreliable if the tagname appears in the text of an article not so tagged.

**Comment by jackycute** [comment]
Hi @benjaminion,
Thanks for reaching us.
You can now select tags for filtering on profile page.
