### ISSUE TITLE
No centralized place where on can link or unlink all four Facebook, Twitter, GitHub, or Dropbox 

### ISSUE THREAD

**Issue by jidanni** [hackmdio/hackmd-io-issues#15]
On https://hackmd.io/features one reads
```
You can sign-in via Facebook, Twitter, GitHub, or Dropbox in the homepage.
```
Alas there is no standard page where one can link or unlink all four.

It's not in Settings.

Apparently the only way to manipulate them is first logout then login...

OK doing that shows currently
```
Choose method
Sign in via Facebook
Sign in via Twitter
Sign in via GitHub
Sign in via Dropbox
Sign in via Google
```
but after the user chooses one, there is no place where he can link/unlink all of them.

**Comment by jackycute** [comment]
We are now supporting to connect all your sign-in methods into one account at https://hackmd.io/settings.

<img width="545" alt="螢幕快照 2019-08-07 下午9 58 21" src="https://user-images.githubusercontent.com/2639151/62628777-8b800c80-b95e-11e9-9a7d-5e2f47bf39a6.png">

Enjoy!
