### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by AarghIMApiratez** [hackmdio/hackmd-io-issues#150]
I have multiple books with multiple long pages. (Think notes from lectures or similar).

I would like a basic search function. Search all my notes for a simple string.

The only thing I can find is search tags.

**Comment by themedleb** [comment]
Searching the content of the notes is a must, I don't know how long it will take to get implemented though.

**Comment by jackycute** [comment]
Thanks for reaching us.
Duplicate #153
