### ISSUE TITLE
Why can't I search text?

### ISSUE THREAD

**Issue by tongzhou80** [hackmdio/hackmd-io-issues#153]
![image](https://user-images.githubusercontent.com/7697776/73127722-cae4f880-3f92-11ea-809d-6e20449fd3fe.png)
In the search bar in the home page, I can't seem to search notes that contain the keyword I am searching  even though  some notes do contain it
.

**Comment by zippy** [comment]
What is the status on this feature.  It's really important!

**Comment by runjvm** [comment]
I am no longer using hackmd much as it lacks this basic functionality and nobody seems to care.

**Comment by themedleb** [comment]
Once I started using it, I noticed that too, unfortunately no official statement on this important basic feature.

**Comment by themedleb** [comment]
@runjvm Can you please tell what do you use now?

**Comment by runjvm** [comment]
@themedleb Hi, I am primarily using MS OneNote and google keep for notes keeping. And sometimes use HackMD for markdown notes sharing.

**Comment by themedleb** [comment]
@runjvm Thanks for the reply.

**Comment by themikesam** [comment]
I have requested this feature since I started to use, they mentioned this is in their roadmap at that time, but it was a few years ago.  😢

**Comment by jackycute** [comment]
Hi guys, thanks for keeping this issue in track.

However, building a full-text search for all users require a robust architecture and will introduce huge cost, we still yet break even.
We've been thinking about this many times and hopefully this can be put into roadmap of year 2021.

**Comment by syenchuk** [comment]
Hi Max Wu,

That's a really important feature. Unlike other solutions, HackMD doesn't offer a lot of options for organising documents.

This is fine with a good full-text search. But without it, it can be really hard to find what we're looking for (especially with teams… which happen to be the users who are ready to pay for features).

Can I help? If your target is 2021, I believe I could get it done in a scalable manner.

**Comment by tongzhou80** [comment]
For non-real-time collaborative situations, I strongly recommend typora (
https://typora.io/) for local editing and use git to back up and sync up
across laptops.

**Comment by jackycute** [comment]
Hi guys,
Sorry this took a long while,
We have supported full-text search for Prime plan from May, 2022. You can read changelog here: https://blog.hackmd.io/changelog?utm_source=home&utm_medium=nav-bar#2022-05-26
