### ISSUE TITLE
.Rmd files

### ISSUE THREAD

**Issue by RichardJActon** [hackmdio/hackmd-io-issues#154]
I would like to be able to edit R markdown files in a GitHub repository with HackMD but only files with .md extension are listed in the interface for setting up GitHub sync. Would it be possible to add an option to show other non-.md but still text-based files with different extentions to this menu?

**Comment by jackycute** [comment]
Hi guys, thanks for bringing this up!

We’ve updated our service and now should support .Rmd for GitHub sync.
Please try if you can do that :)

**Comment by nuest** [comment]
Awesome reaction time - thanks!
