### ISSUE TITLE
Nested list

### ISSUE THREAD

**Issue by reagle** [hackmdio/hackmd-io-issues#156]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io

#### Current behaviour

Notice the first subelement ("a. Digital Natives...") in the 2nd nested list is leftward. Why? Does HackMD support nested lists?

<img width="1153" alt="Screen Shot 2020-02-14 at 9 21 48 AM" src="https://user-images.githubusercontent.com/596814/74539203-9ddd9300-4f0b-11ea-9dba-d90a00ebe4a8.png">

e.g. note link: https://hackmd.io/1bidbkCOQ_SyTFJ3oHrwuA?both

**Comment by jackycute** [comment]
Hi @reagle,

Thanks for reaching us.
Yes, I think we do support nested list.

However, I noticed that the note you gave as reference has a problem that the padding before b. c. d. are mixed with space (utf8 `20`) and non-breaking space (utf8 `C2 A0`) and that will become two different lists according to the CommonMark spec (the list level also determine by the padding counts). Replacing all the padding to normal spaces can solve this issue.

**Comment by reagle** [comment]
Okay, I did try spacing or tabbing over the padding in a, but not the others. Not sure how the student managed to mix the two, perhaps pasting from something else.

(I wasn't sure if it was parsing as a nested list because I'm used to being able to have "1. ... 1. ... 1. ..." auto-numbered by the processor (perhaps a pandoc-ism) and my editor auto-incrementing after a carriage-return, which hackMD does for numbers but not letters.)
