### ISSUE TITLE
Cannot delete latex code selected with vim-visual selection

### ISSUE THREAD

**Issue by f-t-s** [hackmdio/hackmd-io-issues#157]
### Is this a hackmd.io issue?
- [x] Yes, the bug happens on https://hackmd.io

### What's the problem
Cannot delete marked latex in visual selection mode

#### Current behaviour
Currently, when using the vim-visual selection mode to mark latex code and then pressing "d", which should delete the code, nothing happens and instead the green light of the visual selection keeps blinking.

> Screenshot (optional)

Provide steps to reproduce:

1. Open new document,
2. Enter "$\int \limits_0^\pi x^2 dx$" into the document
3. Use visual selection of vim mode to select some of the latex-code
4. Press d: nothing happens

note link: https://hackmd.io/@HkbvxGw0Sqm3JZ2amYOFxg/rkgHxBI7I

#### Expected behaviour

Should delete the selected text

#### Environment

I use HackMD on:

**Desktop**
- Linux
- Chrome 
- Version 79.0.3945.117 (Official Build) (64-bit)

**Comment by WildfootW** [comment]
I have same issue with all operation after selection (whatever latex code or not). And I need to refresh whole page after the bug happen.

**Comment by jackycute** [comment]
Hi guys, thanks for reporting this.
We've found the bug which triggered on vim delete for updating the authorship inline marker.

We'll deploy a fix soon.

**Comment by FongX777** [comment]
I've met similar issues but not only happens in Latex but everywhere.

* OS: macOS
* Environment: Firefox 73.0.1 & chrome 79.0.3945.130 

Vim mode would be broken after a period of time, especially when I wanted to delete some words (`d`),  but nothing was deleted and green light cursors showed up.

Then the line can not be deleted by `d`, and `d`, `x` was mapped to 'visual select' key like the picture below.

![圖片](https://user-images.githubusercontent.com/14963179/75133516-1c111500-5716-11ea-8b9e-725801c8e0c8.png)

---

Fastest way to reproduce the bug:

1. use `V` to select multiple lines
2. press `d`, then the selected lines are not be deleted but a green light cursor shows up.

**Comment by jackycute** [comment]
Hi guys, thanks for reporting to us.
We've deployed a fix for the issue.
Please try if you can reproduce this and feel free to reopen.
