### ISSUE TITLE
Weird rendering of 2 unordered lists

### ISSUE THREAD

**Issue by michcio1234** [hackmdio/hackmd-io-issues#159]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem

When I want 2 bullet lists not separated by a new paragraph, they render as one list where every element is a separate paragraph.

#### Current behaviour

![image](https://user-images.githubusercontent.com/16254622/74914189-47b49800-53c2-11ea-97e1-6ceb3ae81283.png)

https://hackmd.io/@michcio1234/rkmO0ns7U

#### Expected behaviour

I would like to see two lists separated by some blank space, each with smaller spacing.

#### Environment

I use HackMD on:

**Desktop**
- OS: Linux Mint
- Browser: Chrome
- Browser Version: 79.0.3945.88 (Official Build) (64-bit)

**Comment by jackycute** [comment]
Hi @michcio1234 
Thanks for reaching us.

However, that's part of CommonMark spec, please take a look at:
https://spec.commonmark.org/0.29/#loose

> A list is loose if any of its constituent list items are separated by blank lines, or if any of its constituent list items directly contain two block-level elements with a blank line between them. Otherwise a list is tight. (The difference in HTML output is that paragraphs in a loose list are wrapped in `<p>` tags, while paragraphs in a tight list are not.)

**Comment by jackycute** [comment]
Here are some examples that I think might fulfill your need:

1. put horizontal line between two lists
```
- one
- two
- three

---

- one
- two
- three
```

2. use other bullet type
```
- one
- two
- three

+ one
+ two
+ three
```

3. put empty space between two lists
```
- one
- two
- three

&nbsp;

- one
- two
- three
```

**Comment by michcio1234** [comment]
Ah, okay, I wasn't able to find this specification. Thanks for clarification!
