### ISSUE TITLE
Book Mode: "Expand Menu" hint text wrongly surfaced in certain viewport widths

### ISSUE THREAD

**Issue by brlin-tw** [hackmdio/hackmd-io-issues#163]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io

#### Current behaviour

![HackMD issue reproduction clip: Book Mode:  Expand Menu  hint text wrongly surfaced in certain viewport widths](https://user-images.githubusercontent.com/13408130/75610810-9941ed00-5b4f-11ea-8e7b-7238bba623e9.gif)

Provide steps to reproduce:

1. Go to a HackMD note in Book Mode
2. Collapse the navigation menu by clicking the `>>` Button
3. Shrink screen width around 758~766px
4. The hint text of the "Expand Menu" button rendered out of the box/pane UI

bug reproduction note link: https://hackmd.io/@brlin/ryGHsWuNI

#### Expected behaviour

"Expand Menu" text should surface/submerge along with the navigation bar's horizontal/vertical design change

#### Environment

I use HackMD on:

**Desktop**
- OS:  ezgo 14 AMD64(Ubuntu 18.04)
- Browser: Mozilla Firefox
- Browser Version: 73.0.1

**Comment by jackycute** [comment]
Thanks for reporting this @Lin-Buo-Ren.
We've fixed this styling issue.
