### ISSUE TITLE
OSX scrolling with touchpad is flaky

### ISSUE THREAD

**Issue by Fohlen** [hackmdio/hackmd-io-issues#164]
### Is this a hackmd.io issue?

- [ ] Yes, the bug happens on https://hackmd.io

### What's the problem

When using touchpad (the default OSX input device) for scrolling navigation on HackMD the scrolling is flaky. Sometimes it will not really scroll, sometimes just a bit, sometimes it scrolls correctly. This behaviour is quite annoying, as it forces the user to use the scroll bar in the edit area.

#### Current behaviour

> Screenshot (optional)

Provide steps to reproduce:

1. Go to any HackMD note
2. Choose split mode (edit+view)
3. Try to scroll in the edit section

I uploaded a video for better understanding. See https://streamable.com/6rwkc.

#### Expected behaviour

It shouldn't be flaky 🍷 

#### Environment

I use HackMD on:

**Desktop**
- OS: macOS
- Browser: Chrome
- Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by jackycute** [comment]
Do you still experiencing this @Fohlen?
The video is no longer accessible.

**Comment by jackycute** [comment]
Feel free to re-open if this persists.
