### ISSUE TITLE
用iphone手機版網頁無法正常編輯

### ISSUE THREAD

**Issue by tshing** [hackmdio/hackmd-io-issues#165]
您好
在使用iphone手機版網頁時，使用藍芽鍵盤連接iphone，無法使用上下鍵，移動游標的所在行數位置，只會停留在同一行中，請問該如何處理呢？
謝謝

**Comment by reagle** [comment]
English translation:

> Hello
> When using the iPhone mobile version webpage, using the Bluetooth keyboard to connect to the iPhone, the up and down keys cannot be used, and the cursor position will only stay in the same line. What should I do?
> Thank you

**Comment by jackycute** [comment]
Hi @tshing, please upgrade your iOS to 13.1 and the keyboard arrow keys will work.
ref: #80
