### ISSUE TITLE
Graphviz renderings cause error message below the rendered graph.

### ISSUE THREAD

**Issue by karlb** [hackmdio/hackmd-io-issues#166]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io

### What's the problem

Graphviz renderings cause error message below the rendered graph.

#### Current behaviour

Below each graphviz graph, there is the error message `TypeError: ee.renderString(...).then(...).catch(...).finally is not a function`. This can be seen at the official features list at https://hackmd.io/s/features#Graphviz

#### Environment

Firefox 68.4.1esr (64-bit) on debian linux buster

**Comment by jackycute** [comment]
Hi @karlb, thanks for reporting.
We've deployed a fix for this. Feel free to reopen if you can reproduce after.
