### ISSUE TITLE
Button "Push to Github" after note creation

### ISSUE THREAD

**Issue by zhampu** [hackmdio/hackmd-io-issues#169]
In the creation of a new note I see "Push to Github" and once is pushed and the file is created a don't see where to push my changes once I work with my file again In HackMd.

How can I solve this?

**Comment by jackycute** [comment]
Hi @zhampu,
Please click the top right menu on the navbar and choose "Versions".
And you will see the "Push to GitHub" button there.

Read more here: https://hackmd.io/c/tutorials/%2Fs%2Flink-with-github

**Comment by zhampu** [comment]
thanks

**Comment by rupeshtiwari** [comment]
I am not able to push the button is disabled any guess why? 

![image](https://user-images.githubusercontent.com/330383/106306326-e5982000-622b-11eb-9e48-a9a508020c36.png)
