### ISSUE TITLE
Mermaid 的 Gantt 選項說明加上 axisFormat %-m/%-d

### ISSUE THREAD

**Issue by ycktw** [hackmdio/hackmd-io-issues#173]
Hi, 

由於 mermaid 裡面 dateformat 應該是很需要的選項,
能不能幫忙在 Mermaid 的 Gantt 選項 example 加上 axisFormat %-m/%-d 做為 dateFormat 的替代。
因為其實 dateFormat 沒有作用，目前的版本應該只有 axisFormat %-m/%-d 有用。

Many thanks,

**Comment by jackycute** [comment]
您好，目前此功能已經支援了喔！謝謝回報 @ycktw
