### ISSUE TITLE
Help should include information about shortcuts

### ISSUE THREAD

**Issue by rogargon** [hackmdio/hackmd-io-issues#179]
### Is this a hackmd.io issue?

- [ x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem

Really difficult to find the available shortcuts. Getting crazy looking for search and replace. I remember I did find it last time looking for it around the web using Google. Not so lucky this time

**Comment by jackycute** [comment]
Hi @rogargon,
Thanks for reporting to us.
We'll provide doc for this soon.

**Comment by jackycute** [comment]
Please read the doc here: https://hackmd.io/@docs/keyboard-shortcuts
Thank you!
