### ISSUE TITLE
Mathjax breaks highlighting

### ISSUE THREAD

**Issue by zclimber** [hackmdio/hackmd-io-issues#18]
MathJax display expressions ($$) at newline disable editor highlighting after it.
Example at https://hackmd.io/UBJm4aW-Rnq1XutBhr2wHw#
![default](https://user-images.githubusercontent.com/13508223/41498232-fc6d34fe-7170-11e8-8518-39e953bb0b55.png)

**Comment by idoleat** [comment]
Same here. :D

**Comment by jackycute** [comment]
Please leave a line above and below if you're using double dollar sign for block math syntax.
For example:

```
$$
a = b + c
$$
```
