### ISSUE TITLE
MathJax

### ISSUE THREAD

**Issue by birdx0810** [hackmdio/hackmd-io-issues#180]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem

Equation numbers sometimes fail to load, and shows up fine after refreshing a few times (which implies that the MathJax syntax shouldn't be wrong)

#### Current behaviour

> Screenshot (optional)
![image](https://user-images.githubusercontent.com/26107885/82811885-5d0af800-9ec4-11ea-84ac-42696c684957.png)

After changing somethings (typesetting or tag/label values), the MathJax fails to load the equation.

![image](https://user-images.githubusercontent.com/26107885/82812193-0baf3880-9ec5-11ea-8db6-847f8cc392c1.png)

Provide steps to reproduce:

1. Goto link below
2. Tweak values of Eq. 1, Eq. 2, Eq. 3
3. Equation fails to load

note link: https://hackmd.io/RR1KnBIHQ_-sZIgPLgbBTQ#mjx-eqn-1

#### Expected behaviour

You could tweak the tag and label values of Eq. 1, Eq. 2, and Eq. 3 which would fail to load, and ends up fine after refreshing a few times.

#### Environment

I use HackMD on:

**Desktop**
- OS: Windows 10 and Ubuntu 18.04
- Browser: Mozilla Firefox
- Browser Version: 76.0.1

**Comment by jackycute** [comment]
Hi @birdx0810,

Thanks for reporting. Could you try again if this still happening?

**Comment by birdx0810** [comment]
Still happening after removing `\label{1}` and adding it back. Probably got to do with the `\label` tag.

**Comment by jackycute** [comment]
We've deployed a new version which contains related fix, could you test if this issue still exists? @birdx0810

**Comment by jackycute** [comment]
Feel free to reopen if you can reproduce after we deployed the fix.

**Comment by JessRiedel** [comment]
I have been able to reproduce this issue.

https://hackmd.io/pcpfcjMXTW6Yr_60-OoeXw

<img width="808" alt="Screenshot 2023-09-28 at 1 04 45 PM" src="https://github.com/hackmdio/hackmd-io-issues/assets/16365564/586485db-5015-4f14-ab64-9d540749a0b2">

**Comment by JessRiedel** [comment]
Here is the code:

`First, the equations are not autonumbered; you have to number them yourself with a `\tag{...}` command (in addition to the ``\label{...}`` command) like this: $$x=y^2\tag{2}\label{myeq}$$ or
\begin{equation}
   \tag{5}\label{myneweq}
   d=4^y 
\end{equation}
after which you can reference them with ``\eqref{...}``: see equations $\eqref{myeq}$ and $\eqref{myneweq}$. Note that ``\eqref{...}`` needs to be enclosed in dollar signs within the text (unlike a real LaTeX file) to function correctly.`

And here is what it looks like when I re-load the entire webpage:

<img width="809" alt="Screenshot 2023-09-28 at 1 06 52 PM" src="https://github.com/hackmdio/hackmd-io-issues/assets/16365564/6c448e45-c0d0-40a8-8d32-9b726d7a5526">

Note that this isn't really consistently repeatable.  Often, reloading the webpage isn't enough. And sometimes it renders correctly after changing an equation with a label in it without reloading.

**Comment by aakhmetz** [comment]
I have also noticed is that if I used multiline equation, I would not get tag/label working at all.

For example:
```
\begin{equation}\label{Ai}\tag{2.1.1}
\begin{split}\mathcal A_i = \bigl\{[0{-}4], [5{-}11], [12{-}16], [17{-}24], [25{-}34],\\ [35{-}44], [45{-}54],[55{-}64], [65{-}74], [75{+}]\bigr\}\end{split}
\end{equation}
```
gives:
![image](https://github.com/hackmdio/hackmd-io-issues/assets/2173206/e3e95814-edd8-4199-a299-868ef8e0f091)
