### ISSUE TITLE
Question: How can I delete my account?

### ISSUE THREAD

**Issue by nunq** [hackmdio/hackmd-io-issues#181]
Till now I haven't found a 'delete my account' button on hackmd.io.
The procedure described in [hackmdio/codimd issue 1008](https://github.com/hackmdio/codimd/issues/1008#issuecomment-428962525) doesn't seem to work with the new overview interface.
Thanks.

**Comment by jackycute** [comment]
Hi @hyphenc,
If you like to delete account on hackmd.io, please send request to support@hackmd.io

Thank you!
