### ISSUE TITLE
overlapped views in UML

### ISSUE THREAD

**Issue by typebrook** [hackmdio/hackmd-io-issues#182]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io

### What's the problem
In the [tutorial](https://hackmd.io/c/tutorials/%2Fs%2FMathJax-and-UML#Sequence-Diagrams), the text just overlaps `Alice` and `Bob`.

### Current behaviour
It also happens on any other new UML diagram
![Screenshot from 2020-06-01 10-27-18](https://user-images.githubusercontent.com/19887090/83371380-ed7d9700-a3f4-11ea-8832-ab7809fda36e.png)

**Comment by jackycute** [comment]
Hi @typebrook,

Thanks for reporting. Could you let us know your OS and browser version?
I think it's working on the latest Chrome.

**Comment by typebrook** [comment]
@jackycute 
> Thanks for reporting. Could you let us know your OS and browser version?

Firefox Linux 77.0.1 (64-bit)

**Comment by jackycute** [comment]
Hi everyone,
Sorry for the late reply.
We have fixed a height styling issue on Firefox at 2022/8/2 (https://hackmd.io/s/release-notes#-EE-1430-2022-08-02-2000).
Please try again and feel free to let us know if you can reproduce this, thank you!

**Comment by typebrook** [comment]
LGTM, close this issue
![Screenshot_2023-01-10-15-24-16_1920x1080](https://user-images.githubusercontent.com/19887090/211487588-5574e8d5-7817-411f-be69-db3c7e51d59b.png)
