### ISSUE TITLE
Typo about 2.1.0-cjk tag images

### ISSUE THREAD

**Issue by atoato88** [hackmdio/hackmd-io-issues#183]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem

It maybe a typo on [hackmd.io documentation](https://hackmd.io/c/codimd-documentation).

Documentation says "change to `nabo.codimd.dev/hackmdio/hackmd:2.0.1-cjk` if you need" on https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-docker-deployment#Pick-docker-image-for-CJK-fonts , but `2.0.1-cjk` tag doesn't exist.

#### Current behaviour

1. When I tried to pull hackmd image w/ 2.0.1-cjk tag, following error occurs.
```
$ docker pull nabo.codimd.dev/hackmdio/hackmd:2.0.1-cjk
Error response from daemon: manifest for nabo.codimd.dev/hackmdio/hackmd:2.0.1-cjk not found: manifest unknown: manifest unknown
```

#### Expected behaviour

It should be updated `hackmd:2.0.1-cjk` to `/hackmd:2.1.0-cjk`, I think.

#### Additional context

When I tried w/ `2.1.0-cjk`tag, Instead of `2.0.1-cjk`, download finish on success.
```
$ docker pull nabo.codimd.dev/hackmdio/hackmd:2.1.0-cjk
2.1.0-cjk: Pulling from hackmdio/hackmd
Digest: sha256:a999c24eb23d9b17a60c026e074ffdb160e95495ec24cd6acaadb4b2c9e13faf
Status: Image is up to date for nabo.codimd.dev/hackmdio/hackmd:2.1.0-cjk
nabo.codimd.dev/hackmdio/hackmd:2.1.0-cjk
```

**Comment by jackycute** [comment]
Hi @atoato88,

Thanks for letting us know, we've fixed the typo!
