### ISSUE TITLE
使用手機瀏覽網頁網頁無法正常出現

### ISSUE THREAD

**Issue by pepefrog1234** [hackmdio/hackmd-io-issues#184]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### Read our Official tutorial

It's on https://hackmd.io/c/tutorials/

或是中文版 https://hackmd.io/c/tutorials-tw/

#### Current behaviour

> Screenshot (optional)

Provide steps to reproduce:

If possible, create a note with reproducible content and share the link with us.

e.g. note link: https://hackmd.io/features

#### Expected behaviour

(description of expected behaviour)

#### Environment

I use HackMD on:

- Device: [e.g. iPhone se
- OS: [e.g. iOS 10.1]
- Browser: safari,chrome
- Version: 

#### Additional context

我使用ios的手機連入公開的葉面可是畫面完全沒東西

**Comment by jackycute** [comment]
您好，可能要請您稍等，手機上載入會比較慢一點

如果還是無法顯示，請告訴我們您的 iOS 版本與瀏覽器版本，謝謝～
