### ISSUE TITLE
版本記錄似乎缺少查看編輯者的功能？

### ISSUE THREAD

**Issue by ceku012** [hackmdio/hackmd-io-issues#185]
如題，當多人共同編輯一則 HackMD 筆記時，在查閱版本時，是否有方法檢視各版本分別是由何人編輯？

若尚無此功能，希望能加上，因為當出現問題編輯時，需要知道是何人所為，以利進一步溝通或權限管理。

**Comment by jackycute** [comment]
您好，您可以從版本中，將游標移至在變更文字的底線上，可以看出作者為何

<img width="820" alt="螢幕快照 2020-07-02 下午2 38 27" src="https://user-images.githubusercontent.com/2639151/86324818-b6a7d480-bc71-11ea-92e4-9d2ffd5d3b9b.png">
