### ISSUE TITLE
Bugs in the latest update

### ISSUE THREAD

**Issue by Destroyer** [hackmdio/hackmd-io-issues#186]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem
Links containing `_` are broken
Content after `- >` won't appear 
see https://hackmd.io/HRU86XcnQsK94DWu5U8mFw

#### Environment

I use HackMD on:

**Desktop**
- Browser: Firefox 77

**Comment by jackycute** [comment]
Thanks for reporting to us @Destroyer.
We will fix this in next few days.

**Comment by jackycute** [comment]
This issue has been fixed, thanks @Destroyer !
