### ISSUE TITLE
Downloaded HTML has no document menu

### ISSUE THREAD

**Issue by banderlog** [hackmdio/hackmd-io-issues#187]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem

Downloaded HTML has no menu

#### Current behaviour
HackMD:
![image](https://user-images.githubusercontent.com/2557965/84521391-9b365300-acdd-11ea-8330-5a892812556c.png)

Downloaded HTML:
![image](https://user-images.githubusercontent.com/2557965/84521442-b012e680-acdd-11ea-8f27-5062e12c3fa1.png)

Provide steps to reproduce:
1. Menu
2. Download HTML
3. Open HTML

If possible, create a note with reproducible content and share the link with us.

e.g. note link: https://hackmd.io/wbwSvxp_T5yEO9wLqzq01g

#### Expected behaviour

Maintain document menu

#### Environment

I use HackMD on:

**Desktop**
- OS: Ubuntu 20.04 LTS
- Browser: Firefox
- Browser Version: 77.0.1 (64-bit)

**Comment by jackycute** [comment]
Hi @banderlog,

This is expected behavior, we want to make the downloaded HTML clean as can be viewed everywhere.
What's the feature you're looking for in the downloaded HTML?

**Comment by banderlog** [comment]
Actually, I need a single file document with navigation which could be viewed everywhere. It sounds like PDF, but, alas, hackmd does not have this feature yet (except slide decks).

Using this https://addons.mozilla.org/en-US/firefox/addon/single-file/ and `display: none !important` for few elements I was able to get what I want

**Comment by jackycute** [comment]
OK, thanks for your sharing @banderlog
