### ISSUE TITLE
Rust codeblocks don't have numbers.

### ISSUE THREAD

**Issue by nothingismagick** [hackmdio/hackmd-io-issues#188]
**Is your feature request related to a problem? Please describe.**
When I mark triple backtick as rust, I don't see line numbers in the rendered markdown. However, line numbers do show up if I mark it as JS.

**Describe the solution you'd like**
If I am writing code, i want line numbers.

**Describe alternatives you've considered**
Not marking code means I don't have coloring. :(

**Additional context**
![image](https://user-images.githubusercontent.com/35242872/85042801-eba12b00-b18b-11ea-8986-cb8a5a097c7b.png)

**Comment by jackycute** [comment]
Hi @nothingismagick,

Please put `=` after "rust" and you will see the line number, like:
<pre>
```rust=
```
</pre>

**Comment by jackycute** [comment]
Feel free to reopen if you have further question!
