### ISSUE TITLE
No spell checking menu in Firefox

### ISSUE THREAD

**Issue by panigrc** [hackmdio/hackmd-io-issues#19]
Firefox: 60.0.2 (64bit)
System: Xubuntu 14.04

With spell checker enabled in Hackmd when right clicking on a wrong word, Firefox doesn't display the spell checking menu (Choose language and word suggestions).

![hackmd_no_firefox_spellcheck](https://user-images.githubusercontent.com/645895/41505343-62961656-7207-11e8-8f0d-6819edbafd5d.png)

**Comment by jackycute** [comment]
Hi @panigrc, thanks for reaching us.

Sorry about we couldn't find a good solution for to add a spellcheck menu in any browser.
The editor actually is not native, it faked everything including the cursor, hence it's hard to trigger the context menu in many ways.

Feel free to keep this open until we find an answer!

**Comment by ssbarnea** [comment]
Why was this closed? The lack of context menu seams like a huge usability problem.
