### ISSUE TITLE
Slides presentation engine seems to be broken

### ISSUE THREAD

**Issue by Mons** [hackmdio/hackmd-io-issues#190]
### Is this a hackmd.io issue?

- [v] Yes, the bug happens on https://hackmd.io

Currently in slide mode instead of presentation showed only black screen

### Steps to reproduce:

Either use existing presentation (ex: https://hackmd.io/@Mons/Hk7qhFuOS) or create new from template and switch to slides mode

#### Environment

I use HackMD on:

**Desktop**
- OS: MacOS 10.14.6
- Browser: Chrome
- Browser Version: Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by jackycute** [comment]
Hi @Mons,

Thanks for reporting, we've reverted to the version that slide mode was working, please refresh page and try.

**Comment by Mons** [comment]
Thanks for fast action!
