### ISSUE TITLE
行內程式碼區塊不正常顯示

### ISSUE THREAD

**Issue by CA-Lee** [hackmdio/hackmd-io-issues#191]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### Read our Official tutorial

It's on https://hackmd.io/c/tutorials/

或是中文版 https://hackmd.io/c/tutorials-tw/

### What's the problem

行內程式碼（`\`\``）內的文字會套用外部的粗體及斜體效果。

#### Current behaviour

> Screenshot (optional)

Provide steps to reproduce:

If possible, create a note with reproducible content and share the link with us.

note link: https://hackmd.io/kFUJC5fhQC6xcucug586rQ

#### Expected behaviour

(description of expected behaviour)
note link: https://hackmd.io/kFUJC5fhQC6xcucug586rQ

#### Environment

I use HackMD on:

**Desktop**
- OS: Ubuntu 20.04 LTS
- Browser: Mozilla Firefox
- Browser Version:  77.0.1

**Comment by jackycute** [comment]
Hi @CA-Lee,

這是 CommonMark 標準的一部分喔，可以在此網址測試看看
https://spec.commonmark.org/dingus/
