### ISSUE TITLE
Footnote duplication

### ISSUE THREAD

**Issue by chrisjrob** [hackmdio/hackmd-io-issues#193]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io

#### Current behaviour

A simple document whose source looks like this:

```
# Footnote testing

This is a an important sentence ABC[^first], and must not be repeated.

[^first]: Sigh, how very tedious.
```

Results in duplicated footnotes, that looks like this:

> Footnote testing
> 
> This is a an important sentence ABC[2], and must not be repeated.
> 
>     Sigh, how very tedious. ↩︎
> 
>     Sigh, how very tedious. ↩︎

If possible, create a note with reproducible content and share the link with us.

https://hackmd.io/@chrisjrob/SkHvAW908

#### Environment

I use HackMD on:

**Desktop**

Replicated on Chrome Version 83.0.4103.116 (Official Build) (64-bit) and Firefox 77.0.1 (64-bit) - on Windows 10 Pro.

**Comment by jackycute** [comment]
Hi @chrisjrob,

Thanks for reporting, this issue has been fixed now.
