### ISSUE TITLE
MathJax not rendered correctly

### ISSUE THREAD

**Issue by 0xff07** [hackmdio/hackmd-io-issues#194]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### Read our Official tutorial

It's on https://hackmd.io/c/tutorials/

或是中文版 https://hackmd.io/c/tutorials-tw/

### What's the problem

Math expression not rendered in preview panel.

#### Current behaviour

Occasionally MathJax expressions may disappear, shrink, or duplicate.

Provide steps to reproduce:

1. Goto https://hackmd.io/@0xff07/B1PJaC2R8

2. Click "Edit"

<img width="1680" alt="截圖 2020-07-04 上午12 33 03" src="https://user-images.githubusercontent.com/17983661/86486581-37f48980-bd8e-11ea-9efd-239caaa2ec3d.png">

3. Insert two consecutive full-width dollar signs (but don't send out from buffer of input method), and then hit delete button twice to delete dollar signs in buffer. Repeat a few times to see it happen.

<img width="1680" alt="截圖 2020-07-04 上午12 41 40" src="https://user-images.githubusercontent.com/17983661/86487084-ba317d80-bd8f-11ea-884e-eb6eb90c62e7.png">

#### Expected behaviour

There should be math expression rendered in preview panel.

#### Environment

I use HackMD on:

**Desktop**
- OS: macOS Catalina 10.15.5
- Browser: Safari
- Browser Version: 13.1.1 (15609.2.9.1.2)

#### Additional context

Sometimes math expressions in preview panel just shrink, but they are rendered correctly:

<img width="1680" alt="截圖 2020-07-04 上午12 33 08" src="https://user-images.githubusercontent.com/17983661/86487238-2ca25d80-bd90-11ea-836e-02299524c937.png">

In some rare cases it duplicates. For example in the following picture, math expressions appear twice in preview panel than it supposed to be:

<img width="1680" alt="截圖 2020-07-04 上午12 25 34" src="https://user-images.githubusercontent.com/17983661/86487119-de8d5a00-bd8f-11ea-8c36-6d94f57c08d2.png">

Unfortunately I couldn't find a consistent way to reproduce the error, so I put them in additional context.

**Comment by jackycute** [comment]
We've deployed a new version which contains related fix, could you test if this issue still exists? @0xff07

**Comment by 0xff07** [comment]
It doesn't shrink, nor does it duplicates on macOS Catalina 10.15.6 with Safari 13.1.2（15609.3.5.1.3）; however sometimes  indentation in ordered list doesn't seem correct

**Comment by 0xff07** [comment]
It doesn't disappear, nor does it duplicates on macOS Catalina 10.15.6 with Safari 13.1.2 (15609.3.5.1.3), at least these issues never show up since deployment you mentoined.

Occasionally I find that indentation inside ordered list doesn't seem correct upon edition in this version, which never happen in the previous one:

<img width="1440" alt="截圖 2020-07-29 下午3 03 24" src="https://user-images.githubusercontent.com/17983661/88768016-07e1b000-d1ad-11ea-8f09-536e012ba50f.png">

Usually it recovers after refreshing the page manually.

**Comment by jackycute** [comment]
@0xff07 Thanks for reporting, but I think that is something else than the MathJax rendering.
Feel free to open another issue for the indentation problem, thanks!
