### ISSUE TITLE
Ctrl-B on Emacs binding is not working

### ISSUE THREAD

**Issue by niwatly** [hackmdio/hackmd-io-issues#197]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### Read our Official tutorial

It's on https://hackmd.io/c/tutorials/

或是中文版 https://hackmd.io/c/tutorials-tw/

### What's the problem

on Emacs key binding, I want to go backward one character without deleting when input a Ctrl-B command, but I can't do now.

I can do this before. I think the following enhancement affects on this bug.

```
EE 1.18.0  2020-07-23 16:40
Enhancements
Add shortcut keys for markdown editing

https://hackmd.io/s/release-notes
```

#### Current behaviour

toggle bold decoration of markdown when input a Ctrl-B

![hackmd](https://user-images.githubusercontent.com/18342998/89376956-ceb8bb00-d72b-11ea-9fa2-3c4b7c9805f2.gif)

Provide steps to reproduce:

1. input Ctrl-B

#### Expected behaviour

go backward one character without deleting when input a Ctrl-B

(description of expected behaviour)

#### Environment

I use HackMD on:

**Desktop**
- OS: [macOS Catalina 10.15.6]
- Browser: [chrome]
- Browser Version: [84.0.4147.105（Official Build） （64 bit）]

**Comment by jackycute** [comment]
We've deployed a fix for this, please refresh note page.
