### ISSUE TITLE
無法變更分享權限

### ISSUE THREAD

**Issue by AndrewTeraSuns** [hackmdio/hackmd-io-issues#203]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io

#### Current behaviour
更改權限的按鈕異常。
<img width="387" alt="螢幕快照 2020-08-24 下午2 46 06" src="https://user-images.githubusercontent.com/63439849/91012548-dc6dac00-e618-11ea-9886-47a0119afa04.png">

#### Environment

I use HackMD on:

**Desktop**
- OS: macOS
- Browser: chrome
- Browser Version: 84.0.4147.125 (正式版本) (64 位元)

**Comment by jackycute** [comment]
@Andrew-mie7 您好，感謝您回報問題
圖片中變更可閱讀權限的按鈕不應該出現，是 bug 沒錯
不過分享選單如此顯示的話，表示您不是筆記的擁有者，因此無法調整筆記權限

謝謝

**Comment by jackycute** [comment]
Thanks for reporting @Andrew-mie7 
We've deployed a fix for this.
