### ISSUE TITLE
Paste doesn't work on iPhone

### ISSUE THREAD

**Issue by AndreaPi** [hackmdio/hackmd-io-issues#204]
iOS version: 13.6.1
Browsers: Safari, Chrome

When copying some text to the clipboard in Safari or Chrome, it's not possible to paste it in a open document. This makes editing documents on a mobile phone very difficult.

**Comment by jackycute** [comment]
Hi @AndreaPi, thanks for reporting to us.
This is a known issue #97, there is no easy for us to fix it now.

**Comment by AndreaPi** [comment]
Thanks @jackycute, then I'll comment there.

**Comment by jackycute** [comment]
Duplicate #97
