### ISSUE TITLE
嵌入筆記在簡報模式下的Bug

### ISSUE THREAD

**Issue by kent1026** [hackmdio/hackmd-io-issues#205]
嵌入筆記在簡報模式下會出Bug
被嵌入的筆記簡報換頁會失效
全部擠在一頁

**Comment by jackycute** [comment]
謝謝您的回報，我們收到了，會盡快修正

**Comment by jackycute** [comment]
Sorry for the late reply.
This issue has been fixed at 2021/3/19.
