### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by yanjost** [hackmdio/hackmd-io-issues#206]
#### Current behaviour

Error in HackMD documentation

https://hackmd.io/MathJax-and-UML?both

The link to MermaidJS http://knsv.github.io/mermaid is 404.

The link I would suggest to use is https://mermaid-js.github.io/mermaid/#/n00b-overview

**Comment by jackycute** [comment]
Thanks for reporting @yanjost.
The link has been fixed!
