### ISSUE TITLE
Hackmd bad color contrast between text and background

### ISSUE THREAD

**Issue by bhavaniravi** [hackmdio/hackmd-io-issues#208]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem

Hackmd bad color contrast between text and background

#### Current behaviour

> Screenshot (optional)

![image](https://user-images.githubusercontent.com/10116000/92737885-1e2c7f80-f399-11ea-8d57-dbc3895f4c99.png)

Provide steps to reproduce:

1. Use hackmd on firefox - 80.0.1

#### Environment

I use HackMD on:

**Desktop**
- OS: macOS
- Browser: firefox
- Browser Version: 80.0.1

**Comment by YuerLee** [comment]
Same on Chrome:

![image](https://user-images.githubusercontent.com/2075566/144457524-1dc17f44-282a-4744-b96a-f6bd04d4e518.png)

**Environment**

I use HackMD on:

**Desktop**
- OS: macOS 11.6.1
- Browser: Chrome
- Browser Version: v96.0.4664.55, v97.0.4692.8, v98.0.4736.0

**Comment by jackycute** [comment]
Hi @passerbyid @bhavaniravi,

This issue was caused by Source Code Pro font, see more here: https://github.com/adobe-fonts/source-code-pro/issues/217
Please remove the installed Source Code Pro font in your computer and it should look fine again.
