### ISSUE TITLE
Typing lag when document gets long

### ISSUE THREAD

**Issue by alexander-soare** [hackmdio/hackmd-io-issues#212]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem

I get typing lag when the document gets very lengthy.

#### Current behaviour

Reproduce with about 400 lines including about 20 images and 20 $formulas$.

#### Environment

I use HackMD on:

Brave Browser on macOS Catalina

**Comment by andreamatt** [comment]
Same here. I think it's either the images or formulas. Does it happen with text only too?

**Comment by jackycute** [comment]
Hi guys, thanks for reporting.

Please use edit mode (click the pen icon) for editing note with lots of images or formulas or UMLs since the view rendering will take out most of the performance.

<img width="307" alt="螢幕快照 2021-01-21 下午6 29 12" src="https://user-images.githubusercontent.com/2639151/105338488-94c66d00-5c16-11eb-89b9-18e879093ffc.png">

**Comment by andreamatt** [comment]
Isn't the rendering a separate async task? I expected the text writing to be responsive even if the rendering takes ages

**Comment by jackycute** [comment]
We've tried our best to not render the result view under edit mode. But even the editor itself needs rendering. Maybe we can leverage another thread with web worker, otherwise the rendering is very bundled at the moment.

**Comment by andreamatt** [comment]
Alright, thanks anyway

**Comment by jackycute** [comment]
Please open another issue if you have specific case of performance issue, thanks guys!

**Comment by alexander-soare** [comment]
@jackycute just thought I'd chime in. I ended up moving to another solution because of this.

**Comment by jackycute** [comment]
> @jackycute just thought I'd chime in. I ended up moving to another solution because of this.

@alexander-soare Thanks for letting us know. What's your current solution?
It's more than happy if you can try again, we've made lots of fixes recently.

**Comment by alexander-soare** [comment]
@jackycute It's VS Code, my preferred IDE. I went through Evernote, HackMD, BoostNote and maybe one other one, and finally realised that VS Code ticks all the most important boxes. The notes are just for me so I don't need sharing/collaboration facilities - so perhaps I'm not the most important type of customer to retain.

PS: Github as my "cloud storage"
