### ISSUE TITLE
Mermaid autonumber support for sequence diagrams not working

### ISSUE THREAD

**Issue by nodestory** [hackmdio/hackmd-io-issues#215]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem

The upstream dependency `mermaid.js` can not correctly parse the keyword `autonumber`.

#### Current behaviour

Provide steps to reproduce:

1. Paste the example from [mermaid documentation](https://mermaid-js.github.io/mermaid/diagrams-and-syntax-and-examples/sequenceDiagram.html#sequencenumbers)

```mermaid
sequenceDiagram
    autonumber
    Alice->>John: Hello John, how are you?
    loop Healthcheck
        John->>John: Fight against hypochondria
    end
    Note right of John: Rational thoughts!
    John-->>Alice: Great!
    John->>Bob: How about you?
    Bob-->>John: Jolly good!
```

#### Expected behaviour

HackMD can render the same image like [Mermaid Live Editor](mermaid-js.github.io/mermaid-live-editor/)

#### Environment

I use HackMD on:

**Desktop**
- OS: macOS
- Browser: opera
- Browser Version: 71.0.3770.284

#### Additional context

It seems that the issue was [already fixed](https://github.com/mermaid-js/mermaid/issues/1257). Maybe the dependency was not upgraded.

**Comment by jackycute** [comment]
Hi @nodestory, thanks for reporting.
mermaid has been upgrade and supported `autonumber` now.
