### ISSUE TITLE
Starting a wrestling club /Community center where I could hold football games wrestling tournaments and a big facility And a big job opportunity for many people out of work

### ISSUE THREAD

**Issue by acardoz** [hackmdio/hackmd-io-issues#221]
Starting a wrestling club /Community center where I could hold football games wrestling tournaments and a big facility￼ And a big job opportunity for many people out of work 

__Originally posted by @acardoz in https://github.com/hackmdio/hackmd-io-issues/issues/207#issuecomment-747228593__

**Comment by jackycute** [comment]
Are you spamming the issues?
