### ISSUE TITLE
Code block highlighting not working properly in view mode

### ISSUE THREAD

**Issue by davidhcefx** [hackmdio/hackmd-io-issues#226]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### Read our Official tutorial

It's on https://hackmd.io/c/tutorials/

或是中文版 https://hackmd.io/c/tutorials-tw/

### What's the problem

[Code block highlighting](https://hackmd.io/features?both#Code-Block) not working properly in **view mode**:

![screenshot](https://user-images.githubusercontent.com/23246033/104216330-e29fe000-5474-11eb-8ac1-8fb4ee8ff175.png)

From the above screenshot, note that:
- The highlighting was always correct in **edit mode**.
- In **view mode**, there was no color at all.
- Turning on _line-numbering_ or _word-wrapping_ didn't solve the problem.

However, what's strange is that **ADDING THE SECOND = OR ! DO SOLVE THE PROBLEM**! I have no idea how that works.

#### Current behaviour

> [Screenshot as above](https://user-images.githubusercontent.com/23246033/104216330-e29fe000-5474-11eb-8ac1-8fb4ee8ff175.png)

Provide steps to reproduce:

1. Try out the above code ([https://hackmd.io/QFopG7pgTg6EInWFNSLMgg](https://hackmd.io/QFopG7pgTg6EInWFNSLMgg?both)).

#### Expected behaviour

Code been highlighted properly instead of no color at all (black on white).

#### Environment

I use HackMD on:

**Desktop**
- OS: Windows 10
- Browser: Chrome
- Browser Version: 87.0.4280.88

**Comment by jackycute** [comment]
Hi, the proper syntax highlighting works for shell will need to append `$` or `>` before every command line, otherwise it's just output text.

```
$ echo $EDITOR
vim
$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
$ git push
Everything up-to-date
$ echo 'All
> done!'
All
done!
> find $PWD -maxdepth "4" -type 'f' -executable -perm -4000
$ find $PWD -maxdepth "4" -type 'f' -executable -perm -4000
```

<img width="1680" alt="螢幕快照 2021-01-21 下午1 38 03" src="https://user-images.githubusercontent.com/2639151/105284675-e9092700-5bed-11eb-8e80-78556fac2bb4.png">
