### ISSUE TITLE
書本模式顯示問題

### ISSUE THREAD

**Issue by Ziv81** [hackmdio/hackmd-io-issues#227]
### Is this a hackmd.io issue?
Yes

### Read our Official tutorial

Yes, https://hackmd.io/c/tutorials-tw/%2Fs%2Fhow-to-create-book-tw

### What's the problem

書本模式進入後，僅顯示左邊列表右邊一直轉圈圈。
嘗試過
1. Edge 87.0.664.75 (官方組建) (64 位元)
2. Chrome 87.0.4280.141 (正式版本) (64 位元)

我的連結 : https://hackmd.io/@Ziv/BJSo400AP

Chrom and Edge
https://imgur.com/a/gUl3M9h

Provide steps to reproduce:

1. 編輯內容
2. 點選右上角的分享
3. 選擇書本模式
4. 點選預覽

#### Environment

I use HackMD on:

**Desktop**
- OS: Windows
- Browser: Chrome, Edge
- Browser Version: 
   Chrome : 87.0.4280.141 (正式版本) (64 位元)
   Edge 87.0.664.75 (官方組建) (64 位元)

**Comment by Yukaii** [comment]
@Ziv81 HackMD 的書本模式會讀取文件中「列表中的連結」作為書本模式的頁面，由於您的文件沒有寫入任何連結，故書本模式沒有任何頁面。您可以加入以下語法：

```md
- [Link 1](/s/features)
- [Link 2](/s/release-notes)
```

再重新整理頁面

**Comment by Ziv81** [comment]
原來如此，我了解了。謝謝。
