### ISSUE TITLE
typo -"only people [who] have the link and read permission can view this note"

### ISSUE THREAD

**Issue by da5nsy** [hackmdio/hackmd-io-issues#228]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem

Typo. When hovering over the lock on a user's page it reads "only people [who] have the link and read permission can view this note".

#### Environment

I use HackMD on:

**Desktop**
- OS: Windows 10
- Browser: Firefox

**Comment by jackycute** [comment]
Thanks @da5nsy, we will fix this soon.

**Comment by jackycute** [comment]
This typo has been fixed and deployed.
Thanks @da5nsy
