### ISSUE TITLE
Images not uploading

### ISSUE THREAD

**Issue by rupeshtiwari** [hackmdio/hackmd-io-issues#229]
I am using hackmd.io website and I am writing one note. 
My images are always showing  `![Uploading file..._wqat6bi8n]()` from last 15 minutes and they are never uploading. Today only this is happening. 
I see the errors below while in F12 console.log
![image](https://user-images.githubusercontent.com/330383/105248538-8f98ed80-5b44-11eb-9013-73e8b95d7e55.png)
```error
Access to XMLHttpRequest at 'https://api.imgur.com/3/image' from origin 'https://hackmd.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
I tried incognito chrome , I tried new browser everywhere same issue.

Please advise how to fix it.

**Comment by jackycute** [comment]
We can't reproduce this issue, could you try again @rupeshtiwari?

**Comment by rupeshtiwari** [comment]
Hi today it is working fine. Not sure what was happening on that day none
of the image was going through.

Thanks !  Please close the ticket

**Comment by ekg** [comment]
I'm also unable to load or view images in the hackmd editor. Very strange!
