### ISSUE TITLE
手機模式的編輯欄會隱藏

### ISSUE THREAD

**Issue by timcsy** [hackmdio/hackmd-io-issues#23]
在手機上使用hackmd.io切換到編輯模式時，
如果文章太常滑動會導致編輯欄被白色的工具列遮住，
必須要滑到最上面才能使用編輯欄功能。
如果可以稍微調一下就更棒了！

**Comment by jackycute** [comment]
現在手機版上的編輯模式的工具列也會顯示了喔！
謝謝回報 @timcsy
