### ISSUE TITLE
Update mermaid.js version to 8.9.x for ERD column support

### ISSUE THREAD

**Issue by ricecooker** [hackmdio/hackmd-io-issues#231]
**Is your feature request related to a problem? Please describe.**
Need updated version of mermaid.js. The current version doesn't support columns names and types for ERDs. The mermaid.js refer dies on the column definition. Last checked, the latest is 8.9.0.

**Describe the solution you'd like**
Update to use the latest mermaid.js library.

**Describe alternatives you've considered**
Have to use the mermaid.js live editor for now hoping that hackmd will be updated.

**Additional context**
See documentation here: https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram?id=syntax

```mermaid
erDiagram
    CAR ||--o{ NAMED-DRIVER : allows
    CAR {
        string registrationNumber
        string make
        string model
    }
    PERSON ||--o{ NAMED-DRIVER : is
    PERSON {
        string firstName
        string lastName
        int age
    }
```

**Comment by jackycute** [comment]
We have upgraded mermaid to v9 now.
