### ISSUE TITLE
[Feature Request] Subscribe to user

### ISSUE THREAD

**Issue by shitchell** [hackmdio/hackmd-io-issues#232]
It would be awesome to be able to subscribe to a user and receive updates / emails for certain events, namely publishing a new note.

I'd like to start using hackmd as a blog, so it would be preferable if people didn't have to sign up for an account and could simply verify their email. Either way, this would be a great addition for blogs, teachers, and friends who want to follow each other's published notes!

**Comment by jackycute** [comment]
You can now follow a user and get notified when the user publish new note!
https://hackmd.io/s/release-notes#-EE-1581-2023-09-04-1625
