### ISSUE TITLE
Overview is missing many of my notes

### ISSUE THREAD

**Issue by fingolfin** [hackmdio/hackmd-io-issues#236]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### Read our Official tutorial

It's on https://hackmd.io/c/tutorials/

或是中文版 https://hackmd.io/c/tutorials-tw/

### What's the problem

On https://hackmd.io/?nav=overview I only see a subset of my notes (ones that I created and own); I am aware that it has multiple subpages, two in my case. Luckily a colleague still had a link; after visiting it, the missing note appeared in the overview. But now another note which I had opened earlier is missing.

How can I see all my notes???

One of the missing notes is titled "# The Idealised GAP Release Process" (I do have a link for it, but it's not on the overview list right now; it was earlier today)

#### Current behaviour

> Screenshot (optional)

Page 1:
<img width="1672" alt="Screenshot 2021-02-16 at 10 58 02" src="https://user-images.githubusercontent.com/241512/108047229-d8f63300-7045-11eb-8eba-06c3064bd9b9.png">

Page 2:
<img width="1672" alt="Screenshot 2021-02-16 at 10 58 38" src="https://user-images.githubusercontent.com/241512/108047301-ed3a3000-7045-11eb-800e-7dd31b826244.png">

Provide steps to reproduce:

1. Go to https://hackmd.io/?nav=overview
2. Click through the various pages
3. Notice that notes are missing

#### Expected behaviour

All my notes should be shown

#### Environment

I use HackMD on: hackmd.io

**Comment by jackycute** [comment]
Hi @fingolfin,
Usually this happens when you signed-in to another account.
Could you send us email by support@hackmd.io and let us know your account email?
We are happy to help!

**Comment by fingolfin** [comment]
Mail sent, thank you

**Comment by jackycute** [comment]
We received it, let's talk there.
