### ISSUE TITLE
Auto Scrolling in the Coding Page

### ISSUE THREAD

**Issue by Aleo0129** [hackmdio/hackmd-io-issues#237]
From time to time, whenever I type anything, the page would scroll up to the top after few seconds automatically. I am not sure it's whether the problem in the hackMD or the problem of my own PC.

**Comment by jackycute** [comment]
Hi @Aleo0129, do you still have this issue? Could you provide an example that can reproduce this?
Thank you!

**Comment by jackycute** [comment]
Feel free to re-open this if you can reproduce.
