### ISSUE TITLE
[Feature Request]: Add RTL Support to Markdown Preview

### ISSUE THREAD

**Issue by theMasix** [hackmdio/hackmd-io-issues#241]
**Is your feature request related to a problem? Please describe.**
As some markdown previewer and also VSCode supports `rtl` text, It would great if HackMD support it too!
As I know, HackMD doesn't support `rtl` text now.

[More About RTL](https://en.wikipedia.org/wiki/Right-to-left)

**Describe the solution you'd like**
I think updating the MD parser could solve this issue.

**Additional context**
Here is a screenshot from VSCode:
![image](https://user-images.githubusercontent.com/22872117/109352514-34b78c00-7890-11eb-87c8-f5784d8951b7.png)

And same text screenshot from HackMD
![image](https://user-images.githubusercontent.com/22872117/109352601-57e23b80-7890-11eb-812e-f9a7d2dfd2f1.png)

the `div` which has `dir="rtl"` attribute should starts from right to left.

**Comment by jackycute** [comment]
Hi @theMasix, thanks for reaching us.
We do support dir attribute, you can specify it in yaml metadata, learn more here: https://hackmd.io/s/yaml-metadata#dir

**Comment by theMasix** [comment]
Hello @jackycute, thanks for response.
As I know, the yaml metadata, specifies the whole text preferences, if I set `dir` to `rtl`, whole page will be rendered as `rtl`. but using `div` would change only a part of the page not the whole page.

and we often want to have both `rtl` and `ltr` on one page.

So I think using `div` would be more useful for everyone.
