### ISSUE TITLE
"Save as version" is disabled

### ISSUE THREAD

**Issue by peterkaminski** [hackmdio/hackmd-io-issues#246]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io

### Read our Official tutorial

I have read [How to save versions \- HackMD](https://hackmd.io/c/tutorials/%2Fs%2Fhow-to-save), but the answer to my problem is not there.

### What's the problem

The "Save as version" button is disabled, and I cannot create a named version from the current note content.

#### Current behaviour

Screenshot:

<img width="1013" alt="Screenshot of top of 'Versions and GitHub Sync' window" src="https://user-images.githubusercontent.com/169442/111917956-df5e3d00-8a3f-11eb-9a07-9944cce9bc8c.png">

Steps to reproduce:

1. Create a HackMD note.
2. Edit for a while.  (I shared and edited with another person. Note permissions were Read=Everyone, Write=Signed-in users.)
3. Click the three-dot menu in the upper right toolbar.
4. Click "Versions and GitHub Sync"
5. Make sure "Current note content" is selected at the left.
6. Notice that the "Save as version" button is a lighter color, and does nothing when clicked.

This has happened with two different notes so far.

I've tried a few steps to fix:

- reloading the page
- closing the tab and loading the note again
- tried closing and reopening browser
- tried a different browser (including signing in fresh)

I do not currently have a note that replicates the problem that I can share.  If/when I do, I will make a comment on this issue.

#### Expected behaviour

From the "Versions and GitHub Sync" dialog, I can click the "Save as version" button which would create a named version.

#### Environment

I use HackMD on:

**Desktop**
- OS: macOS Big Sur 11.2.2 (Intel)
- Browser: Google Chrome Version 89.0.4389.90 (Official Build) (x86_64)
- Second Browser: Apple Safari Version 14.0.3 (16610.4.3.1.4)

#### Additional context

It seems that auto-saving may have stopped, as well.

The most recent auto-saved version is from 11:40 AM.  Another user and I have both made edits since then, and the time is now 12:30 PM.  The most recent edit was 15 minutes ago, at ~12:15 PM.

**Comment by peterkaminski** [comment]
For what it's worth, I feel like I'm just missing something, and this is a dumb FAQ rather than a bug -- but I can't find any documentation of it or how to move past it.

Anyway, it's just happened again on another private note, I can't "Save as version" and don't know how to unblock it.

**Comment by peterkaminski** [comment]
> Anyway, it's just happened again on another private note, I can't "Save as version" and don't know how to unblock it.

And a few minutes later, after editing/adding a line or two of text, I was able to "Save as version". 🤷

**Comment by jackycute** [comment]
Hi @peterkaminski,

Thanks for reaching us.
You can only save another version when the content is modified to the previous saved version.
If the "Save as version" button is disabled, that means the current note content is same as the previous saved version.

To name a version, click any saved version on the left side and you will see "Name this version" button on the right side, please learn more here:
https://hackmd.io/c/tutorials/%2Fs%2Fhow-to-save#Save-Versions

**Comment by peterkaminski** [comment]
@jackycute, thank you for the advice.

I believe I've seen instances where the content is different from the previously saved version, and the "Save as version" button is disabled, but now I will check more carefully.

Closing this issue until I have more observations...
