### ISSUE TITLE
No margin space using <div class="pull-left">

### ISSUE THREAD

**Issue by fildunsky** [hackmdio/hackmd-io-issues#25]
![bug_hackmd](https://user-images.githubusercontent.com/32987666/42136582-f99ac14a-7d66-11e8-919e-152b69ee217d.png)

Please add few 5-10 pixels space to the right from the image using pull-left class.

**Comment by jackycute** [comment]
Hi @fildunsky, thanks for reaching us.
You can add your custom CSS using `<style>` tag.
