### ISSUE TITLE
hackmd favicon low contrast on dark-mode browser

### ISSUE THREAD

**Issue by mikesamuel** [hackmdio/hackmd-io-issues#250]
### Is this a hackmd.io issue?

- [X] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem

The black favicon without any light border blends into the browser's tab bar when the browser is in dark mode.

#### Current behaviour

![image](https://user-images.githubusercontent.com/368886/112700365-5d697c00-8e64-11eb-97d8-1491e485af12.png)

Note the github favicon mixes light and dark so is recognizable.  The two hackmd favicons are not.

#### Expected behaviour

A human with declining eyesight using a standard browser theme can scan the tab list and find a hackmd logo without falling back to looking for blanks.

#### Environment

**Desktop**
- OS: macOS
- Browser: chrome
- Browser Version: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36

**Comment by jackycute** [comment]
Hi @mikesamuel,
Sorry for the late reply.
We have updated for favicon to make it looks nice in dark mode.
<img width="194" alt="截圖 2023-01-10 下午2 57 47" src="https://user-images.githubusercontent.com/2639151/211482800-b69f01f6-11b9-4da9-b78d-6ccef89cf857.png">
