### ISSUE TITLE
[Feature Request] Allow Team Owners to change default node permissions

### ISSUE THREAD

**Issue by PaulRitter** [hackmdio/hackmd-io-issues#255]
Currently the default note permissions for public teams are:
Read: anyone
Write: Signed in users

This makes little sense for teams which want their notes as well as their teams to be publicly available, yet **not** have the public edit their notes. Putting this in the Team Settings would be grand, thanks.

**Comment by jackycute** [comment]
Hi @PaulRitter 
Thanks for reaching us.
The default note permission will be able to be changed for private team in the future.
In this case you will need to use private team instead of public team.

**Comment by PaulRitter** [comment]
> Hi @PaulRitter
> Thanks for reaching us.
> The default note permission will be able to be changed for private team in the future.
> In this case you will need to use private team instead of public team.

Hi, thanks for answering.
Will private teams then have the possibility to set the default note read permissions to public?

**Comment by faelin** [comment]
I would like to expand on this feature request. All users should be able to configure Default Note Permissions for Read, Write, and Comment, for notes that they create!

**Comment by jackycute** [comment]
Hi everyone,
Thanks for giving us feedback.
We have supported change default note permissions of workspace in Prime plan from 2021/7/20.
https://hackmd.io/s/release-notes#-EE-1280-2021-07-20-1700
