### ISSUE TITLE
[Feature] Allow External CSS Through <link> Tag

### ISSUE THREAD

**Issue by faelin** [hackmdio/hackmd-io-issues#258]
In several of my HackMD notes (which I have compiled into a Book), I use a shared set of CSS styles that I have appended to each note through a `<style>` block:
```
<head>
  <style>
       ...some css...
  </style>
</head>
```

Because I reuse the same styles between all of these notes, I would like to be able to use a `<link rel="stylesheet" href="...">` tag to load an external CSS document. Unfortunately, the HackMD parser automatically changes `<link>` tags to a plaintext link wrapped in `<span class="cm-m-xml cm-string cm-link">` tags.

I believe that HackMD would strongly benefit from a way to override CSS via a file that could be shared between several notes. This could be done through a special notation (example: `[!style](https://example.com/stylesheet.css)`), and/or through a system similar to HackMD Templates (example: "Insert Style from Template").

In addition, I frequently have to use the `!important` modifier on my CSS changes when I want to adjust the design of a table, `<h_>` tag, or other tag generated by the Markdown parser. Although HackMD's default stylings are beautiful and well designed, I would like to be able to override them via some special notation, instead of having to use the `!important` modifier.

**Comment by jackycute** [comment]
Hi @faelin,
You can achieve this by embed a note that have CSS styles to another note.
`<link>` tags will always be removed to prevent XSS.
Feel free to re-open if you have more feedback.
