### ISSUE TITLE
inline html with markdown code block (```) preview disappear while editing

### ISSUE THREAD

**Issue by chhuang215** [hackmdio/hackmd-io-issues#263]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### Read our Official tutorial

It's on https://hackmd.io/c/tutorials/

或是中文版 https://hackmd.io/c/tutorials-tw/

#### Current behaviour

> Screenshot (optional)
![Snipaste_2021-06-29_09-37-55](https://user-images.githubusercontent.com/706083/123724100-536d7400-d8be-11eb-94ca-b397db9f85c9.png)

![Snipaste_2021-06-29_09-38-39](https://user-images.githubusercontent.com/706083/123724109-5700fb00-d8be-11eb-9a60-97cbdbc24cbb.png)

Provide steps to reproduce:

1. Inline HTML with markdown code block within
2. Focus in editor; the code block not rendered in preview
3. Lose editor focus; the code block will render as usual

If possible, create a note with reproducible content and share the link with us.

e.g. note link: https://hackmd.io/features

#### Expected behaviour

code block should show in preview as usual

#### Environment

I use HackMD on:

**Desktop**
- OS: [eg. Win10]
- Browser: chrome
- Browser Version: 91.0.4472.114

#### Additional context

NONE

**Comment by jackycute** [comment]
Hi @chhuang215,

Thanks for reporting to us.
This was caused by a render optimization styling issue.
We will fix this soon.

**Comment by jackycute** [comment]
This issue has been fixed and deployed.
