### ISSUE TITLE
Cannot login via github on Firefox

### ISSUE THREAD

**Issue by coopchange** [hackmdio/hackmd-io-issues#266]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

#### Current behaviour

<img width="1388" alt="Screen Shot 2021-08-10 at 10 49 37 AM" src="https://user-images.githubusercontent.com/18379380/128784024-3a9f5bff-a678-4cf8-84d2-fcc706a8bf80.png">

Provide steps to reproduce:

1. Go to Firefox
2. Click on Login
4. See lack of Login by Github

### Versions 

Mac OS X 10.14.16

Firefox 90.0.1

**Comment by coopchange** [comment]
adding screenshot here and to OP - versions added to OP as well
<img width="1388" alt="Screen Shot 2021-08-10 at 10 49 37 AM" src="https://user-images.githubusercontent.com/18379380/128783955-319db623-1a7b-462a-94d9-c47fe3971dd2.png">

**Comment by jackycute** [comment]
Hi @coopchange,

Thanks for reaching us.
Please disable any ad blockers extension for `hackmd.io` and you can see the social sign-in buttons.
