### ISSUE TITLE
Markdown syntax check

### ISSUE THREAD

**Issue by Ziv81** [hackmdio/hackmd-io-issues#269]
Dear hackmd team,

When I edit with markdown syntax check which function at the editor bottom bar.
I got the MD024 check fail.
Following the message and refer [this](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md024---multiple-headings-with-the-same-content).

Is there a way to add the setting like siblings_only or allow_different_nesting to avoid this?

Ziv

**Comment by jackycute** [comment]
Hi @Ziv81,

You can disable MD024 rule by adding `<!-- markdownlint-disable MD024 -->` to your note.
Please read more at: https://github.com/DavidAnson/markdownlint#configuration

**Comment by jackycute** [comment]
BTW, adding `<!-- markdownlint-configure-file { "MD024": { "siblings_only": true } } -->` also helps.
