### ISSUE TITLE
My page occurs error when a wrong codeblock syntax is used

### ISSUE THREAD

**Issue by LeeLin2602** [hackmdio/hackmd-io-issues#271]
Hello everyone, I use syntax likes it:

    ```{.cpp= }
    #include<iostream>
    
    using namespace std;
    
    int main(){
	      cout << "Hello World!" << endl;
    }
    ```

and the page occurs error like it:

![image](https://user-images.githubusercontent.com/30391069/131821959-7f24c3bc-9e89-470b-aadc-0d6496e8e3c2.png)

It's connected, but I cannot modify the content. 

https://hackmd.io/tfPONyT6TlGX-sY4_p_Zuw

Thanks.

**Comment by jackycute** [comment]
Hi @LeeLin2602,

Thanks for reporting to us.
It appears you encountered a syntax parser error, please visit your note in edit mode here: https://hackmd.io/tfPONyT6TlGX-sY4_p_Zuw?edit and continue editing.
The critical part is the `{.cpp= }`, please change that to `{cpp=}`.

We will fix this soon, thanks!

**Comment by LeeLin2602** [comment]
@jackycute Thank you for replying 

I just use TeX to MD converter, and just paste the result on HackMD. I knew some syntax might not work well on hackMD and I was planned to fix it after pasting on it, then I found that the page occurs errors and I cannot modify the page anymore. I want to report this part. 

Thank you for detailedly answering and good luck!

**Comment by jackycute** [comment]
We have fixed and deployed this issue, thanks for reporting.
