### ISSUE TITLE
Fixed(Sticky) Table Headers

### ISSUE THREAD

**Issue by jimmy801** [hackmdio/hackmd-io-issues#272]
**Is your feature request related to a problem? Please describe.**
Sometimes I make huge tables, and I want to see all headers when I scroll down.

**Describe the solution you'd like**
I have noticed that someone said we can add the pure css position attribute "sticky", but it didn't work in the style setting of hackmd document. I found [https://adrianroselli.com/2020/01/fixed-table-headers.html](https://adrianroselli.com/2020/01/fixed-table-headers.html) is a good source to see how I would like it to behave.

**Additional context**
Here is the screenshot of the result from [the reference website](https://adrianroselli.com/2020/01/fixed-table-headers.html) I mentioned above.
![](https://imgur.com/5DWBWg4.gif)

**Comment by jackycute** [comment]
Hi @jimmy801,

Thanks for reaching us.
You can put CSS in your note through `<style>` tag, since the example you mentioned is pure CSS, it would be nice to give it a try.

**Comment by jimmy801** [comment]
@jackycute, thank you for the advice.

It works perfectly now.
