### ISSUE TITLE
PlantUML server is outdated

### ISSUE THREAD

**Issue by mlopezgva** [hackmdio/hackmd-io-issues#275]
**Is your feature request related to a problem? Please describe.**
PlantUML has two issues:

1. plantuml version is outdated, it's almost half a year "old:
  ![image](https://user-images.githubusercontent.com/996070/134537218-83ab647d-184f-427b-9f53-8f55b5e1a007.png)

2. The rendering is not good,maybe related to a faulty version of `dot`.

**Describe the solution you'd like**
Well, just updating the .jar version, and for the bug, using graphviz v2.38 instead of v2.40 should do.

**Describe alternatives you've considered**
An option to change the plantuml server for hackmd's to another one (for instnce, I have one server and also the local .jar...)

**Additional context**
This is part of a diagram with plantuml:

![image](https://user-images.githubusercontent.com/996070/134537908-a57304b9-f987-4654-8889-c08af464786c.png)

And this is the same part using the current official version:

![image](https://user-images.githubusercontent.com/996070/134538045-c0872526-35bd-4ff6-8873-8827db67cc0c.png)

**Comment by jackycute** [comment]
Hi @mlopezgva,

Thanks for heads up, we have updated to PlantUML version to 1.2021.12 and graphviz version 2.43

<img width="564" alt="截圖 2021-10-06 下午1 54 26" src="https://user-images.githubusercontent.com/2639151/136147977-7f5226fd-d674-4d6d-9b23-11a3c07abd09.png">
