### ISSUE TITLE
**Auto-update: False/True** Button

### ISSUE THREAD

**Issue by SPyofgame200** [hackmdio/hackmd-io-issues#278]
Stop rendering every single time I type one more character, such a waste of time for un-needed stuff while editting :V

**Comment by jackycute** [comment]
Hi @spyofgame,

For this scenario, you can switch to Edit Mode on the top left of editor so the view won't render.
<img width="382" alt="截圖 2021-10-07 上午11 00 22" src="https://user-images.githubusercontent.com/2639151/136313474-b7dfffba-0e8a-4670-8dc7-e19d835df467.png">
