### ISSUE TITLE
Cannot delete text using Icecat on Android

### ISSUE THREAD

**Issue by oliver** [hackmdio/hackmd-io-issues#28]
When editing a hackmd.io pad using IceCat 52.6.0 (Firefox clone) on Android 7, it is not possible to delete characters that are older than a few seconds. I only tried deleting with Backspace key on the virtual keyboard, since I didn't find any other way. Entering new text is no problem, though.

**Comment by jackycute** [comment]
Do you still experiencing this @oliver ?

**Comment by jackycute** [comment]
This might related to #97 
Please reopen if you still have this issue @oliver, thanks!
