### ISSUE TITLE
Multiple markdown pages on a single item - "New Collection"?

### ISSUE THREAD

**Issue by alshdavid** [hackmdio/hackmd-io-issues#283]
**Is your feature request related to a problem? Please describe.**

When using one account across many projects, trying to document a complex issue that requires multiple markdown files with an index is quite difficult. Notes will be displayed flatly across the home page. Tags help to an extent but there is always overlap with tag names unless you use a single tag only as a means to create "pseudo folders" - dividing sections of the homepage up for quick look up.

![image](https://user-images.githubusercontent.com/12656294/142783265-608e6d35-8737-4e54-ac8b-c66a9eef1656.png)

**Describe the solution you'd like**

I would like to have a multi-page document. Something like a note collection or a folder that contains multiple notes where there is an automatically selected note acting as an index.

It would be nice if tags were scoped to that document, making it easy to look up the specifics of a certain project.

Perhaps "new note collection", or "new folder"

![image](https://user-images.githubusercontent.com/12656294/142782903-16fba5b4-0b02-4e74-acd4-b2356cbf30df.png)

**Describe alternatives you've considered**

I have tried using nodes

I have tried making a new account per project - obviously that makes less sense when you look at the push towards SSO

**Additional context**

**Comment by plutonium-239** [comment]
Duplicate of #20, @jackycute is this happening?

**Comment by jackycute** [comment]
Maybe you can try book mode?
https://hackmd.io/c/tutorials/%2Fs%2Fhow-to-create-book
https://hackmd.io/c/book-example

**Comment by plutonium-239** [comment]
@jackycute I tried for a week with book mode, it feels pretty gimmicky
one way to improve book mode is to have the index note present towards the side at all times like a file explorer w/o having to put a file explorer in or even any directory structure 
_**[switching tabs to open different notes, that too in different tabs is pretty inconvenient]**_
I think it's a feasible solution [adding one more markdown view towards the left side is not really invasive], do you think you might look into that? I would be satisfied with that and don't need a whole folder structure.

**for proper folder structure :**
I think (https://stackedit.io) implements it pretty well, we can have workspaces and folders inside them
It might be hard but a lot of people are rooting for this, even on CodiMD's issue tracker (https://github.com/hackmdio/codimd/issues/1275 contains 4 more related issues and one way to solve this w/o having to f up any behavior) 

anyways, cheers!

**Comment by jackycute** [comment]
@Plutonium-239 Thanks for the feedback, we know the importance of folder, we will need to solve some other issues in our architect.

BTW, we just added Tags List, even it won't open note at the right side view but might easier to browse notes.
https://hackmd.io/c/tutorials/https%3A%2F%2Fhackmd.io%2F%40docs%2Fhow-to-use-tag-list-filter

**Comment by plutonium-239** [comment]
@jackycute it looks like it'll be some time before this is implemented
I plan to make a small extension/something (even better if i can do it using just CSS) to add a third column to the left side to use and for others to use in the meanwhile
Any useful hints from your side?

**Comment by alshdavid** [comment]
Closing this issue as I clean up my old issues, feel free to reopen this
