### ISSUE TITLE
Slide Mode is broken

### ISSUE THREAD

**Issue by afrozl** [hackmdio/hackmd-io-issues#285]
### Is this a hackmd.io issue?

- [X] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem
Slides no longer centered and scrollbar is visible
#### Current behaviour
Slides no longer centered and scrollbar is visible
> Screenshot (optional)
![Web capture_1-12-2021_93246_hackmd io](https://user-images.githubusercontent.com/6628282/144265614-86e35bcd-3cc6-4f81-a99f-6d44977cde4f.jpeg)

Provide steps to reproduce:
Preview any presentation in 'Slide Mode'

If possible, create a note with reproducible content and share the link with us.
https://hackmd.io/@mMd6p_RbQRauwNa94Ik9-Q/Sk_ABzStK

#### Expected behaviour
Centered slides without scrollbar
(description of expected behaviour)

#### Environment

I use HackMD on:

**Desktop**
- OS: MacOS, Windo3ws 10
- Browser: Chrome, Firefox
- Browser Version:  Current

**Comment by mrvolkomorov** [comment]
I get the same error: mobile - Android / Lightning browser, Desktop - Linux Pop!OS, Opera, Firerox

**Comment by cosinusalpha** [comment]
I have the same error.
Windows 11, latest Chrome, latest Firefox.

**Comment by drbangert** [comment]
Same here. Replicated on Chrome on MacOS and on Android.
I am just at the verge of transitioning a ton of md slide presentations I use for my university job to HackMD and upgrade to prime personal account. I just need to make sure errors like this go away quickly when reported, and hopefully dont come back ;-)
Keep up the good work!

**Comment by jackycute** [comment]
Hi everyone,

Thanks for reporting to us, we have aware this and will deploy a fix soon.

**Comment by afrozl** [comment]
Can we possibly revert to the previous version of hackmd.io? In addition to the broken slide mode, the print-to -pdf functionality is also broken. This makes hackmd.io essentially unusable for those of us that use it as a presentation service. I am a prime and team plan user and am getting frustrated by the lack of responsiveness. This is not a minor bug.

**Comment by drbangert** [comment]
Without urging too much, same here. I now have already become a prime user as soon as a saw the ticket has been acknowledged, assuming it would be a quick fix.

Like many new users joining hackmd.io at the moment (I suppose), I am migrating from swipe.to (which is doomed to end their service by the end of the month), and I am super happy with all the functionality and workflow hackmd.io has to offer. I heavily use md slides for academic teaching, so fingers crossed I can transition smoothly into the next year.

**Comment by jackycute** [comment]
We've deployed a fix for slide mode, please clear your browser cache and it should be fine now.
Thanks for letting us know.

**Comment by drbangert** [comment]
Perfect, works now. Thank you!
