### ISSUE TITLE
Cannot unpublish notes

### ISSUE THREAD

**Issue by monktastic** [hackmdio/hackmd-io-issues#288]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io

### What's the problem

There should be an "unpublish" button according to [this page](https://hackmd.io/s/how-to-publish-note), but instead I see the "published" button grayed out. This is a note in a public team, on the free plan.

#### Current behaviour

> Screenshot (optional)

<img width="298" alt="Screen Shot 2022-01-07 at 11 56 56 AM" src="https://user-images.githubusercontent.com/1936858/148586302-f8f08958-cf52-482f-9f5f-f9056c7af4f0.png">

Provide steps to reproduce:

1. Create a note in a public team.
2. Publish it.
3. Click the sharing menu.
4. There is no unpublish button. 

#### Expected behaviour

I should be able to unpublish notes.

#### Environment

I use HackMD on:

**Desktop**
- OS: macOS
- Browser: Chrome
- Browser Version: 96.0.4664.110

**Comment by chonyy** [comment]
Echoing on this, is there any way to unpublish notes?

**Comment by jackycute** [comment]
Hi all,

You can only unpublish a note from Private Team or personal account.
The Public Team is designed to publish all the notes inside.
If you are the team owner, you can transfer team to be Private/Public from team settings.
