### ISSUE TITLE
hackmd is reporting 503 Service Unavailable

### ISSUE THREAD

**Issue by programmatix** [hackmdio/hackmd-io-issues#299]
For myself and colleagues, we're seeing error 503 trying to open https://hackmd.io.  Not sure when it started exactly, but we think in the last 1-2 hours.

**Comment by jackycute** [comment]
Thanks for reporting this.
We have recovered from that.

**Comment by a1573595** [comment]
> 感謝您報告此事。 我們已經從中恢復過來。

Again。

**Comment by JiangJiaWei1103** [comment]
> Thanks for reporting this. We have recovered from that.

(Fixed )Hey Jacky, HackMD is reporting 503 again.

The 503 issue is fixed, but now there's no way to get connected. It always shows that I'm in the off-line mode.

**Comment by nateyang1999** [comment]
Same here. I can access my notes but it shows that I'm off-line.
