### ISSUE TITLE
[feature request] Export as text through HTTP requests

### ISSUE THREAD

**Issue by karlcow** [hackmdio/hackmd-io-issues#30]
Currently in the menu it is possible to either Export on a certain number of online services
or save locally as Markdown. This is cool. Though there is another use case which would greatly help to streamline the processing of the document: Export as text.

The current HTTP request gives me an HTML page.

```http
GET /features HTTP/1.1
Accept: */*
Host: hackmd.io
```

It would be cool if we could have a response to an HTTP request with `text/plain` `Accept` header.

```http
GET /features HTTP/1.1
Accept: text/plain
Host: hackmd.io
```

This  would return through HTTP the same version than the one given by "Download Markdown".

Another way of doing it would be through a parameter on the URI.

```http
GET /features?export=md HTTP/1.1
Accept: text/plain
Host: hackmd.io
```
That way it is possible to create scripts using the URI as the data-source for further processing.

Use-Case: We are using in our Mozilla community an etherpad to

1. publish an asynchronous agenda
2. take notes with multi-users during the meeting (live-scribing)
3. live read the notes when participating to the meeting
4. Process through scripting the text export to publish automagically in a different dated space.

**Comment by jackycute** [comment]
Hi @karlcow, Thanks for giving us such detailed info.
Here is a quick way to have a markdown API: `https://hackmd.io/features/download`, this will send with `text/markdown` Content-Type.

**Comment by karlcow** [comment]
@jackycute Oh shoot. Just seen that when exploring codimd. :)
Thanks a lot! Closing the issue. It answers my use case.
