### ISSUE TITLE
Search bar not working

### ISSUE THREAD

**Issue by AaronCHH** [hackmdio/hackmd-io-issues#301]
![圖片](https://user-images.githubusercontent.com/16632466/171034371-4132a4b2-049b-4c7e-9b14-134eb0708fad.png)

In the search bar in the home page, I can't seem to search notes that contain the keyword I am searching even though some notes do contain it.

**Comment by jackycute** [comment]
Hi @AaronCHH,

Thanks for reporting to us.
This might related to the full-text search we just launched, could you send email to support@hackmd.io with your account email? We can look into your account and fix it sooner, thank you!

**Comment by AaronCHH** [comment]
Thanks @jackycute , I just sent an email to support@hackmd.io

**Comment by jackycute** [comment]
Hi @AaronCHH,
We have deployed a fix at yesterday, could you please try again?

**Comment by AaronCHH** [comment]
Hi, Max
I've tried to use the search bar last night and it works.
Thanks for your help.

Sincerely,
Aaron
