### ISSUE TITLE
HackMD keep sending email whenever someone edit the note "Play Ground"

### ISSUE THREAD

**Issue by bruce30262** [hackmdio/hackmd-io-issues#31]
Hi , 
I've received like 10 emails from HackMD today  
All of them are saying `Someone changed the note: "Play Ground"`   
However I did not own this "Play Ground" note, why do the server keep sending emails to me ?   
( I did edit the Play Ground note before though, for learning the usage of HackMD ) 
Moreover this email notification **cannot be turned off**  
There's no such link that said "Click to unsubscribe" or something like that  
Just a "Sent from HackMD" and nothing else  
It is really annoying  
Can someone just tell me how to turn this thing off ?

**Comment by jackycute** [comment]
Hi Brian,

Sorry about that, we’re in the way migrate the DB and WILL provide subscribe/unsubscribe button and overall email notification settings in next two days.

Please bear us for a while, I will consider canceling subscribe this specific note for everyone.

**Comment by bruce30262** [comment]
Thanks for the quick reply  
Guess I'll have to wait for the new update

It's Bruce by the way, but whatever :)

**Comment by jackycute** [comment]
I'm sorry about that, Bruce 😅 
By the way, we just removed all the notifications of that note, you only will receive the email notification once you subscribe or edit that note again.

Thanks for your patience.

**Comment by edoardoo** [comment]
I'm gonna sacrifice for the cause and edit the note with a link to this issue...

**Comment by tabarra** [comment]
> By the way, we just removed all the notifications of that note, you only will receive the email notification once you subscribe or edit that note again.

Oh man, I should have read that before....

**Comment by jackycute** [comment]
Hi guys, we just made the feature online.

So there is a button on the top right of the view pane for subscribe/unsubscribe the note.
<img width="393" alt="2018-08-04 11 05 13" src="https://user-images.githubusercontent.com/2639151/43677806-de8d5d88-983a-11e8-88f2-b3fbefd96e6f.png">

Also, overall email notification settings is available in your [settings page](https://hackmd.io/settings).
<img width="785" alt="2018-08-04 11 06 13" src="https://user-images.githubusercontent.com/2639151/43677819-03b31bb6-983b-11e8-8cbc-c48086cd441a.png">
