### ISSUE TITLE
Little Copy Button and function on source code block

### ISSUE THREAD

**Issue by deryann** [hackmdio/hackmd-io-issues#310]
**Is your feature request related to a problem? Please describe.**
No.
Quick and speed up hackmd usage.
**Describe the solution you'd like**
If my mouse over the code block, and a copy button appear.
Press that button I can copy the code block into my local clipboard.
![2022-10-27 09_26_24-How to share code or flow json - Meta _ FAQs - Node-RED Forum](https://user-images.githubusercontent.com/26877848/198170263-d7c56d6b-a2b0-475c-8efb-5adf9b29a66c.png)
**Describe alternatives you've considered**
No.
**Additional context**
No.

Thank you.

**Comment by Dragonfly911117** [comment]
Do we have any news about this feature? Can really use it.

**Comment by jackycute** [comment]
duplicated #171
