### ISSUE TITLE
Transfer ownership of workspace

### ISSUE THREAD

**Issue by FriederikeHanssen** [hackmdio/hackmd-io-issues#313]
Hi!

is it possible to transfer ownership of teams and workspaces?

Cheers,
Rike

**Comment by jackycute** [comment]
Hi @FriederikeHanssen,
To transfer ownership of team workspace, please contact support@hackmd.io at the moment.
We have have a user flow to make this easier in the future.

**Comment by jackycute** [comment]
Hi @FriederikeHanssen,

You can now transfer team ownership on your own, please read more here: https://hackmd.io/c/tutorials/https%3A%2F%2Fhackmd.io%2F%40docs%2Ftransfer-team-ownership-en
Feel free to leave comment!
