### ISSUE TITLE
unable to display images wiithin a github repo to hackmd note

### ISSUE THREAD

**Issue by PatLiu1168** [hackmdio/hackmd-io-issues#314]
I would like to display an image from a GitHub repo. The repository is private however, the note has access to the repo and is also linked to a note in the repo.

This is my command.
![alt test](https://github.com/xxxx.jpg)

**Comment by PatLiu1168** [comment]
I'd also like to note that the alt text doesn't become a link when an image is not provided in hackmd

**Comment by jackycute** [comment]
Hi @PatLiu1168,
Thanks for letting us know.
Unfortunately, unless HackMD save a copy of the image from your GitHub repo, it won't be available in HackMD note due to GitHub repo's permission.

**Comment by mivanit** [comment]
I would also like to request this feature -- it would be incredibly useful. Since syncing notes with github probably requires the whole repo to be cloned, it seems like it would be possible (for prime plans, at least) to upload assets from the github repo to the HackMD image repository

**Comment by fredcallaway** [comment]
This feature would be enough for me to pay for a subscription.
