### ISSUE TITLE
Screen stuck while editing large document

### ISSUE THREAD

**Issue by johnroyer** [hackmdio/hackmd-io-issues#32]
I am editing a document which size is about 15 KB.

Screen sometimes stuck about half second when I adding or deleting word. Especially some keyword like `<` , `"`, `=` .  Everything goes fine without error after screen stuck.

Info:

- Hackmd version: https://hackmd.io current version (2018-08-07)
- Browser: Chrome 68.0.3440.84
- View: Editor + HTML view in 2 column (`?both` parameter in URL)

----

[php-exam.txt](https://github.com/hackmdio/hackmd-io-issues/files/2265594/php-exam.txt) is the document that make screen stuck.

Copy the file content and paste into Hackmd edit area, and try to edit any characters. Issue may occurs while editing.

**Comment by jackycute** [comment]
We just found a performance issue according to your sample data.
This will get fixed soon, thanks for reporting to us 👍

**Comment by jackycute** [comment]
This issue has been fixed and pushed to production.
