### ISSUE TITLE
Is HackMD data encrypted in-transit and storage?

### ISSUE THREAD

**Issue by adam-hurwitz** [hackmdio/hackmd-io-issues#320]
# Data encryption

**Questions**

- How data is encrypted when sent from the client to server and vice-versa?
- How is data encrypted when stored on HackMD's servers?
- Which storage solution does HackMD use, e.g. GCP, Azure, AWS, and etc?

I've searched the [HackMD Tutorial Book](https://hackmd.io/c/tutorials) and do not see information on this. 

# Why it's important to communicate this?

By sharing HackMD's best practices for security it helps provide confidence to potential individual users, projects, and larger organizations to choose HackMD as their solution for collaboration, docs, and open-source guides.

For example, GitBook states that their data is encrypted in transit and once in storage on Google Cloud. - *[Security FAQ > Is customer data encrypted?](https://policies.gitbook.com/privacy-and-security/security/security-faq#is-customer-data-encrypted)*

**Comment by jackycute** [comment]
Hi @AdamSHurwitz,
We are happy to answer those questions:

> How data is encrypted when sent from the client to server and vice-versa?

We use TLS to encrypt the connection between client and server.

> How is data encrypted when stored on HackMD's servers?

We do AES-256 encryption at the rest.

> Which storage solution does HackMD use, e.g. GCP, Azure, AWS, and etc?

Mainly on AWS.

**Comment by adam-hurwitz** [comment]
Thank you for providing those details! I've updated my [HackMD security notes](https://hackmd.io/@openguide/hackmd/#Security) on HackMD. :-)
