### ISSUE TITLE
Gibberish on typing

### ISSUE THREAD

**Issue by CoolJosh0221** [hackmdio/hackmd-io-issues#322]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

I use the brave browser and when I try to type in hackmd, I got gibberish.

https://user-images.githubusercontent.com/88709160/217860720-c8b3ee74-e7cc-4c21-861b-f732716df8f4.mp4

OS: macOS
browser: Brave Browser

**Comment by jackycute** [comment]
Hi @CoolJosh0221,
Could you provide OS version and Brave version?
Do you install any browser extensions?

**Comment by CoolJosh0221** [comment]
<img width="205" alt="Screen Shot 2023-02-11 at 10 52 18 AM" src="https://user-images.githubusercontent.com/88709160/218235315-baa5b7a5-8c29-4de1-890f-780515cc7618.png">

<img width="643" alt="Screen Shot 2023-02-11 at 10 53 30 AM" src="https://user-images.githubusercontent.com/88709160/218235355-2949f6c7-7b9e-407a-9920-11e52f98d5f0.png">Brave Version:
Version 1.48.158 Chromium: 110.0.5481.77 (Official Build) (arm64)

**Comment by CoolJosh0221** [comment]
issue no longer exists

**Comment by CoolJosh0221** [comment]
issue exists again
but only for I can't move my cursor and I can't type

**Comment by jackycute** [comment]
Hi @CoolJosh0221,

We didn't change anything of the editor in the meanwhile.
If you seeing regression of issue, probably it's Brave or one of your extension causing this problem.
