### ISSUE TITLE
Upgrade MathJax to version 3.2

### ISSUE THREAD

**Issue by IvanaGyro** [hackmdio/hackmd-io-issues#323]
Current hackmd.io uses MathJax version 2.7.5 to render the math formula. MathJax 2.7.5 misses some valuable packages, for example, the "physics" package, and it's [slower than version 3](https://www.intmath.com/cg5/katex-mathjax-comparison.php). I hope MathJax version 3 can be applied to hackmd.io to enable more features for rendering math equations.

**Comment by mlzxy** [comment]
+1

The math rendering in hackmd is slow and lacks support of certain latex command, e.g., `\limits`.  Please consider an upgrade.

**Comment by torfjelde** [comment]
Did they just upgrade this?

![image](https://github.com/hackmdio/hackmd-io-issues/assets/11074788/311f92d3-d4c8-4835-906e-c4c5a9746bfb)

**Comment by torfjelde** [comment]
I noticed because all my usages of commands from `physics` stopped working

**Comment by jackycute** [comment]
> I noticed because all my usages of commands from `physics` stopped working

Hi @torfjelde,
We have upgraded MathJax to v3 and you can enable physics by require it like: `\require{physics}`.
It won't enable by default because it affects how other formula's rendering.

**Comment by torfjelde** [comment]
Ah yes, I figured that out:) I was just saying I discovered the transition to MathJax 3 because of this (which I'm _very_ happy and grateful about; thank you!)
