### ISSUE TITLE
Unable to link GitHub account to HackMD – Error "read ECONNRESET"

### ISSUE THREAD

**Issue by adam-hurwitz** [hackmdio/hackmd-io-issues#324]
# Expect vs observe

- Expect: Sync a GitHub account and repository to a new and/or exiting HackMD note.
- Observe: Error: `request to https://github.com/login/oauth/access_token failed, reason: read ECONNRESET`

# Steps

I followed the steps under [Sync a Note with GitHub](https://hackmd.io/s/link-with-github), e.g. [hackmd.io/@openguide/safedao](https://hackmd.io/@openguide/safedao)

1. Make sure my HackMD email has GitHub access under the repository’s permission settings: Team admin, Team member, or Invitee admin.
    a. I've changed my HackMD email address to be the same email as my GitHub primary email address.
2. Install [Hackmd Hub app](https://github.com/apps/hackmd-hub) within my GitHub account.
3. Link GitHub to HackMD
    a. Menu (Bottom-left button with username) > *Settings* > *Integration* > Select *Link with GitHub*: **Received the error above.**
4. Enable GitHub in a note: Note overflow menu (3 dots in the top-right) > *Versions and GitHub Sync* > *Pull from GitHub* or *Push to GitHub* > Select to *Sign in to GitHub*: **Received the error above.**

# Attempted solutions

- Link existing HackMD note and/or new note.
- Try *Pull from GitHub* and *Push to GitHub*
- Sign out and sign in to HackMD
- Clear browser cache and cookies
- Disable ad blockers
- Try on Firefox and Chrome
- Disable VPN
- Create a new note and attempt to link
- Enable *All repositories* in the [HackMD Hub app](https://github.com/apps/hackmd-hub)
- Revoke and re-enable HackMD Hub access: GitHub *Settings* > *Integrations* > *Applications* > *Authorized GitHub Apps* > Select to revoke access.
- Uninstall and reinstall HackMD Hub access.
- Try on home Wi-Fi vs. cafe Wi-Fi
- Use GitHub Privacy email as HackMD account email: `3938076+AdamSHurwitz@users.noreply.github.com`
    - Unable to switch username to this because I haven't received the invite email.
- Disable GitHub *Keep my email addresses private* feature. 

# Environment

**Desktop**
- OS: macOS Ventura v13.2
- Browser: Firefox v109.0.1 and Chrome v110.0.5481.77

**Comment by jackycute** [comment]
Hi @AdamSHurwitz,
Thanks for reporting.
I think it might be our WAF rule block this request by accident.
We will look into this and you can try again later.

**Comment by adam-hurwitz** [comment]
Much appreciated Max!

What is WAF?

**Comment by jackycute** [comment]
> Much appreciated Max!
> 
> What is WAF?

WAF stands for web application firewall, there are some routing rules that protect our server not been DoS or Abused.

**Comment by adam-hurwitz** [comment]
@jackycute, After taking a look at the issue Is there a rough estimate on how long it might take to fix?

I'd like to demo HackMD's two-way GitHub sync to the [Safe](https://safe.global) (Formerly Gnosis Safe) core team and SafeDAO as we're exploring strategies for open guides.

**Comment by jackycute** [comment]
Hi @AdamSHurwitz,
We are investigating the issue, it seems the GitHub API has some minor changes that cause the flow on retrieving user access token failed.
I will keep you updated here.

**Comment by jackycute** [comment]
Hi @AdamSHurwitz,
We just deployed a fix for that, should be working now.
Feel free to re-open if you still have the issue, thanks again.

**Comment by adam-hurwitz** [comment]
Much appreciated Max! I will test the fix and report back to confirm. 🙏🏻

**Comment by adam-hurwitz** [comment]
I'm happy to confirm that this issue has been resolved! I have made a [commit](https://github.com/AdamSHurwitz/hackmd-og/commits/main) to my repo in order to verify.

Thanks again.
