### ISSUE TITLE
Unable to create public team with a personal account

### ISSUE THREAD

**Issue by adam-hurwitz** [hackmdio/hackmd-io-issues#325]
# Expect

Today I attempted to create a Public team for my [open source crypto guides](https://docs.google.com/document/d/1u9QQUVDuz1ryBTmhiZV9-WSIC2m4DKOaqIKOuM2MN_c/edit#heading=h.dkdaj5azl3za) in my free personal account.

# Observed

Unfortunately, I'm receiving a `Permission denied` error for my personal account.

- User: [hackmd.io/@adamhurwitz](https://hackmd.io/@adamhurwitz)
- Device: macOS v13.2.1
- Browser: Firefox v110

<img width="1680" alt="Create public team Permission denied" src="https://user-images.githubusercontent.com/3938076/219794240-c07c67ec-3bd1-4bac-9f27-2bdbb1e505f3.png">

# Attempted solutions

- Clear the cache and cookies and sign back in
- Disable VPN and ad blockers
- Test in Chrome browser

Much appreciated!

**Comment by jackycute** [comment]
Hi @AdamSHurwitz,
Thanks for reaching us.

It seems you have been identified using anonymous IP (like: VPN, Tor) or hosting provider (like: AWS, GCP).
There are some firewall rules applied in order to protect us from abusing usage.

Please try again later, we will see what we can do.

**Comment by AdamSHurwitz** [comment]
Thank you for the context @jackycute!

I re-tried creating a public team, making sure the VPN is disabled, and it results in the same error message. There must be a block on the account level. I will retry again later this weekend.

In the long-term it would be great if VPN access is supported as privacy and security seem to align well with HackMD's open-source values.

**Comment by AdamSHurwitz** [comment]
Thank you for the context @jackycute!

I re-tried creating a public team, making sure the VPN is disabled. In the long-term it would be great if VPN access is supported as privacy and security seem to align well with HackMD's open-source values.

It now shows the error `Duplicate team URL path, please try another` for `https://hackmd.io/team/openguide`.
- I checked the URL `https://hackmd.io/team/openguide` and there does not seem to be another team with this name.
- This is the URL I attempted earlier, so I wonder if it is showing the error since the request from before partially went through.
- I've been using the account [hackmd.io/@openguide](https://hackmd.io/@openguide) to create an open-source book on how to use HackMD.: [hackmd.io/@openguide/hackmd](https://hackmd.io/@openguide/hackmd)
  - I wonder if this is causing the same team name to be blocked.
  - I had a call with Jong-kai Yang today, who taught me about public teams. These are a perfect use case to switch over from the private @openguide account to the public team @openguide account.

**Comment by adam-hurwitz** [comment]
Thank you for the context @jackycute!

I re-tried creating a public team, making sure the VPN is disabled. In the long-term it would be great if VPN access is supported as privacy and security seem to align well with HackMD's open-source values.

It now shows the error `Duplicate team URL path, please try another` for `https://hackmd.io/team/openguide`.
- I've been using the account [hackmd.io/@openguide](https://hackmd.io/@openguide) to create an open-source book on how to use HackMD.: [hackmd.io/@openguide/hackmd](https://hackmd.io/@openguide/hackmd)
- I wonder if this is causing the same team name to be blocked.
- After my call with @GitOnion today I realize a public team accomplishes my goal of creating open-source guides/books instead of having the [at]openguide user account.

**Can I simply delete the [at]openguide personal account in order to free up the [at]openguide public team account?**
- I'd love to migrate the user account to the public team if possible now that I know public teams are the best option.

**Comment by jackycute** [comment]
Hi @AdamSHurwitz,

We will try our best to reduce the abusing and hopefully we can reduce firewall rules.
But I don't quite understand the relationship between VPN and open-source values.

You can change your username and create a team using "openguide".
The username and team path name can't be the same.

**Comment by adam-hurwitz** [comment]
> We will try our best to reduce the abusing and hopefully we can reduce firewall rules.

Thank you! That is good to hear.

> But I don't quite understand the relationship between VPN and open-source values.

That is a fair statement as I did not explain the above.

Some of the benefits of open-source software is that the code can be audited and forked. This has the _potential_ to improve the software's security for users because they know the code is doing what is expected and they are not "locked-in" since others can build off of the original.
- Some view these potential security features of auditability and forkability as benefits of being open-source.
  - I view security as a value associated with open-source due to its potential whereas others may not explicitly. VPNs are an additional privacy/security tool to complement the open-source security properties above.
  - Others may view this as a by-product of being open-source.
- Also, open-source tends to strive for greater access to those globally and in certain countries people rely on VPNs to access accurate and reliable information.

> You can change your username and create a team using "openguide".

Done. Teams are working as expected now with the desired permalinks, e.g. [hackmd.io/@openguide/hackmd](https://hackmd.io/@openguide/hackmd). Thank you for the helpful support again!
