### ISSUE TITLE
Add document Title in the header

### ISSUE THREAD

**Issue by biafffff** [hackmdio/hackmd-io-issues#328]
Following the [OverLeaf](https://www.overleaf.com/) approach (LaTeX editor), I would like to see the title of the document I'm working on clearly visible in the header of the HackMD editor. 

This addition could help when dealing with similar versions of the same document such as one that is the internal draft and another slightly changed version that will be shared with external users. 

<img width="933" alt="image" src="https://user-images.githubusercontent.com/26275332/222516177-a8d71ef1-492f-4c28-ae1b-fd9fbbc43735.png">
<img width="807" alt="image" src="https://user-images.githubusercontent.com/26275332/222517464-5aaf7fde-4626-4d57-bfa8-7cce026781ad.png">

The team can think of "stealing" additional small features from OverLeaf, but I see if it wants to keep the editor raw for coders :)

**Comment by elekli** [comment]
@biafffff We are working on the new design of HackMD, and, among other changes, separating title from the Markdown content is one of them. The title will get its own place on the UI. Please follow our [Changelog](https://blog.hackmd.io/changelog).

**Comment by jackycute** [comment]
you can now setup note title and tags from title bar.
<img width="883" alt="截圖 2023-12-19 下午3 50 17" src="https://github.com/hackmdio/hackmd-io-issues/assets/2639151/5cbc65a9-3a99-459a-8fe8-01e145c1704b">
