### ISSUE TITLE
Cannot change link preview

### ISSUE THREAD

**Issue by davidhcefx** [hackmdio/hackmd-io-issues#329]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### Read our Official tutorial

It's on https://hackmd.io/c/tutorials/

或是中文版 https://hackmd.io/c/tutorials-tw/

### What's the problem

- The [document](https://hackmd.io/s/features#YAML-Metadata) stated that link previews could be changed by setting the YAML metadata.
- However, it's not working.

#### Current behaviour

- [Facebook Tool][fb]:

<img src="https://user-images.githubusercontent.com/23246033/224479468-0d116111-50d3-4213-b274-4412afb13580.png" width=50%>

- [LinkedIn Tool][linkedin]:

<img src="https://user-images.githubusercontent.com/23246033/224479475-1325b5f7-6df7-41e7-8c7c-053f4aea6c08.png" width=50%>

Provide steps to reproduce:

1. Go to https://hackmd.io/gTrV9LfuS0mD4onCY-5cFg?view
2. Try with [Facebook tool][fb] or [LinkedIn tool][linkedin]
3. Link previews not been set to our customized image.

[fb]: https://developers.facebook.com/tools/debug/
[linkedin]: https://www.linkedin.com/post-inspector/

#### Expected behaviour

Link preview been set to our customized image.

#### Environment

I use HackMD on:

**Desktop**
- OS: Windows 10
- Browser: Chrome
- Browser Version: 110.0

**Comment by chiro-hiro** [comment]
I got the same problem, can't update the review thumbnail and content.

**Comment by jackycute** [comment]
Hi guys,
Please read this: https://hackmd.io/c/tutorials/%2F%40docs%2Fhow-to-edit-metadata-of-a-note-en
We have moved YAML metadata to note settings now.
