### ISSUE TITLE
creating a note via markdown link is currently not possible due to a human verification process that is in place. As a result, attempting to create a note in this manner will not yield any results.

### ISSUE THREAD

**Issue by reillo** [hackmdio/hackmd-io-issues#330]
When I tried to create a note from a link, it does nothing:

<img width="1508" alt="Screen Shot 2023-03-12 at 1 16 20 PM" src="https://user-images.githubusercontent.com/6128004/224525800-1a034675-023f-4668-bb0c-19769a3ae38c.png">

When i checked the consoled and found that the ajax request was failing. I copied the ajax url and paste directly from the browser url, and found that it wants to verify if i'm a robot or not.
<img width="1506" alt="Screen Shot 2023-03-12 at 1 16 41 PM" src="https://user-images.githubusercontent.com/6128004/224525812-ec7a82b8-3bd5-4e97-b370-a7992d9c115a.png">

**Comment by jackycute** [comment]
Hi @reillo,

Thanks for letting us know.
We have looked into this issue and adjust few rules, now it should work under most cases.
Feel free to re-open if you still having this, thanks!

**Comment by reillo** [comment]
Thanks for fixing it, much appreciated!
