### ISSUE TITLE
want  to know  why the maindland of china  can't  access this website?  any method to make it work?

### ISSUE THREAD

**Issue by FredInnovusion** [hackmdio/hackmd-io-issues#332]
### Is this a hackmd.io issue?

- [ yes ] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### Read our Official tutorial

It's on https://hackmd.io/c/tutorials/

或是中文版 https://hackmd.io/c/tutorials-tw/

#### Current behaviour

> Screenshot (optional)

Provide steps to reproduce:

If possible, create a note with reproducible content and share the link with us.

e.g. note link: https://hackmd.io/features

#### Expected behaviour

(description of expected behaviour)

#### Environment

I use HackMD on:

**Desktop**
- OS: [eg. macOS]
- Browser: [e.g. chrome, safari, firefox, opera]
- Browser Version: [71]

**Mobile**

- Device: [e.g. iPhone XS]
- OS: [e.g. iOS 12.1]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 23]

**Comment by jackycute** [comment]
Hi @FredInnovusion,

As far as we know, hackmd.io has been blocked by GFW without known reason for years.
Probably hackmd.io allows almost any content been published and it's not censored by China.
Maybe you can try using VPN or other proxy to workaround, but we don't have solution for this.
