### ISSUE TITLE
Comparison of three growth curves for the diagnosis of extrauterine growth retardation at 40 weeks postconceptional age and associated factors in preterm infants in the city of Yaoundé, Cameroon

### ISSUE THREAD

**Issue by sankenk** [hackmdio/hackmd-io-issues#333]
The aim of this work is to analyze the concordance between the different growth curves for the appreciation of the extrauterine growth as well as the factors associated with the RCEU at 40 weeks of post-conceptional age in preterm infants in the city of Yaoundé in Cameroon.
specifically, we want to: 
- To describe the variability of growth parameters obtained after the use of different growth curves (Intergrowth -21, Fenton and WHO) in low birth weight preterm infants in Yaoundé, Cameroon.
- To identify the profile of the parents as well as that of the preterm newborns of PPN.
- To determine the factors associated with prematurity and to show their influence in the occurrence of extrauterine growth retardation.
- To model the growth curves in our context.

**Comment by jackycute** [comment]
Seems not related to the repo.
Not an export of this.
