### ISSUE TITLE
Cannot make a team of 3 private.

### ISSUE THREAD

**Issue by popey** [hackmdio/hackmd-io-issues#336]
### Is this a hackmd.io issue?

- [X] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem

I want to switch my workspace from public to private. 
We had 4 members, and I removed 1, so we now have 3.
I cannot make the team private.

#### Current behaviour

In "Danger Zone" I clicked "Change to Private Team". I get a popup:

```
"You're about to change (Team name) to Private team. Because the members are more than 3, team notes will become readonly, upgrade the team to continue editing.

You can choose:

[ ] Team notes will remain current permission and publishment status
[ ] Team notes will be changed to readonly by members"
```

#### Expected behaviour

As we have only 3 members, I expect to be able to make a private team on the free tier.

#### Environment

I use HackMD on:

**Desktop**
- OS: Ubuntu
- Browser: Microsoft Edge
- Browser Version: Version 112.0.1722.48 (Official build) (64-bit)

**Comment by jackycute** [comment]
Hi @popey,

Thanks for letting us know.
Please provide your team workspace name or team url path here or by sending email to support@hackmd.io, we are happy to help!

**Comment by popey** [comment]
Thanks @jackycute - I've emailed support.

**Comment by popey** [comment]
I'm going to close this, as we have decided not to use hackmd, but another tool. Thanks for the quick replies!
