### ISSUE TITLE
Upgrade Mermaid to latest (10.10)

### ISSUE THREAD

**Issue by MarinPostma** [hackmdio/hackmd-io-issues#338]
**Is your feature request related to a problem? Please describe.**
Haskmd is using a quite old version of Mermaid, that misses a lot of the new cool features

**Describe the solution you'd like**
A more recent mermaid version (latest 🤞)

**Describe alternatives you've considered**
Not using those sweet new mermaid features

**Comment by rafaelbeckel** [comment]
I second that. I'm trying to add notes to a class diagram, and I see it is not supported. Upgrading to the latest Mermaid version would solve it. They added this feature in late 2022 (and many others after that).

**Comment by jackycute** [comment]
We have upgraded to mermaid 10.4.0, please take a loot at:
https://hackmd.io/s/release-notes#-EE-1592-2023-10-17-1741

**Comment by jackycute** [comment]
Please open another issue if you request for newer mermaid version upgrade.
