### ISSUE TITLE
Everything looks bold

### ISSUE THREAD

**Issue by michcio1234** [hackmdio/hackmd-io-issues#34]
This is a UX issue.

I have an impression that the font that's used to render notes is always bold. Headers and actual bold text do stand out, but it's _bold vs. bolder_ instead of _regular vs. bold_. 

I don't think that this is the fault of my browser or OS (I have the same impression on mobile), but I'm using Chrome on Linux Mint.

To illustrate what I'm talking about:
this is what it looks like:
![image](https://user-images.githubusercontent.com/16254622/44708249-ee0e2e80-aaa6-11e8-8b63-e2fb3c908651.png)
and this is what I would expect it to look like:
![image](https://user-images.githubusercontent.com/16254622/44708336-26157180-aaa7-11e8-92c3-a97fdab6c83b.png)
Notice the difference in appearance of regular text.

**Comment by jackycute** [comment]
Hi @michcio1234, thanks for reporting this.
We see this might cause by we recently introduce font Roboto but haven't include all font weight.

**Comment by BinotaLIU** [comment]
Should be fixed now. If it still happen, please re-open this issue.

**Comment by michcio1234** [comment]
Thanks!
