### ISSUE TITLE
Title and tags are not editable on workspace notes

### ISSUE THREAD

**Issue by ben-509** [hackmdio/hackmd-io-issues#341]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem

In a new note, title and tags can't be edited.

#### Current behaviour

In a team workspace, with a new note or existing note, tags and title are unresponsive.

[Clicking around title and tags](https://github.com/hackmdio/hackmd-io-issues/assets/95769279/1bc8166c-ea99-4bd9-962e-355113241956)

> If possible, create a note with reproducible content and share the link with us.

An empty note reproduces the behavior.

#### Expected behaviour

It should work as it does on a note on a regular account.

Create a note. You can:

1. Click into the title at any time to edit it.
2. Click into tags and edit them.
3. Exit the note, title and tags persist.

![image](https://github.com/hackmdio/hackmd-io-issues/assets/95769279/c9af0cfe-66d8-4dd8-a440-2cd4f5026255)

#### Environment

I use HackMD on:

**Desktop**
- OS: [Linux]
- Browser: [Chrome]
- Browser Version: [114.0.5735.133 (Official Build) (64-bit) ]

Additional reports: Chrome and Firefox on Windows.

#### Additional context

Possibly related: #340

**Comment by ben-509** [comment]
Not a JS expert, but let me know if there's anything I can do in the console or dev tools to check. I didn't see any errors reported that seemed to fit the issue.

**Comment by tjpalmer** [comment]
For basic usage with new notes, this makes HackMD semi unusable. The team note list just shows a bunch of "Untitled" and there's little we can do about it.

**Comment by jwatson0** [comment]
I just got a response from the support email:
> This is a known bug and we are working on it. We apologize for all the inconveniences you have been experienced.

**Comment by milouse** [comment]
I’m suffering from the same issue and I can also add that it impacts picture uploading too. It’s now impossible to upload a picture into pad. Same issue: an XHR request is made in background, which fails with a 403 error code.

**Comment by ben-509** [comment]
Seems like it's fixed.

**Comment by milouse** [comment]
I confirm it’s fixed on my side
