### ISSUE TITLE
Details tag does not support Markdown and cannot be collapsed

### ISSUE THREAD

**Issue by fugohan** [hackmdio/hackmd-io-issues#343]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### Read our Official tutorial

It's on https://hackmd.io/c/tutorials/

或是中文版 https://hackmd.io/c/tutorials-tw/

### What's the problem

When I use the details html tag, I can only use html syntax in it. But I want to use markdown in it. Also its not possible to collapse the details tag. 

#### Current behaviour

```
<details>
Important 
- None
- of these 
- [ ] items 
</details>
```
![image](https://github.com/hackmdio/hackmd-io-issues/assets/46691165/ff49beea-f147-4d2f-834d-a11b73d8925f)

#### Expected behaviour

I want to see the markdown output not a line with the text. 

#### Environment

I use HackMD on:

**Desktop**
- OS: Linux
- Browser: Brave
- Browser Version: 114.0.5735.198

**Comment by jackycute** [comment]
Hi @fugohan,
For you case, please leave a blank line under and above the html tags like this:
```
<details>

Important 
- None
- of these 
- [ ] items
 
</details>
```

This should works.
