### ISSUE TITLE
Theme changes in slides do not have any effect

### ISSUE THREAD

**Issue by patrickpichler** [hackmdio/hackmd-io-issues#348]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### Read our Official tutorial

It's on https://hackmd.io/c/tutorials/

或是中文版 https://hackmd.io/c/tutorials-tw/

### What's the problem
Setting the `theme` in `slideOptions` is not working consistently.

#### Current behaviour
Sometimes (I couldn't identify a pattern) changing the `theme` works, but most of the time any chance is 
ignored. I tried setting it in the presentation itself, as well as in the `Customize Slide` options in the share menu.

> Screenshot (optional)

Provide steps to reproduce:

1. Create new note
2. At one slide
3. Preview it
4. Change the theme to e.g. `theme: white`

If possible, create a note with reproducible content and share the link with us.

e.g. note link: https://hackmd.io/features

#### Expected behaviour

As soon as the theme is changed, I expect the rendered slides to be in that specified theme and not the default black.

#### Environment

I use HackMD on:

**Desktop**
- OS: macOS
- Browser: firefox and chromium

**Comment by jackycute** [comment]
Hi @patrickpichler,
We have deployed few fixes for this, could you give it a try and let us know if this issue persists?
Thank you!

**Comment by patrickpichler** [comment]
Hey, 
I tried switching the `theme` setting from `white` to `black` and opened the preview page, but it didn't update.

Edit: I just tried it via the `Customize slide options` in the share menu and from there it works.

**Comment by jackycute** [comment]
> Hey, I tried switching the `theme` setting from `white` to `black` and opened the preview page, but it didn't update.
> 
> Edit: I just tried it via the `Customize slide options` in the share menu and from there it works.

Yeah, we have made the slide options to take affect only in the sharing menu.
https://blog.hackmd.io/blog/2023/06/12/how-to-handle-metadata-change-en
