### ISSUE TITLE
mhchem mathjax commands sometimes does not render properly

### ISSUE THREAD

**Issue by edwar4rd** [hackmdio/hackmd-io-issues#354]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### Read our Official tutorial

It's on https://hackmd.io/c/tutorials/

或是中文版 https://hackmd.io/c/tutorials-tw/

#### Current behaviour

![image](https://github.com/hackmdio/hackmd-io-issues/assets/61072918/1e067232-4779-4d49-bce9-0c511c2c2911)

Provide steps to reproduce:

1. Create a note
2. Add `$\ce{H2O}$`
3. Might or might not render the `\ce` command properly
4. Refresh (F5 or Ctrl+Shift+R) the page and it might/might not work

If possible, create a note with reproducible content and share the link with us.

https://hackmd.io/@edwar4rd/SyrEd-J46

Some older notes created by others are also broken

https://hackmd.io/@hikari/H1sVJtRy5

#### Expected behaviour

`$\ce{H2O}$` should be displayed properly as a chemical formula with auto typesetting.

![image](https://github.com/hackmdio/hackmd-io-issues/assets/61072918/7a8e6e40-af02-492d-8dd8-b49a6c14f0de)

#### Environment

I use HackMD on:

**Desktop**
- OS: GNU/Linux
- Browser: Firefox
- Browser Version: 119.0 (64-bit)

**Desktop**
- OS: GNU/Linux
- Browser: Chromium
- Browser Version: 119.0.6045.123 (Official Build)

**Desktop**
- OS: Windows 11
- Browser: Firefox
- Browser Version: 119.0.1（64 位元）

**Desktop**
- OS: Windows 11
- Browser: Chrome
- Browser Version: 119.0.6045.124 (正式版本) (64 位元)

**Mobile**
- OS: Android 13; SM-A5360 Build/TP1A.220624.014
- Browser: Chrome
- Browser Version: 119.0.6045.66

Tested and reproducible (sometimes after a few page refresh) in all of the above environment.

#### Additional context

- Might be related to recent MathJax version bump
- `Uncaught (in promise) TypeError: this.parent(...) is null` error flood console
  - `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'replaceChild')` when using Chromium/Chrome
- Sometimes it works sometimes it doesn't after page refresh
  - I've tried clearing cache multiple times
  - Maybe related to cdn cache?

**Comment by jackycute** [comment]
We have deployed a fix, now it should display properly.
Feel free to keep us posted, thank you!

**Comment by edwar4rd** [comment]
Didn't test throughly but seem fixed.
Thanks!
