### ISSUE TITLE
latex rendering issue

### ISSUE THREAD

**Issue by marwahaha** [hackmdio/hackmd-io-issues#355]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### Read our Official tutorial

It's on https://hackmd.io/c/tutorials/

或是中文版 https://hackmd.io/c/tutorials-tw/

### What's the problem

when using
```
### blah: $\text{QMA}_{c,s}$
```
the "c,s" is weirdly uppercased, which is not what I want!

<img width="474" alt="Screenshot 2023-11-15 at 9 59 56 PM" src="https://github.com/hackmdio/hackmd-io-issues/assets/2541209/5fa54cee-02e1-47d1-995d-8f9747104be0">

This happens in slide mode when you "customize slides" with a theme.

#### Current behaviour

see an example https://hackmd.io/@kmarw/HyZ84GXN6

> Screenshot (optional)

Provide steps to reproduce:

If possible, create a note with reproducible content and share the link with us.

e.g. note link: https://hackmd.io/features

#### Expected behaviour

(description of expected behaviour)

#### Environment

I use HackMD on:

MacOS, Firefox

**Desktop**
- OS: [eg. macOS]
- Browser: [e.g. chrome, safari, firefox, opera]
- Browser Version: [71]

**Mobile**

- Device: [e.g. iPhone XS]
- OS: [e.g. iOS 12.1]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 23]

#### Additional context

This wasn't a problem during June 2023! Something changed since then.

**Comment by jackycute** [comment]
It's because the white theme of revealjs has default to do uppercase styling for all headings.
You can use style tag to overwrite it or use other theme.
```
<style>
    .reveal h1, .reveal h2, .reveal h3, .reveal h4, .reveal h5, .reveal h6 {
        text-transform: none;
    }
</style>
```

**Comment by marwahaha** [comment]
This wasn't the behavior I wanted, but the following worked for me:
```
<style>
    .reveal h1 .mathjax, 
    .reveal h2 .mathjax, 
    .reveal h3 .mathjax, 
    .reveal h4 .mathjax, 
    .reveal h5 .mathjax, 
    .reveal h6 .mathjax {
        text-transform: none;
    }
</style>
```
