### ISSUE TITLE
[BUG] CSS Injection ".markdown-body { max-width: 2048px; }" is no longer working

### ISSUE THREAD

**Issue by SPyofgame200** [hackmdio/hackmd-io-issues#364]
I can no longer use `.markdown-body` for wider view ?

![image](https://github.com/hackmdio/codimd/assets/52689671/e1389542-b3aa-4a66-9e6b-3bbea8f5e004)
![image](https://github.com/hackmdio/codimd/assets/52689671/ff7fea4e-bbc3-4d72-8c47-e40f90857428)

**Comment by jackycute** [comment]
It still works.
Please add important to overwrite it.
```
<style>
    .markdown-body {
        max-width: 2048px !important;
    }
</style>
```
