### ISSUE TITLE
書本模式疑似出問題？

### ISSUE THREAD

**Issue by Latisha19** [hackmdio/hackmd-io-issues#365]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### Read our Official tutorial

It's on https://hackmd.io/c/tutorials/

或是中文版 https://hackmd.io/c/tutorials-tw/

### What's the problem
在嘗試將一篇筆記以書本模式分享開啟後出現問題

#### Current behaviour

> Screenshot (optional)
出問題截圖：
![1703581984591](https://github.com/hackmdio/hackmd-io-issues/assets/85289926/b9da0066-920c-4382-8251-77a8c9698cf7)

原本正常應該長這樣：(分屬兩個不同書本的筆記)
![2](https://github.com/hackmdio/hackmd-io-issues/assets/85289926/2276c3a7-62f3-4240-ab7f-13763f56c631)
![1](https://github.com/hackmdio/hackmd-io-issues/assets/85289926/b746f1cc-9962-4cf1-b27a-ee5347d509c4)

Provide steps to reproduce:
1. 前往 [hackmd 首頁](https://hackmd.io/)
2. 按下隨意一篇筆記 (非當作書本模式首頁的那篇，而是書本模式下其他篇筆記)
3. 以書本模式分享後按下 [預覽]

If possible, create a note with reproducible content and share the link with us.

e.g. note link: https://hackmd.io/features
提供一下 [網址](https://hackmd.io/@Latisha/Syv6jJywT/https%3A%2F%2Fhackmd.io%2F%40Latisha%2FHylK3qF4a%2F%252FQSgM76SlTDid81H9qfjW_A) 好了...？

#### Expected behaviour

原本應出現正常的書本模式 (如上方 2 張正常版截圖)

#### Environment

I use HackMD on:

**Desktop**
- OS: Win11
- Browser: chrome
- Browser Version: 120.0.6099.129 (Official Build) (64-bit)

#### Additional context

無

**Comment by jackycute** [comment]
Hi @Latisha19,
感謝詢問！
分享模式設定書本的筆記，分享的連結就會用書本模式瀏覽。
且書本模式裡面也可以放書本模式，這是在預期內的功能 (也就是書本模式可以多層使用)，書本模式會預設顯示筆記的第一個清單連結。

**Comment by Latisha19** [comment]
您好：
不好意思，但是在我第一張截圖中最左邊是原本應該長相正常的筆記(就像第三章截圖一樣)，但被縮成很奇怪的長相，這樣是沒問題的嗎QQ

**Comment by jackycute** [comment]
> 您好： 不好意思，但是在我第一張截圖中最左邊是原本應該長相正常的筆記(就像第三章截圖一樣)，但被縮成很奇怪的長相，這樣是沒問題的嗎QQ

或許我們可以檢查一下有沒有少移除的區塊，可以的話想請您提供可以重現的範例原始碼，謝謝！

**Comment by Latisha19** [comment]
@jackycute 
好的，嗯...
1. 打開[uu](https://hackmd.io/sYouEBuXQ52dqik8W78CVw)，以書本模式分享後按下 [預覽] (如附圖)
![image](https://github.com/hackmdio/hackmd-io-issues/assets/85289926/262dee17-fc21-4761-96bf-8728268a966f)
2. See error

**Comment by jackycute** [comment]
書本模式的預期使用方式，是使用者新增一篇收集其他筆記連結的筆記清單，並設定成書本模式。
這邊看到您的用法，好像是希望一篇筆記可以用瀏覽模式也可以用書本模式開啟並且都顯示正常。
想請問您預期第一張圖的書本模式應該呈現什麼結果呢？

**Comment by Latisha19** [comment]
嗯...原本只是想說筆記被縮成那樣有點怪，但這樣想想也對，筆記轉書本模式會這樣縮是正常的
是我搞錯用法了，不好意思打擾了~
