### ISSUE TITLE
Mis-alignment on home page

### ISSUE THREAD

**Issue by irfan-iiitr** [hackmdio/hackmd-io-issues#366]
There is an misalignment in the front home page in the header where github and world web logo is showed.
![screenshot (1)](https://github.com/hackmdio/codimd/assets/123577873/ff0ededa-09f9-4f8c-932d-5bad175077f5)

**Comment by irfan-iiitr** [comment]
i want to fix this

**Comment by jackycute** [comment]
Hi @irfan-iiitr,
Thanks for reporting.
However, the CodiMD docs site is hosted at hackmd.io, we will fix this.

**Comment by jackycute** [comment]
This has been fixed.
<img width="1439" alt="截圖 2024-01-03 上午9 14 56" src="https://github.com/hackmdio/hackmd-io-issues/assets/2639151/75cff89c-4768-4f6b-acfe-77b45b8e543d">
