### ISSUE TITLE
Cannot log through github: `TypeError: Cannot read properties of undefined (reading 'marketingEmails')`

### ISSUE THREAD

**Issue by fxcoudert** [hackmdio/hackmd-io-issues#368]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

#### Current behaviour

<img width="483" alt="Capture d’écran 2024-01-15 à 14 09 22" src="https://github.com/hackmdio/hackmd-io-issues/assets/1980544/fd6b66d8-3e01-4745-b006-fe5ba8a9edf4">

Provide steps to reproduce:

1. Tried to sign in through my github account
2. Clicked "Connect through github"
3. Give permissions when github asks
4. See error: `TypeError: Cannot read properties of undefined (reading 'marketingEmails')`

#### Expected behaviour

(description of expected behaviour)

#### Environment

I use HackMD on:

**Desktop**
- OS: macOS Ventura
- Browser: Safarai
- Browser Version: 17.2.1

**Comment by fxcoudert** [comment]
There's more to it. After that unsuccessful attempt, I received an email "Please confirm your email address" with a one-time link to click. I clicked on the link, but:

<img width="526" alt="Capture d’écran 2024-01-15 à 14 14 05" src="https://github.com/hackmdio/hackmd-io-issues/assets/1980544/a2ae498b-27a9-40d0-a9f0-e3749fe8388a">

**Comment by jackycute** [comment]
Hi @fxcoudert,
We are on to this, please wait for the fix.

**Comment by jackycute** [comment]
We have deployed a fix now, can you please try again now?

**Comment by jackycute** [comment]
Feel free to re-open if the issue persists.

**Comment by fxcoudert** [comment]
I can confirm it is fixed
