### ISSUE TITLE
text is unexpectedly rendered differently.

### ISSUE THREAD

**Issue by govvin** [hackmdio/hackmd-io-issues#37]
In my text, I have a string `(P)` that is unexpectedly rendered as "§".

![image](https://user-images.githubusercontent.com/5821688/45151262-693ab780-b200-11e8-9138-5387c5d7bc8f.png)

**Comment by jackycute** [comment]
Hi @govvin 
That's one of the parser feature called "smartypants".
You can use `\(P\)` instead for escaping and use plaintext.

**Comment by jackycute** [comment]
Feel free to re-open this issue.
