### ISSUE TITLE
Site blank after login

### ISSUE THREAD

**Issue by jonasW3F** [hackmdio/hackmd-io-issues#370]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem
Recently the website won't load on Brave browser after being logged in. The site is simply blank. When I delete the website data, I get back to the login page, which renders fine. But again after logging in, the site is blank. This also happens when I take down Brave's shields. This does not happen on Chrome.

#### Current behaviour

<img width="1126" alt="Screenshot 2024-02-23 at 11 48 37" src="https://github.com/hackmdio/hackmd-io-issues/assets/67730419/526ffc93-4455-464d-9460-4f29a66d3a19">

Provide steps to reproduce:

1. Simply open hackmd.io and log in.
2. Even taking shields down and clearing site data will not help.

#### Expected behaviour

Should simply work.

#### Environment

I use HackMD on:

**Desktop**
- OS: MacOS Version 14.3.1 (23D60)
- Browser: Brave
- Browser Version: v1.63.161

**Comment by jackycute** [comment]
Please re-open if you can reproduce now.
