### ISSUE TITLE
Bug Report: Background Color turns black in "Light Mode" in Firefox 

### ISSUE THREAD

**Issue by siiroi77** [hackmdio/hackmd-io-issues#377]
### Is this a hackmd.io issue?

- [O] Yes, the bug happens on https://hackmd.io

### What's the problem

According to the EE 1.74.4 2024-07-05 12:47 bug fix, the team seems to have fixed it for the background color, but the background tint problem still occurs in Firefox.

When in "View" and using "light mode", except for the first page, when the page is scrolled down, the background will appear black and cannot be displayed correctly in light color.

("Edit" and "Both" are normal.)

- View Setting:
![圖片](https://github.com/hackmdio/hackmd-io-issues/assets/28017405/1997431a-6357-4530-9d54-36d79ebeda88)
-------
- When Scroll down:
![圖片](https://github.com/hackmdio/hackmd-io-issues/assets/28017405/73347c41-c6b2-425c-9387-063ce149f467)

#### Environment

**Desktop**
- OS: Windows 10
- Browser: Firefox 120.0.1 (same issue regardless of whether firefox in auto, light or dark mode)

**Comment by jackycute** [comment]
Hi @hirosy401,
Thanks for reporting to us.
It was due to the CSS selector `:has()` only been supported after Firefox 121.
But we have deployed a fix to avoid using it, please try again and feel free to keep us posted.

**Comment by siiroi77** [comment]
Dear @jackycute 
Thanks for the response, 
and after the EE 1.74.5 update, it seems to be working properly.
Sincerely appreciate the help.
