### ISSUE TITLE
Add Share to all with link - Similar to Google doc's feature.

### ISSUE THREAD

**Issue by 0xSero** [hackmdio/hackmd-io-issues#381]
**Is your feature request related to a problem? Please describe.**
- I either have to share with individuals using their emails, share to anyone with an account, or share to everyone

**Describe the solution you'd like**
An option for sharing documents where only those with the URL can view the document

**Describe alternatives you've considered**
This is a standard feature in Google

**Additional context**
Increased privacy
Increased usability

**Comment by jackycute** [comment]
Hi @Seroxdesign,
Thanks for asking.
I think you can already do that now by simply change the read permission to everyone and copy the sharing url.
The read permission is "everyone" means exactly the same as "only those with the URL can read".
The share to everyone or say "public on internet" will need to publish the note.
<img width="317" alt="截圖 2024-07-22 晚上11 25 16" src="https://github.com/user-attachments/assets/b29d8816-913d-4a20-803b-a27ab0c38b1e">

Feel free to re-open if it's not the case, thanks.

**Comment by 0xSero** [comment]
Hey, thanks for the quick response @jackycute 
The issue I'm experiencing here:

I just tested this, if I shared a document with you in the past, or if you somehow have a link to my profile you can view all my shared with everyone or shared with signed in user's notes.

The problem there is if I'm using this hackmd for producing all my docs, if I want to keep a note semi-private, by only sharing with 1 team or group, i have to add them by email.
