### ISSUE TITLE
The view in 'Both' mode is not working properly.

### ISSUE THREAD

**Issue by sam30606** [hackmdio/hackmd-io-issues#385]
The view area didn't display next to the edit area, and the view area was blank.

![image](https://github.com/user-attachments/assets/14f0d68b-82ee-4bce-a0a4-b58f7175f463)
![image](https://github.com/user-attachments/assets/84c44e70-3ae8-4662-ac4b-231ed3b1c285)

**Comment by jackycute** [comment]
Hi @sam30606,
Could you please provide your OS version and browser version? Thanks!

**Comment by sam30606** [comment]
Hi @jackycute 

Below are the hardware information and browser version.

BTW, the issue happend on my 27' vertical monitor, I provide the resorusion too.

```bash
sam@sam-ASUS-EXPERTBOOK-B9450FA:~$ neofetch --stdout
sam@sam-ASUS-EXPERTBOOK-B9450FA 
------------------------------- 
OS: Ubuntu 24.04 LTS x86_64 
Host: ASUS B9400CEAS_B9400CEA 1.0 
Kernel: 6.8.0-41-generic 
Uptime: 2 hours, 58 mins 
Packages: 3945 (dpkg), 24 (flatpak), 34 (snap) 
Shell: bash 5.2.21 
Resolution: 1920x1080 
DE: GNOME 46.0 
WM: Mutter 
WM Theme: Adwaita 
Theme: Yaru [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: 11th Gen Intel i7-1165G7 (8) @ 4.700GHz 
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics] 
Memory: 16217MiB / 31788MiB 
```

![image](https://github.com/user-attachments/assets/a0f6846a-821a-448e-b1c4-5c572c3e1cbf)
![image](https://github.com/user-attachments/assets/cf220436-0098-452d-9bbc-a316758e35a0)

**Comment by jackycute** [comment]
Hi @sam30606,
Thanks for providing information, we tried your note but can't reproduce the issue.
Could you try to reproduce in incognito mode or in other browser?
Thanks.

**Comment by sam30606** [comment]
Hi @jackycute 

Thanks for your support! I found out how the issue happened,  it was because I had installed the [XPath Helper extension for Google Chrome](https://chromewebstore.google.com/detail/google-chrome-%E7%9A%84-xpath-%E5%8A%A9%E6%89%8B/madglblnbddpkecoihhnkohnofachcgn?hl=zh-TW).
