### ISSUE TITLE
The Image missing error message isn't clear 

### ISSUE THREAD

**Issue by GitOnion** [hackmdio/hackmd-io-issues#392]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io

### What's the problem
The copy text here needs some minor revision 

#### Current behaviour

<img width="771" alt="Screenshot 2024-11-11 at 2 47 58 PM" src="https://github.com/user-attachments/assets/60b99706-1072-48e4-9805-3c627cbba889">

#### Expected behaviour
Please change the copy text to the following:

```
Possible Reasons:
- The image was uploaded to a note which you don't have access to
- The note which the image was originally uploaded to has been deleted
```

**Comment by jackycute** [comment]
fixed in 1.77.0
