### ISSUE TITLE
Cannot import .md file from Google Drive

### ISSUE THREAD

**Issue by NeverBehave** [hackmdio/hackmd-io-issues#42]
Possibly Related Issue: https://github.com/hackmdio/codimd/issues/352

- I have files with .md in my Google Drive and owned by me, and I try importing them into Hackmd, but folders are shown empty.
- I found that only files exported from Hackmd to my Google Drive can show up properly.

Have anyone else encountered this issue here?

**Comment by jackycute** [comment]
Hi @NeverBehave 
As I mentioned, we can only support files that have extension `.md` and `.html`.
This might be a Google Drive issue if you found that still happened.

**Comment by NeverBehave** [comment]
Hi @jackycute 
As I mentioned, the files are end with extension `.md`, and seems that hackmd.io's Google integration can only work with files it exported. 

Steps to Reproduce:
- Exporting an arbitrary file to Google Drive (`Features.md` for example)
- Import and choose Google Drive, the files can be seems and selected.
- Download file from Google Drive and upload to the same place with a different name, keeping the same extension (`Copy_features.md` for example)
- The uploaded file cannot be retrieve.

![image](https://user-images.githubusercontent.com/17120571/45452315-a644f500-b6ab-11e8-8e73-8b4bbd871d01.png)
![image](https://user-images.githubusercontent.com/17120571/45452337-b361e400-b6ab-11e8-9582-00599e20af3d.png)

It might be an issue related to Gdrive so I am reading the documentation about it, or the app scope when setting the OAUTH or something. But for now it is a bit of annoying if I have to import all files via hackmd.io before I can edit them.

**Comment by NeverBehave** [comment]
@jackycute I have just tried https://draw.io , which can access all files in my drive (not created by draw.io), and I have check the permission here.

Maybe there is misunderstanding of the permission of Gdrive. I am still looking up the API documentation here.  

![image](https://user-images.githubusercontent.com/17120571/45463981-634f4580-b6dc-11e8-9b8d-748ebb8d718b.png)

![image](https://user-images.githubusercontent.com/17120571/45463898-06538f80-b6dc-11e8-8fec-2839b597c733.png)

**Comment by NeverBehave** [comment]
Updates:  https://stackedit.io/ has an interesting option that allows user to choose how to access their Google Drive as well (and it does work), and sorry that I have not yet found the related documentation for this. Any updates so far?

![image](https://user-images.githubusercontent.com/17120571/45732090-c3e0f580-bba8-11e8-82d0-f8a7623b2c83.png)

**Comment by jackycute** [comment]
I think that might a permission scope settings issue, will look into this later.
See the docs here: https://developers.google.com/identity/protocols/googlescopes#drivev3

**Comment by jackycute** [comment]
Fixed for now. Thanks for reporting to us @NeverBehave

**Comment by keelancook** [comment]
I know this is an old thread, but I'm having a similar issue attempting to locate .md files in my google drive that were not created with HackMD. When I attempt to import, the file picker show some but not all of the .md files I have in the Drive folder. No matter what I do, I cannot seem to get it to show me the full number. 

Any suggestions as to how I can see these files, so that I can import them to HackMD and edit? Thanks!
