### ISSUE TITLE
code highlight for Rust is not correct 

### ISSUE THREAD

**Issue by tigercosmos** [hackmdio/hackmd-io-issues#45]
when there is lifetime syntax 'a in Rust code, the highlight will be wrong

correct one as Github show

```rust
fn foo<'a>(s: &'a str) -> &'a str { }
```

what hackmd shows
![](https://user-images.githubusercontent.com/18013815/46594475-e27e4080-cb05-11e8-86c0-a1c82fa202e5.png)

**Comment by tigercosmos** [comment]
@jackycute why close the issue?

**Comment by jackycute** [comment]
Supported rust syntax highlighting in editor.

<img width="1230" alt="2018-10-10 4 08 30" src="https://user-images.githubusercontent.com/2639151/46742162-c534a800-cca6-11e8-8d43-a8dae74a06b6.png">
