### ISSUE TITLE
Book Mode: Multiple hyperlinks in one list element isn't rendered as expected in summary panel

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [hackmdio/hackmd-io-issues#47]
Not sure if this syntax actually supported in book mode, but anyway...

The following source:

```markdown
## 置頂 📌<br>Pinned
* [(中文) 救災即時資訊](/8GSRtWBMTein5AIQ_cYVVw)  
  [(English) Latest Information](/JZAXEPVHQE2q8RjFM5on2g)  
  [(日本語) 最新情報](/o7Mt-Ih1Q-6J4w_DuTxg4g)
* [傷患查詢及醫院狀況<br>Patient Inquiry and Hospital Status](https://g0v.github.io/1021puyuma/)
```

renders to

![default](https://user-images.githubusercontent.com/13408130/47301501-9b3d9700-d651-11e8-8afc-26934ceb4662.png)

Notice the additional gap between the three entries in the summary panel, which seems to be occurred by an additional `<br>` tag in the HTML markup:

![2018-10-22 23-43-03](https://user-images.githubusercontent.com/13408130/47302548-5ebf6a80-d654-11e8-8168-82c97021222b.png)

**Comment by jackycute** [comment]
We fixed this issue recently, feel free to re-open if you found anything 😄
