### ISSUE TITLE
上传图片，一直处于uploading

### ISSUE THREAD

**Issue by zhisays** [hackmdio/hackmd-io-issues#48]
![image](https://user-images.githubusercontent.com/42082498/47652713-9c2a7780-dbc1-11e8-8df8-e4d37f70ab66.png)

**Comment by jackycute** [comment]
您好，請問您是否在中國地區上傳圖片？
因為中國地區使用 imgur 上傳可能會被阻擋，可能要請您先自行上傳再貼入連結

**Comment by zhisays** [comment]
恩，是的，刚试了下imgur，我访问的确有问题，谢啦
![image](https://user-images.githubusercontent.com/42082498/47653000-68038680-dbc2-11e8-8fd2-53fe72fda390.png)

**Comment by BinotaLIU** [comment]
先关闭此 Issue，如果还有问题可再开启或另开 Issue。

Close this issue. You are welcome to open it again or open a new one if you found another issue. Thanks!
