### ISSUE TITLE
"Shared with me" is empty / no notes visible there

### ISSUE THREAD

**Issue by fingolfin** [hackmdio/hackmd-io-issues#49]
A bunch of HackMD documents which were created by others but on which I collaborated are not visible to me anymore on hackmd.io. In fact, if I click on "Shared with me", it just says "No notes with current filters".

In the past, they were definitely shown there. I luckily had some tabs open with some of them, but keeping them there or via bookmarks is of course very annoying. Note that I have write access to the notes in question

I found no way to explicitly add HackMD documents to the "Shared with me" section, so i assume it is meant to be populated automatically, but it clearly isn't for me.

Help!

**Comment by jackycute** [comment]
We're working on that.
The page you're looking for is now at: https://hackmd.io/recent

**Comment by fingolfin** [comment]
OK, great, at least I can see everything there now. Phew. 

Thanks!

**Comment by egrefen** [comment]
I'm having this issue too. Most notes I collaborate on are shared with me, so it would be nice to see them in overview so I we can add labels etc...

**Comment by jackycute** [comment]
"Shared with me" shows in the collaborative page of the tab "Invited me".
"Recent" page has distinguished to another page to avoid confusion.

<img width="620" alt="螢幕快照 2019-12-25 上午12 15 51" src="https://user-images.githubusercontent.com/2639151/71419716-cf747380-26ab-11ea-9cb8-3304af06e5fe.png">

<img width="262" alt="螢幕快照 2019-12-25 上午12 19 09" src="https://user-images.githubusercontent.com/2639151/71419763-33973780-26ac-11ea-94f5-5ddef0abcb08.png">
