### ISSUE TITLE
todo list toggles wrong checkbox if [TOC] is included in document

### ISSUE THREAD

**Issue by silicht** [hackmdio/hackmd-io-issues#50]
If a [TOC] and at least one headline is included in document, clicking on a checkbox is toggling the wrong todo list entry.

I have created an simple test pad:
https://hackmd.io/yLY3d1BTTha53mfNU1v7aA#

**Comment by jackycute** [comment]
duplicated in #51

**Comment by ccoenen** [comment]
(sorry for the unrelated comment)
cool! I didn't know issues could be transferred :-)

**Comment by jackycute** [comment]
@ccoenen it's new feature GitHub just launched 5 days ago 😄 
https://blog.github.com/changelog/2018-10-30-issue-transfer/
