### ISSUE TITLE
todo list toggles wrong checkbox if [TOC] is included in document

### ISSUE THREAD

**Issue by silicht** [hackmdio/hackmd-io-issues#51]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem

If a [TOC] and at least one headline is included in document, clicking on a checkbox is toggling the wrong todo list entry.

#### Current behaviour

Provide steps to reproduce:

I have created an simple test pad:
https://hackmd.io/yLY3d1BTTha53mfNU1v7aA#

1. Go to https://hackmd.io/yLY3d1BTTha53mfNU1v7aA#
2. Toggle checkboxes in view mode

#### Expected behaviour

Toggle right checkbox

#### Environment

I use HackMD on:

**Desktop**
- OS: Linux
- Browser: Firefox / Chromium

**Comment by jackycute** [comment]
Fixed and deployed.
Thanks @silicht for reporting to us 😄
