### ISSUE TITLE
the content of tag is displayed at the beginig of the TOC

### ISSUE THREAD

**Issue by peace098beat** [hackmdio/hackmd-io-issues#52]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io

#### Current behaviour

At the beginning of the sentence writing, 
the content of tag is displayed at the beginig of the TOC.

> jp: 文章の書き始めの時点では、TOCの先頭にtagの内容が表示される

![](https://i.imgur.com/UStmRxr.png)

![](https://i.imgur.com/Kvt0zGz.png)

When H3 is added, 
the content of tag is no longer displayed of the TOC.

> jp: H3を追加したところで、TOC先頭のtagは表示されなくなる

![](https://i.imgur.com/2fWCNn0.png)

#### Expected behaviour

The contents of tag aren't shown to contents.

> jp: 目次にtagの内容は表示されない

#### Environment

I use HackMD on:

**Desktop**
- OS: [macOS]
- Browser: [chrome]
- Brwoser Version: [70.0.3538.77（Official Build） （64bit）]

#### Additional context

None

**Comment by jackycute** [comment]
Fixed and deployed.
Thanks @peace098beat for reporting to us.
