### ISSUE TITLE
Add support of PlantUML for diagrams

### ISSUE THREAD

**Issue by BenjD90** [hackmdio/hackmd-io-issues#53]
**Is your feature request related to a problem? Please describe.**
I'm drawing collaborative sequences diagrams, it's not the main purpose of this tool, but it's working great. I saw that you're using https://bramp.github.io/js-sequence-diagrams/ but there is not a lot of feature supported to draw complexe diagrams.

**Describe the solution you'd like**
A solutions might be to change the tool used to draw the diagram, or to add new type to keep retro-compatibility.

**Describe alternatives you've considered**
I'm thinking of libraries like : [mermaid](https://mermaidjs.github.io/) or the best [plantUML ](http://plantuml.com/)

**Additional context**
Sample of diagram I've done, and on which I'd like to add loops and colors :

![image](https://user-images.githubusercontent.com/8216338/48184203-93f4d980-e331-11e8-8626-7eadf9b47d57.png)

Thanks a lot for this awesome tool, which I can recommend in the company where I work :)

**Comment by mlopezgva** [comment]
Me, too.
PlantUML would be great. And they don't mind people using their server to generate diagrams, they even have sample code in many languages pointing to their server(s).
And for the desktop version, it would be s imple dependency (dot + plantuml).

**Comment by gonzaloserrano** [comment]
So PlantUML support was merged into codimd some weeks ago https://github.com/hackmdio/codimd/pull/1096. Having this on the website would be great!

**Comment by h0jeZvgoxFepBQ2C** [comment]
Yeah, would be really great if you could support PlantUML in Hackmd!

**Comment by Potherca** [comment]
As far as I can tell, this already works!

[![image](https://user-images.githubusercontent.com/195757/98591377-6e0fc000-22d0-11eb-9ddc-3809080a7c12.png)](https://hackmd.io/@Potherca/S1x7gbDtw)

See: https://hackmd.io/@Potherca/S1x7gbDtw

**Comment by jackycute** [comment]
It's working at the moment!
