### ISSUE TITLE
paragraph is not justify default.

### ISSUE THREAD

**Issue by ghost** [hackmdio/hackmd-io-issues#56]
**Is your feature request related to a problem? Please describe.**
Paragraph is not justify default.
I always need to use the code to comply.

```
<style tyle="text/css">
p {
text-align: center;
}
</style>
```

**Comment by jackycute** [comment]
Hi @cmmei 
The default text alignment is left by design.
Would you tell us why you always need it to be justify?

**Comment by cmmei** [comment]
Chinese copywriting is used to being justify. May be just for me myself. = =

Another feature for Chinese copywriting is **spacing before /after number and English words** referring https://github.com/sparanoid/chinese-copywriting-guidelines

**Comment by jackycute** [comment]
Please reopen this if you still having this issue, thanks!
