### ISSUE TITLE
Title Not Changing

### ISSUE THREAD

**Issue by metalqueen1** [hackmdio/hackmd-io-issues#58]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### Read our Official tutorial

It's on https://hackmd.io/c/tutorials/

或是中文版 https://hackmd.io/c/tutorials-tw/

### What's the problem

Title is not changing when I change it. 

#### Current behaviour

> Screenshot (optional)

I type the title in...

![image](https://user-images.githubusercontent.com/45250572/48880776-ee853f80-eddf-11e8-8581-c978472cbb51.png)

then

The very first one I just recently created still has 'Untitled' on it.

![image](https://user-images.githubusercontent.com/45250572/48880809-11175880-ede0-11e8-9e23-281f851bbb8a.png)

Provide steps to reproduce:

1. Go to 'add note'
2. Click on 'Insert title here' and insert titles
3. Publish and go to main overview page with your notes
4. See error 'Untitled' on recent creation

If possible, create a note with reproducible content and share the link with us.

e.g. note link: https://hackmd.io/s/SkU0AcmRm#

#### Expected behaviour

I'd like the 'Untitled' portion to change to the title I wrote for it. 

#### Environment

I use HackMD on:

**Desktop**
- Firefox 63.0.3 (64-bit)

#### Additional context

Am I misunderstanding how to add titles to my content?

**Comment by Yukaii** [comment]
Reopen if you still encounter this problem :D
