### ISSUE TITLE
Logging in through 2 different services causes multiple accounts to be created.

### ISSUE THREAD

**Issue by resurge** [hackmdio/hackmd-io-issues#59]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem
I logged in with 3 different login methods (Facebook, Github & Google) and they don't have the same notes. (= I have 3 separate accounts now)

#### Current behaviour

1. Log in through Facebook
2. Make a note and save it
3. Log out
4. Log in through an other provider (I tried Github and Google)
5. Notice there is no note any more. 
6. Log out & log in through Facebook again - Notes are back

#### Expected behaviour
After logging in with a different provider I should be able to see my old notes.
( = It shouldn't make a new account, but link to the existing one)

#### Environment
I use HackMD on:
**Desktop**
- OS: XUbuntu 18.04.1 LTS 
- Browser: Firefox
- Browser Version: 63.0

#### Additional context

When I log in through Facebook or Github I can see that my email is not filled out on my profile, But it is filled out when I log in through Google. 
So I'm guessing you're not asking for the email from some providers? And I think that's what you'll need to link the accounts?

**Comment by resurge** [comment]
This is somewhat related to this feature request: https://github.com/hackmdio/hackmd-io-issues/issues/15

**Comment by jackycute** [comment]
You can now integrate all your accounts into one from Settings page.
https://hackmd.io/settings

<img width="453" alt="螢幕快照 2019-12-25 上午12 25 25" src="https://user-images.githubusercontent.com/2639151/71419916-24fd5000-26ad-11ea-8c75-b1212b07dc97.png">
