### ISSUE TITLE
Send update mail despite disabled in settings

### ISSUE THREAD

**Issue by blapplications** [hackmdio/hackmd-io-issues#62]
### Is this a hackmd.io issue?

- [x ] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

或是中文版 https://hackmd.io/c/tutorials-tw/

### What's the problem
When I create a new file and share it I get an mail about updates all 5 minutes. 
I disabled the mail notifications in the settings but it doesn't change something.

#### Current behaviour

Provide steps to reproduce:

1. Create a new file
2. Share it
3. Disable mail notification
4. Let someone change something
5. You get an change e-mail every 5 - 15 minutes

#### Environment

I use HackMD on:

**Desktop**
- OS: [Windows, Linux]
- Browser: [chrome, firefox]

**Comment by jackycute** [comment]
Hi @blapplications 
Thanks for reporting to us.
Could you share the reproducable note link here? or send email to hackmdio@gmail.com.

We'll look into this.

**Comment by blapplications** [comment]
It happens on every file, created by different people.

**Comment by jackycute** [comment]
Fixed and deployed.
Thanks @blapplications for reporting to us 😄

**Comment by blapplications** [comment]
Love you guy! Thanks for that. :)
