### ISSUE TITLE
[Feature request] Tag other users

### ISSUE THREAD

**Issue by edingroot** [hackmdio/hackmd-io-issues#63]
Hi @jackycute,

We are using Hackmd in our development team, it really helps a lot!
However, if we can **tag other users** in the document so they can get notified would be a useful feature :)

Thank you!
Chi Chang

**Comment by edingroot** [comment]
Reference issue #40

**Comment by jackycute** [comment]
Thank you @edingroot 
We've supported mentioning other users in the note or in the comment now.
