### ISSUE TITLE
embed gist bug

### ISSUE THREAD

**Issue by ysuper** [hackmdio/hackmd-io-issues#66]
embed gist is broken
reason is append .json to link
ex: {%gist ysuper/xxx%}
will show↓
Failed loading gist https://gist.github.com/ysuper/xxx.json: error

**Comment by Yukaii** [comment]
Hi @ysuper 

You need to place **gist id** when you embed gist, without username. For example, to embed the gist https://gist.github.com/ysuper/4387a5ac831f4263995e1607a2aebe3e , you need to write:

```md
{% gist 4387a5ac831f4263995e1607a2aebe3e %}
```

**Comment by ysuper** [comment]
請問 會在網路上喵喵叫的都是男孩子 在嗎?
再麻煩有空看一下我的回覆貼圖，感謝！

**Comment by jackycute** [comment]
Hi @ysuper, this issue have been confirmed a CSP problem.
We will fix this soon.

**Comment by ysuper** [comment]
好的 ，感謝二位😀

**Comment by ysuper** [comment]
哈囉~ 這個問題已經發生一週了，問題真的不是我第一則留言反應的原因嗎?↓
目前超連結會自動加.json，可能把.json去掉，就可以不限制用json格式顯示進而達到正常效果?
reason is append .json to link
ex: {%gist ysuper/xxx%}
will show↓
Failed loading gist https://gist.github.com/ysuper/xxx.json: error

**Comment by jackycute** [comment]
您好，因為我們正在忙別的 issue，所以還沒上版
確定是這個問題沒錯 :)

**Comment by ysuper** [comment]
okok 辛苦了!
那就靜候佳音:)

**Comment by jackycute** [comment]
Fixed and deployed.
Thanks @ysuper for reporting to us.

**Comment by ysuper** [comment]
確認已修正，感謝協助!
