### ISSUE TITLE
Descriptions of privileges are unclear

### ISSUE THREAD

**Issue by fweng322** [hackmdio/hackmd-io-issues#68]
### Is this a hackmd.io issue?

- [X] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### Read our Official tutorial

It's on https://hackmd.io/c/tutorials/

或是中文版 https://hackmd.io/c/tutorials-tw/

### What's the problem
The descriptions of "Limited", "Locked" and "Protected" are unclear.  For example, what does "forbid guests" mean while only owner can edit?  Forbid guests to view? to comment? When I set the pad to "Locked" nobody can add comments.  When I set to "Protected" nobody except me can view it.  They seemed to have different behaviors from what I interpreted these options.

#### Current behaviour
When I set the pad to "Locked" nobody can add comments.  When I set to "Protected" nobody except me can view it.  They seemed to have different behaviors from what I interpreted these options.

For example, I have no idea about what's the differences between "Editable" and "Limited".  "Signed-in people can edit" should apply to "Not-signed-in people (guests??) can view but can not edit", then what does "forbid guests" mean?

> Screenshot (optional)
![screenshot_20181228_125134](https://user-images.githubusercontent.com/1000315/50504323-cad0ab80-0aa7-11e9-8195-5d6f1272d26b.png)

Provide steps to reproduce:

If possible, create a note with reproducible content and share the link with us.
e.g. note link: https://hackmd.io/features

https://hackmd.io/s/SygyXxPzbE

#### Expected behaviour
(description of expected behaviour)

#### Environment

I use HackMD on:

**Desktop**
- OS: Kubuntu 18.04
- Browser: Google chrome
- Browser Version: 版本 71.0.3578.98 (正式版本)

**Comment by jackycute** [comment]
We've improved the permission popover UI, should be clearer now.

<img width="324" alt="2019-01-19 3 31 36" src="https://user-images.githubusercontent.com/2639151/51423745-7aa8bd00-1bff-11e9-9706-376a328de901.png">

**Comment by fweng322** [comment]
Yes, much clearer.  Thanks.
