### ISSUE TITLE
Export documents while the server is offline

### ISSUE THREAD

**Issue by hunan-rostomyan** [hackmdio/hackmd-io-issues#7]
I'm connected to the internet, but every document I open shows up blank and stays in offline mode.

<img width="1430" alt="screen shot 2018-02-28 at 8 46 46 am" src="https://user-images.githubusercontent.com/5122980/36802876-f40ed836-1c6a-11e8-80b6-fba909d5c0f4.png">

When I download a document, I get an empty markdown file, even though the file is supposed to be non-empty. There seems to be some issue with the server at the moment, so it's 503-ing.

**Question.** Is there any way to export all of the documents (preferably in markdown format) at once, without having to first render the documents (because rendering doesn't seem to always work)?

(This is a copy of [hackmd issue 747](https://github.com/hackmdio/hackmd/issues/747).)

**Comment by hunan-rostomyan** [comment]
Got help from the chat:

> You can read all your previous notes in static mode by adding "/publish" to the URL of your notes. For example, if you have a note at https://hackmd.io/ABCDEFGHIJK1234567890, you can view its static content at https://hackmd.io/ABCDEFGHIJK1234567890/publish

The ability to export the data would still be great.

**Comment by jackycute** [comment]
You can now download all your notes to a zip file in one click.
https://hackmd.io/settings

<img width="568" alt="螢幕快照 2019-12-25 上午12 22 53" src="https://user-images.githubusercontent.com/2639151/71419852-b9b37e00-26ac-11ea-97d3-7b0403eedf8c.png">
