### ISSUE TITLE
Your list + mathjax + indentation is problematic

### ISSUE THREAD

**Issue by nowexactly513** [hackmdio/hackmd-io-issues#70]
<img width="957" alt="image" src="https://user-images.githubusercontent.com/45745272/50574415-407ba500-0e23-11e9-8d9f-94c13f957478.png">

I think the picture describes everything I want to say.

And I also encountered a case that

 - $one
mathjax
looks like
this$
    - with indentation

, which makes everything _beautiful_.

**Comment by jackycute** [comment]
We've upgraded MathJax to version 2.7.5.
Could you check if this fix this issue?
