### ISSUE TITLE
手機模式的書本模式畫面會顯示不出來

### ISSUE THREAD

**Issue by wayne930242** [hackmdio/hackmd-io-issues#71]
### Is this a hackmd.io issue?

- [O ] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem

手機模式的書本模式畫面會顯示不出來。

使用的是 android 手機的 google 瀏覽器。

#### Current behaviour

Provide steps to reproduce:

1. 以書本模式的連結開啟一個 hackmd 筆記

#### Expected behaviour

(description of expected behaviour)

#### Environment

I use HackMD on:

**Mobile**

android 的平板和手機都遇到這個問題，使用的是 google chrome 瀏覽器。

**Comment by jackycute** [comment]
您好，我們這邊看是正常的，不過目前載入時間較久，可以先請您多等候載入嗎？

另外，可以請您提供筆記的連結、您手機的 OS 版本與瀏覽器的版本嗎？

**Comment by jackycute** [comment]
我們最近在 book mode 載入的時候，加上一個提示載入中的動畫，希望有幫助！
