### ISSUE TITLE
SlideShare embed feature not working

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [hackmdio/hackmd-io-issues#74]
Refer https://hackmd.io/features?both#SlideShare , the slide isn't rendered in the preview pane.

![screenshot](https://user-images.githubusercontent.com/13408130/50051013-80b10700-0144-11e9-84d2-2811b72aa1cb.png)

**Comment by jackycute** [comment]
We've fixed this, thanks for reporting to us @Lin-Buo-Ren
