### ISSUE TITLE
export all docs in a single go, for backup

### ISSUE THREAD

**Issue by dch** [hackmdio/hackmd-io-issues#75]
**Is your feature request related to a problem? Please describe.**

I'd like a separate trusted backup or export to ensure my data is safe by storing it myself in plain markdown.

**Describe the solution you'd like**

A single script to run, or a button to click on in the web ui, that exports a tarball/zipfile of all my docs.

**Describe alternatives you've considered**

An API to query all the active documents & an API to retrieve (or "clone") a given document and all its history, perhaps in the form of a git repo.

Or, a single git repo that spans all my docs that I can simply `git pull` to retrieve all updates.

**Comment by SasquatchYuja** [comment]
I agree, that's be great to be able to download all/only-selected documents as .md/.odt/.html and additionally as .pdf, in one single tarball, without having to visit and click download button for all of them

**Comment by jackycute** [comment]
We are now supporting to export all your notes to a zip in `.md` format at https://hackmd.io/settings

<img width="571" alt="螢幕快照 2019-08-07 下午9 51 59" src="https://user-images.githubusercontent.com/2639151/62628305-9f773e80-b95d-11e9-9fc0-269e66afb3c0.png">

Enjoy!

**Comment by SasquatchYuja** [comment]
I was referring to the ability of bulk-downloading notes that you don't own but that appear in your account. Those you contributed to or just opened. And thus the possibility to select / exclude some. In addition, the option to select output formats like pdf / html, would be great.

**Comment by samlaf** [comment]
I would also like to have access to this feature. I can't currently download notes from my team/company.
