### ISSUE TITLE
Mermaid sequence diagrams look bad (especially notes)

### ISSUE THREAD

**Issue by dvtomas** [hackmdio/hackmd-io-issues#76]
### Is this a hackmd.io issue?

- [x ] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem

Mermaid sequence diagrams look ugly. The biggest problem is that multiline notes have way too much space after each line. Also, the fixed-width font inside the actor names and loop description looks bad, and makes the text unnecessarily wide.

I'm using the following diagram for testing:

```mermaid
sequenceDiagram

participant MP as MP-HOST
participant MS as Measuring System

Note left of MP: This is a long <br> sentence split into <br> several lines.

loop each century
	MP-->>MS: Do do do dsomething repeatedly
end

Note right of MS: Another <br> multiline sentence.
 ``` 

#### Current behaviour

https://hackmd.io/s/HyhXYlqmN# looks like this:

https://www.imgup.cz/image/LTQT
  
#### Expected behaviour

https://www.imgup.cz/image/LTQ2

https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG5cbnBhcnRpY2lwYW50IE1QIGFzIE1QLUhPU1RcbnBhcnRpY2lwYW50IE1TIGFzIE1lYXN1cmluZyBTeXN0ZW1cblxuTm90ZSBsZWZ0IG9mIE1QOiBUaGlzIGlzIGEgbG9uZyA8YnI-IHNlbnRlbmNlIHNwbGl0IGludG8gPGJyPiBzZXZlcmFsIGxpbmVzLlxuXG5sb29wIGVhY2ggY2VudHVyeVxuXHRNUC0tPj5NUzogRG8gZG8gZG8gZHNvbWV0aGluZyByZXBlYXRlZGx5XG5lbmRcblxuTm90ZSByaWdodCBvZiBNUzogQW5vdGhlciA8YnI-IG11bHRpbGluZSBzZW50ZW5jZS4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ

#### Environment

I use HackMD on:

**Desktop**
- OS: Linux
- Browser:Firefox

**Comment by gustavorps** [comment]
Is really small in mobile view and is not able to open or zoom
![Sequence Diagram on Mobile](https://i.imgur.com/NMjNpFv.png)

**Comment by jackycute** [comment]
Hi everyone,
Sorry for the late reply.
We have fixed a height styling issue on Firefox at 2022/8/2 (https://hackmd.io/s/release-notes#-EE-1430-2022-08-02-2000).
I have tested your diagram on HackMD and now it looks just like the mermaid live demo editor.
