### ISSUE TITLE
Contiguous lines should form a single paragraph without break

### ISSUE THREAD

**Issue by reagle** [hackmdio/hackmd-io-issues#79]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io

### What's the problem

Incorrect implementation of [CommonMark paragraphs](https://spec.commonmark.org/0.28/#paragraphs) 

#### Current behaviour

In the markdown:

```
This is a line
that should be continued with no break whatsoever.
```

You [incorrectly render a carriage return](https://hackmd.io/mHymypDtR52-bm9BOhTizg?both) after the word `line`.

<img width="535" alt="screen shot 2019-02-26 at 4 20 17 pm" src="https://user-images.githubusercontent.com/596814/53447186-a2e7c080-39e2-11e9-8f86-87f116b13250.png">

#### Expected behaviour

[This example](https://spec.commonmark.org/dingus/?text=This%20is%20a%20line%0Athat%20should%20be%20continued%20with%20no%20break%20whatsoever.) at the commonmark dingus show that there is no break after `line`.

<img width="1070" alt="screen shot 2019-02-26 at 4 21 37 pm" src="https://user-images.githubusercontent.com/596814/53447197-a67b4780-39e2-11e9-9dd7-afacb898a4a7.png">

#### Environment

I use HackMD on:

**Desktop**
- OS: MacOS Mojave; Chrome 72.0.3626.119

**Comment by reagle** [comment]
Because of this behavior, my students who write using HackMD *think* they have (pseudo) paragraphs because of the line breaks, but when I render their work using pandoc (commonmark) I get huge mono-graphs.

**Comment by reagle** [comment]
It looks like you render the markdown as:

```
    <div id="doc" class="container markdown-body">This is a line
that should be continued with no break whatsoever.
</div>
```

**Comment by reagle** [comment]
That could be rendered correctly by a browser **if** it has the same styling as <p>. I suspect you have CSS that sets `white-space: pre` on that `div`.

**Comment by jackycute** [comment]
Hi @reagle! Thanks for reaching us.
HackMD enables the line breaks by default, so newline will result in a line break.

Since Pandoc escape line breaks by default (see [here](http://pandoc.org/MANUAL.html#extension-escaped_line_breaks)).
I think you can use follow command to disable the extension.
```
$ pandoc -f markdown-escaped_line_breaks doc.md -o doc.pdf
```

**Comment by reagle** [comment]
Thanks for the response, though your suggestion will not work. I believe you've misunderstood the Commonmark spec and the pandoc option.

In Commonmark, line breaks work by way of appending two spaces to the end of a line. Otherwise lines are inline concatenated within a `p` element -- with its `white-space: normal` styling.

Pandoc long had the option of also using an escaped (backslashed) space to force a break, which can be enabled with that option. As you can see below, it does not change the Commonmark behavior.

```
> cat test.md
This is a line
that should be continued with no break whatsoever.
> pandoc test.md
<p>This is a line that should be continued with no break whatsoever.</p>
> pandoc -f markdown-escaped_line_breaks test.md
<p>This is a line that should be continued with no break whatsoever.</p>
```

**Comment by jackycute** [comment]
I know in CommonMark line break works when appending two spaces after the line.
But we decided to keep both cartridge return and two spaces at the end of the line work as line break for easier and quicker to write in multiple paragraphs.

I just tried the `--wrap` option and it worked.

```
> pandoc --wrap=preserve test.md
<p>This is a line
that should be continued with no break whatsoever.</p>
```

**Comment by reagle** [comment]
Pandoc's `wrap` option will "Determine how text is wrapped in the output (the source code, not the rendered version)." If you generate a HTML page via pandoc: `pandoc -s --wrap=preserve test.md -o test.html` your output should look like this in the browser.

<img width="486" alt="screen shot 2019-02-27 at 8 53 44 am" src="https://user-images.githubusercontent.com/596814/53495142-509fb180-3a6d-11e9-8e4b-5eaa8a42fe83.png">

There's no break because the standard rendered of HTML's `p` element ignores them.

**Comment by jackycute** [comment]
How about this?

```
> pandoc -f markdown+hard_line_breaks test.md
<p>This is a line<br />
that should be continued with no break whatsoever.</p>
```

<img width="432" alt="2019-02-27 10 15 39" src="https://user-images.githubusercontent.com/2639151/53496551-40bfb600-3add-11e9-87ff-748014e57eac.png">

**Comment by reagle** [comment]
Yes, there are many ways to force a break from the default CommonMark behavior: double space at end, escaped space at end, and `<br>` element. But if HackMD doesn't follow the spec, there's no way to get back to the default behavior. In any case, I'm not trying to emulate the non-conformant behavior, I want the specified behavior. 

Otherwise, my only option when processing HackMD markdown so to prevent mono-paragraphs when using a compliant render would be to pre-process HackMD markdown and detect if the user has written conformant or non-conformant markdown. If I don't find any real paragraphs (e.g., double CR/LF), I'd have to use a heuristic for detecting your pseudo-paragraphs (e.g., short line followed by a long line) and it'd be buggy and gross.

If you don't understand, perhaps we cold take this to the [CommonMark](https://talk.commonmark.org/) forum? Other people might be able to explain better.

**Comment by reagle** [comment]
Again, to fix this -- and stop my students from writing pseudo-paragraphs -- all you have to do is tweak your CSS so your `div.markdown-body` elements emulate a standard `p` element (probably via the `white-space` directive). I looked at your CSS but couldn't figure it out because it's fairly compressed.

**Comment by jackycute** [comment]
Thanks for explaining to me.

There is an option to turn off the breaks, but you'll need to specify a front-matter.
```
---
breaks: false
---
```
https://hackmd.io/yaml-metadata#breaks

We do want to follow all the specs but at same time make user comfortable to write.
I'm thinking there might be an option letting user to custom the rendering rules otherwise it'll use the original specs.
And the reason I don't really want to change the CSS styles right now because there are many docs already written in this format and I would like to keep it as-is.

BTW, the render we're using is markdown-it https://github.com/markdown-it/markdown-it

**Comment by reagle** [comment]
Okay, good, glad we share an understanding. Are you saying markdown-it has the same problem you inherited, or is this something you added? Is this bug in Codi as well? If so, I suppose we should share this bug there?

In terms of migrating to a conformant rendering, I appreciate you don't want to do a unilateral change. You'd turn lots of peoples' pages into mono-paragraphs. (BTW: Hitting return twice isn't uncomfortable...?) Some brainstorming:
1. Write a heuristic that migrates peoples' markdown, but that might be hard.  This could be automatic (too dangerous probably) or allow people to opt-in.
2. Have all new accounts use conformant (CR) rendering, grandfather old accounts with non-conformant rendering (NCR).
3. Make all new *pages* use CR. New accounts would be fine. Older accounts would notice the difference and perhaps could opt for CR or select to keep all pages NCR.
...

Thanks for being so responsive!

**Comment by jackycute** [comment]
Please take a look at the markdown-it doc:
https://markdown-it.github.io/markdown-it/#MarkdownIt.new

We use `default` preset and add the `breaks: true` option to init markdown-it options. So I think markdown-it follows the line break spec at first place (since default `breaks` option is false).

Yes, CodiMD use the same renderer and options to init, we should share this.

I will talk to our team and try figure out a solution.
Thanks for helping us!

**Comment by reagle** [comment]
Hi, wondering if there's any update?

**Comment by jdhoek** [comment]
Is there a way to configure CodiMD to use only the CommonMark hard breaks without having to add a preamble to each document?

> We do want to follow all the specs but at same time make user comfortable to write.

Why not follow the specs and:

* Document the two-spaces markup for hard breaks in the *help*.
* Add a button to the toolbar for inserting hard breaks via the GUI

That would help users to understand hard breaks in Markdown, and allow users who expect normal Markdown to work to use CodiMD/HackMD.

**Comment by reagle** [comment]
I use HackMD with a class, and as I think about the fall semester I wonder if there's been any progress on this, such that new accounts follow the standard/specified behavior? (Existing accounts could be grandfathered, with the option to change to standard behavior.)

**Comment by jackycute** [comment]
We are currently working on this, would possibly release in the next month.

**Comment by jackycute** [comment]
Hi @reagle and @jdhoek,
We are now support changing note line break rendering rule and you can change the default rule at https://hackmd.io/settings

<img width="611" alt="螢幕快照 2019-08-07 下午9 49 23" src="https://user-images.githubusercontent.com/2639151/62628095-3c85a780-b95d-11e9-99ee-fe7e75634043.png">

See more: https://hackmd.io/c/tutorials/%2Fs%2Flink-with-github

Enjoy!

**Comment by reagle** [comment]
Excellent. Will CommonMark be the default for new accounts? In a month I'll have 30 students creating new accounts and I'd like CommonMark to be the default. If I have to instruct them on how to do this, then I'll end up with a mix which would be even worse.

BTW: Is it possible to sync all of my pages with a Github repo?

**Comment by jackycute** [comment]
We've considered that, but we found many users get used to and love to write with hard breaks, so it will still be as is at the moment (sorry about that).

You need to sync them one by one for now, we'll make a full repo syncing later when we ready.

**Comment by reagle** [comment]
Drats, that's too bad. People will get used to a lot, so I think it'd be better to embrace the benefits of the recommended route, including "semantic line feeds" and, most importantly, interoperability.

**Comment by reagle** [comment]
Today is one of those days I most dislike this default. A student writes prep-exam questions, which look decent on HackMD but cruddy when collected and processed with pandoc.

<img width="2055" alt="Screenshot 2020-02-14 08 30 32" src="https://user-images.githubusercontent.com/596814/74537209-a7fd9280-4f07-11ea-9cd6-b2cfaeb5701d.png">
