### ISSUE TITLE
嵌入錯誤的 HackMD 頁面導致畫面異常

### ISSUE THREAD

**Issue by lk7892332** [hackmdio/hackmd-io-issues#82]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io

### What's the problem

使用 {%hackmd %} 嵌入頁面時，若輸入的網址不正確，會導致整個畫面被蓋住。
若輸入 {%hackmd new#%} ，則會讓瀏覽的人一直新增新筆記。

#### Current behaviour

![image](https://user-images.githubusercontent.com/26433740/54489199-ded8bc00-48e4-11e9-9690-94e49b24f2bb.png)
Note link:
畫面被蓋住：
https://hackmd.io/h_c9giGESuCNT3S8_WAh0w?view
進入後會一直新增筆記：
https://hackmd.io/0PaBAMU2SneGdHKjVJ77SQ

#### Environment

I use HackMD on:

**Desktop**
- OS: Windows 10
- Browser: Chrome
- Browser Version: 73.0.3683.75

**Comment by jackycute** [comment]
您好，此問題已修正，感您的回報
