### ISSUE TITLE
無法載入圖片

### ISSUE THREAD

**Issue by GoulongWang** [hackmdio/hackmd-io-issues#83]
我截圖貼上 Hackmd 上用了都正常，也都有顯示截圖畫面，然後用到一半突然就無法加圖片進去了，加進去的時候完全沒反應，我原本以為是超過字數上限，但看了一下還離 100000 字元差的遠，也還能正常打字。我有嘗試重新登入和開新的筆記也都無法加圖片

**Comment by jackycute** [comment]
您好，由於目前圖片上傳依賴 imgur 服務，請您稍後重新嘗試
imgur 的服務偶而會因為流量過大而暫時無法使用
謝謝～
