### ISSUE TITLE
建議加入時序圖繪圖工具 Wavedrom

### ISSUE THREAD

**Issue by GitOnion** [hackmdio/hackmd-io-issues#84]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
https://github.com/wavedrom/wavedrom

**Describe alternatives you've considered**
N/A

**Additional context**
使用者寫信到 hackmdio@gmail.com 信箱來的

```
建議加入時序圖繪圖工具
Darrent Chen <darrent.chen@gmail.com>| Apr 7, 2019, 9:58 PM (3 days ago)
敬啟者：

建議如題，例： https://wavedrom.com 

陳秋湧
```

**Comment by jackycute** [comment]
Now we support plantuml and it has timing function syntax.
https://plantuml.com/timing-diagram

Feel free to open another issue if you still prefer wavedrom.
