### ISSUE TITLE
How do I exit slide mode?

### ISSUE THREAD

**Issue by AndreaPi** [hackmdio/hackmd-io-issues#85]
As per title. Once I enter [Slide Mode](https://hackmd.io/p/slide-example#/), exiting it seems impossible (<kbd>Esc</kbd>, <kbd>⌘</kbd>+<kbd>C</kbd>, <kbd>⌥</kbd> + <kbd>C</kbd>, etc. don't work). The only way to exit it seems to close the corresponding browser tab (<kbd>⌘</kbd>+<kbd>W</kbd> in Chrome). Is that correct?

**Comment by jackycute** [comment]
You can scroll down the page and click the pencil icon on the bottom right to go back to edit mode.

<img width="494" alt="螢幕快照 2019-08-07 下午10 01 40" src="https://user-images.githubusercontent.com/2639151/62629020-f4678480-b95e-11e9-9a7c-12400438de91.png">
