### ISSUE TITLE
How to change font size for Slide mode?

### ISSUE THREAD

**Issue by AndreaPi** [hackmdio/hackmd-io-issues#87]
How can I change the main text (not a heading) font size for a single slide?

**Comment by jackycute** [comment]
Hi @AndreaPi,

You can put CSS into you note.
For example, put below text in your note:
```
<style>
.reveal {
  font-size: 24px;
}
</style>
```

Will make the slide mode font size smaller (default font-size is 42px).

**Comment by AndreaPi** [comment]
Good to know! Thanks

**Comment by darkquasar** [comment]
Hi guys, this changes the font size for **all** the slides instead of just a single slide. Do you have any advice on how to go about changing the font size for a single slide?

**Comment by banderlog** [comment]
You are able to alter single slide attributes via `.slide` selector:
```html
<!-- .slide: style="font-size: 12px;" -->
```
