### ISSUE TITLE
View for 'Recent' same as 'Overview' please

### ISSUE THREAD

**Issue by nadiaburborough** [hackmdio/hackmd-io-issues#91]
As a team we create and share many hackmd docs - I like the ability to change the view from Grid to List view from the 'Overview' page. I'd like the same functionality in 'Recent' page please so i can view the docs easier / quicker.

**Comment by jackycute** [comment]
We will consider that, thanks for telling us @nadiaburborough !

**Comment by jackycute** [comment]
You can now change the layout of Recent page as well.

<img width="264" alt="螢幕快照 2019-12-25 上午12 12 16" src="https://user-images.githubusercontent.com/2639151/71419606-3c3b3e00-26ab-11ea-977d-b6c56bd09418.png">
