### ISSUE TITLE
Slide mode no more?

### ISSUE THREAD

**Issue by dnafication** [hackmdio/hackmd-io-issues#92]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### Read our Official tutorial

It's on https://hackmd.io/c/tutorials/

或是中文版 https://hackmd.io/c/tutorials-tw/

### What's the problem
I had slides written in hackmd.io but when it came to presenting them last tuesday, the service was no more. Is that service being brought down?

#### Environment

I use HackMD on:

**Desktop**
- OS: Windows
- Browser: Chrome
- Browser Version: [75]

**Comment by jackycute** [comment]
Hi @dnafication, thanks for reaching us.
The slide mode now is in the top right sharing menu and hit “Preview” to see your slide.

**Comment by dnafication** [comment]
Thank you. I didn't see that change.
