### ISSUE TITLE
Sometimes I can't get into hackmd.io but when I choose another network,it works!I don't know what I did in network that I can't get into hackmd.io..

### ISSUE THREAD

**Issue by ArcherLoki** [hackmdio/hackmd-io-issues#93]
### Is this a hackmd.io issue?

- [ ] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### Read our Official tutorial

It's on https://hackmd.io/c/tutorials/

或是中文版 https://hackmd.io/c/tutorials-tw/

#### Current behaviour

> Screenshot (optional)

Provide steps to reproduce:

If possible, create a note with reproducible content and share the link with us.

e.g. note link: https://hackmd.io/features

#### Expected behaviour

(description of expected behaviour)

#### Environment

I use HackMD on:

**Desktop**
- OS: [eg. macOS]
- Browser: [e.g. chrome, safari, firefox, opera]
- Browser Version: [71]

**Mobile**

- Device: [e.g. iPhone XS]
- OS: [e.g. iOS 12.1]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 23]

**Comment by ArcherLoki** [comment]
Oh I use win10~
Thanks a lot~

**Comment by jackycute** [comment]
Hi @ArcherLoki Thanks for reaching us.

Could you describe more about what's the network you've chosen?
Did you use any proxy or VPN? The network provider (ISP or company) might prohibit our domain?

**Comment by jackycute** [comment]
This seems like an ISP issue, feel free to re-open if you found anything 😄
