### ISSUE TITLE
Common API

### ISSUE THREAD

**Issue by fabiocosta0305** [hackmdio/hackmd-io-issues#95]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be nice if Hackmd.io provides an API that could be used for third-party applications to sync and edit files (like Simplenote does) so anyone could take files and so, edit and sync

**Comment by jackycute** [comment]
Hi @fabiocosta0305,
We have supported HackMD API from 2022/2/21, you can read more here: https://blog.hackmd.io/blog/2022/02/21/be-creative-with-hackmd-api
It's easy to get started with Developer Portal https://hackmd.io/@hackmd-api/developer-portal and view some use cases: https://hackmd.io/@docs/HackMD_API_Book

We also released HackMD extension for VSCode which is the best companion for productivity: https://marketplace.visualstudio.com/items?itemName=HackMD.vscode-hackmd

Thank you!
